
export const UI_COPY_BY_LANG = {
  en: {
    common: {
      all: 'All',
      search: 'Search',
      sort: 'Sort',
      market: 'Market',
      brokerage: 'Broker',
      account: 'Account',
      status: 'Status',
      details: 'Details',
      clearFilters: 'Clear filters',
      noValue: 'No value',
      noRows: 'No rows to display.',
      help: 'Show explanation',
      helpFor: (label: string) => `${label} explanation`,
      closeHelp: 'Press Esc to close.',
      notRecorded: 'Not recorded',
      elapsed: 'elapsed',
    },
    freshness: {
      labels: {
        fresh: 'Fresh',
        stale: 'Needs refresh',
        drift: 'Source changed',
        missing: 'No data',
      },
      descriptions: {
        fresh: 'Collected within the expected refresh window.',
        stale: 'The last collection is old enough to need a refresh.',
        drift: 'The source file changed after ingestion and needs review.',
        missing: 'The data has not been collected or is unavailable.',
      },
    },
    priority: {
      high: 'High',
      medium: 'Medium',
      low: 'Low',
    },
    runStatus: {
      success: 'Complete',
      failed: 'Failed',
      degraded: 'Degraded',
      running: 'Running',
      pass: 'Pass',
    },
    error: {
      title: 'This page could not be built',
      body: 'The page asked the local database for something it could not answer. The rest of the dashboard is unaffected — the data itself has not changed.',
      retry: 'Try again',
      home: 'Back to overview',
      reference: 'Reference',
      notFoundTitle: 'No such page',
      notFoundBody: 'That address does not match any screen in this dashboard.',
    },
    autoRefresh: {
      offline: 'Offline',
      lastChecked: 'last checked',
      refreshing: 'Refreshing...',
      lastRefresh: 'Last refresh',
      interval: (seconds: number) => `${seconds}s interval`,
      auto: (seconds: number) => `Auto-refresh every ${seconds}s`,
      paused: 'Auto-refresh paused',
      pausedSince: (clock: string) => `Auto-refresh paused · showing ${clock}`,
      pause: 'Pause auto-refresh',
      resume: 'Resume auto-refresh',
      refreshNow: 'Refresh now',
    },
  },
  ko: {
    common: {
      all: '전체',
      search: '검색',
      sort: '정렬',
      market: '시장',
      brokerage: '증권사',
      account: '계좌',
      status: '상태',
      details: '상세 보기',
      clearFilters: '필터 초기화',
      noValue: '값 없음',
      noRows: '표시할 데이터가 없습니다.',
      help: '설명 보기',
      helpFor: (label: string) => `${label} 설명`,
      closeHelp: 'Esc 키를 누르면 닫힙니다.',
      notRecorded: '기록 없음',
      elapsed: '경과',
    },
    freshness: {
      labels: {
        fresh: '최신',
        stale: '갱신 필요',
        drift: '원본 변경',
        missing: '데이터 없음',
      },
      descriptions: {
        fresh: '정해진 갱신 주기 안에 수집된 데이터입니다.',
        stale: '마지막 수집 후 시간이 지나 새로고침이 필요합니다.',
        drift: '원본 데이터가 이전과 달라져 확인이 필요합니다.',
        missing: '아직 수집되지 않았거나 사용할 수 없는 데이터입니다.',
      },
    },
    priority: {
      high: '높음',
      medium: '보통',
      low: '낮음',
    },
    runStatus: {
      success: '완료',
      failed: '실패',
      degraded: '일부 기능 저하',
      running: '진행 중',
      pass: '통과',
    },
    error: {
      title: '이 페이지를 만들 수 없었습니다',
      body: '페이지가 로컬 데이터베이스에 요청한 내용을 처리하지 못했습니다. 대시보드의 나머지는 영향을 받지 않으며, 데이터 자체는 그대로입니다.',
      retry: '다시 시도',
      home: '개요로 돌아가기',
      reference: '참조 번호',
      notFoundTitle: '없는 페이지입니다',
      notFoundBody: '이 주소에 해당하는 화면이 대시보드에 없습니다.',
    },
    autoRefresh: {
      offline: '오프라인',
      lastChecked: '마지막 확인',
      refreshing: '갱신 중...',
      lastRefresh: '마지막 갱신',
      interval: (seconds: number) => `${seconds}초 간격`,
      auto: (seconds: number) => `${seconds}초마다 자동 갱신`,
      paused: '자동 갱신 멈춤',
      pausedSince: (clock: string) => `자동 갱신 멈춤 · ${clock} 기준`,
      pause: '자동 갱신 멈추기',
      resume: '자동 갱신 다시 시작',
      refreshNow: '지금 갱신',
    },
  },
} as const
