/**
 * Per-page wording, in both languages.
 *
 * `defineCopy` is the whole point: it infers the shape from `en` and requires
 * `ko` to match it exactly, so a page cannot gain an English string without
 * gaining its Korean counterpart. Seven pages had drifted to English-only
 * precisely because nothing stopped them.
 */
function defineCopy<T>(copy: { en: T; ko: T }) {
  return copy
}

const transactions = defineCopy({
  en: {
    eyebrow: 'Portfolio',
    title: 'Transactions',
    emphasis: 'Transactions',
    subtitle: 'Most recent ledger rows from the normalized transaction TSV.',
    card: 'Recent transactions',
    searchPlaceholder: 'Ticker, name, account, or broker',
    summary: (shown: string, total: string) => `${shown} of ${total} recent rows`,
    filters: { market: 'Market', broker: 'Broker', account: 'Account', type: 'Type', term: 'Term', status: 'Status' },
    columns: {
      market: 'Market',
      date: 'Date',
      broker: 'Broker',
      account: 'Account',
      type: 'Type',
      ticker: 'Ticker',
      name: 'Name',
      quantity: 'Qty',
      amount: 'Amount',
      baseAmount: 'Base Amount',
      source: 'Source',
      page: 'Page',
    },
  },
  ko: {
    eyebrow: '포트폴리오',
    title: '거래 내역',
    emphasis: '내역',
    subtitle: '정규화된 거래 TSV에서 읽은 최근 원장 행입니다.',
    card: '최근 거래',
    searchPlaceholder: '종목코드, 종목명, 계좌 또는 증권사',
    summary: (shown: string, total: string) => `최근 ${total}건 중 ${shown}건`,
    filters: { market: '시장', broker: '증권사', account: '계좌', type: '유형', term: '과세 구분', status: '상태' },
    columns: {
      market: '시장',
      date: '거래일',
      broker: '증권사',
      account: '계좌',
      type: '유형',
      ticker: '종목코드',
      name: '종목명',
      quantity: '수량',
      amount: '거래금액',
      baseAmount: '원화 환산',
      source: '원본',
      page: '페이지',
    },
  },
})

const lots = defineCopy({
  en: {
    eyebrow: 'Tax',
    title: 'Tax Lots',
    emphasis: 'Lots',
    subtitle: 'Open tax lots with search, account filters, sorting, and ticker drilldown.',
    card: 'Open tax lots',
    searchPlaceholder: 'ticker, name, account, source',
    filtered: 'Filtered',
    openQuantity: 'Open quantity',
    baseCost: 'Base cost',
    unknownTerm: 'Unknown',
    terms: { 'Long-term': 'Long-term', 'Short-term': 'Short-term' } as Record<string, string>,
    filters: { market: 'Market', broker: 'Broker', account: 'Account', type: 'Type', term: 'Term', status: 'Status' },
    columns: {
      market: 'Market',
      broker: 'Broker',
      account: 'Account',
      instrument: 'Instrument',
      acquired: 'Acquired',
      quantity: 'Qty',
      costBasis: 'Cost Basis',
      baseCost: 'Base Cost',
      days: 'Days',
      term: 'Term',
    },
  },
  ko: {
    eyebrow: '세금',
    title: '세금 계산 단위',
    emphasis: '단위',
    subtitle: '검색·계좌 필터·정렬·종목 드릴다운이 가능한 미결제 세금 단위입니다.',
    card: '미결제 세금 단위',
    searchPlaceholder: '종목코드, 종목명, 계좌, 원본',
    filtered: '필터 결과',
    openQuantity: '미결제 수량',
    baseCost: '원화 취득원가',
    unknownTerm: '미상',
    terms: { 'Long-term': '장기', 'Short-term': '단기' } as Record<string, string>,
    filters: { market: '시장', broker: '증권사', account: '계좌', type: '유형', term: '과세 구분', status: '상태' },
    columns: {
      market: '시장',
      broker: '증권사',
      account: '계좌',
      instrument: '종목',
      acquired: '취득일',
      quantity: '수량',
      costBasis: '취득원가',
      baseCost: '원화 취득원가',
      days: '보유일',
      term: '과세 구분',
    },
  },
})

const costBasis = defineCopy({
  en: {
    eyebrow: 'Records',
    title: 'Cost Basis',
    emphasis: 'Basis',
    subtitle: (rows: string, missing: string, estimated: string) =>
      `${rows} holdings with current value and total cost review. ${missing} missing cost, ${estimated} estimated.`,
    methodCard: 'Cost basis method',
    methodBody1:
      'Use this table as the read-only source for holdings that need a current shares, value, and Total Cost check. Match by Symbol, Name, Account/Broker, and Shares, then use the Total Cost value in the holding currency.',
    methodBody2:
      'Cost values come from the observatory holdings snapshot. Rows marked Estimated are usable for review but should be checked against statements; for crypto-style activity, reconcile source cost as purchases minus the cost removed by sales and rewards/disposals.',
    priceCard: 'Price basis',
    latestPriceDate: 'Latest price date',
    missingCostRows: 'Missing cost rows',
    estimatedRows: 'Estimated rows',
    card: 'Holdings cost basis',
    searchPlaceholder: 'symbol, name, account, broker',
    filtered: 'Filtered',
    totalValue: 'Total value',
    totalCost: 'Total cost',
    missingCost: 'Missing cost',
    estimated: 'Estimated',
    mixedCurrencies: 'Mixed currencies',
    status: {
      ready: 'Ready',
      missing_cost: 'Missing cost',
      estimated: 'Estimated',
      unpriced: 'Unpriced',
    },
    filters: { market: 'Market', broker: 'Broker', account: 'Account', type: 'Type', term: 'Term', status: 'Status' },
    columns: {
      symbol: 'Symbol',
      name: 'Name',
      broker: 'Broker',
      account: 'Account',
      shares: 'Shares',
      price: 'Price',
      value: 'Value',
      totalCost: 'Total Cost',
      gain: 'Gain',
      gainPct: 'Gain %',
      day: 'Day',
      dayPct: 'Day %',
      percentOfTotal: '% of Total',
      syncStatus: 'Sync Status',
      why: 'Why',
    },
  },
  ko: {
    eyebrow: '상세 기록',
    title: '취득원가',
    emphasis: '원가',
    subtitle: (rows: string, missing: string, estimated: string) =>
      `현재 평가금액과 총 취득원가를 검토할 ${rows}개 보유종목입니다. 원가 없음 ${missing}건, 추정 ${estimated}건.`,
    methodCard: '취득원가 기준',
    methodBody1:
      '현재 수량·평가금액·총 취득원가를 확인해야 하는 보유종목의 조회 전용 출처로 이 표를 쓰세요. 종목코드·종목명·계좌/증권사·수량으로 대조한 뒤, 보유 통화 기준의 총 취득원가 값을 사용합니다.',
    methodBody2:
      '취득원가는 관측소 보유 스냅샷에서 옵니다. 「추정」으로 표시된 행은 검토용으로는 쓸 수 있지만 명세서와 대조해야 하며, 가상자산성 활동은 매수액에서 매도·리워드/처분으로 빠져나간 원가를 뺀 값으로 원본 원가를 맞춥니다.',
    priceCard: '가격 기준',
    latestPriceDate: '최근 가격일',
    missingCostRows: '원가 없는 행',
    estimatedRows: '추정 행',
    card: '보유종목 취득원가',
    searchPlaceholder: '종목코드, 종목명, 계좌, 증권사',
    filtered: '필터 결과',
    totalValue: '총 평가금액',
    totalCost: '총 취득원가',
    missingCost: '원가 없음',
    estimated: '추정',
    mixedCurrencies: '통화 혼재',
    status: {
      ready: '확인됨',
      missing_cost: '원가 없음',
      estimated: '추정',
      unpriced: '가격 없음',
    },
    filters: { market: '시장', broker: '증권사', account: '계좌', type: '유형', term: '과세 구분', status: '상태' },
    columns: {
      symbol: '종목코드',
      name: '종목명',
      broker: '증권사',
      account: '계좌',
      shares: '수량',
      price: '가격',
      value: '평가금액',
      totalCost: '총 취득원가',
      gain: '평가손익',
      gainPct: '수익률',
      day: '전일 대비',
      dayPct: '전일 대비 %',
      percentOfTotal: '비중',
      syncStatus: '동기화 상태',
      why: '사유',
    },
  },
})

const dividends = defineCopy({
  en: {
    eyebrow: 'Portfolio',
    title: 'Dividends',
    emphasis: 'Dividends',
    subtitle: (total: string, rows: string) => `${total} across ${rows} dividend rows.`,
    openIncome: 'Open Income Review',
    trendCard: 'Annual dividend income',
    yearsCard: 'Yearly totals',
    axisLabel: 'KRW thousand / USD',
    note: 'KR bars are KRW thousands; US bars are native USD.',
    rows: (count: string) => `${count} rows`,
  },
  ko: {
    eyebrow: '상세 기록',
    title: '배당 내역',
    emphasis: '배당',
    subtitle: (total: string, rows: string) => `배당 ${rows}건, 합계 ${total}.`,
    openIncome: '수익 검토 열기',
    trendCard: '연간 배당 수익',
    yearsCard: '연도별 합계',
    axisLabel: '천 원 / 달러',
    note: '한국 막대는 천 원, 미국 막대는 달러 원화입니다.',
    rows: (count: string) => `${count}건`,
  },
})

const cryptoPremium = defineCopy({
  en: {
    eyebrow: 'Crypto',
    title: 'Korea Premium',
    emphasis: 'Premium',
    subtitleWithData: (asOf: string) => `Domestic versus global pricing for the coins actually held, as of ${asOf}.`,
    subtitleNoData: 'No crypto price snapshot yet — run pnpm refresh.',
    weightedPremium: 'Weighted Premium',
    weightedPremiumInfo:
      'KRW-venue crypto premium weighted by the value of held KRW-venue positions. Use this as the headline premium exposure signal.',
    premiumHeadline: 'Premium headline',
    weightedHint: 'Across KRW-venue holdings, weighted by value',
    premiumBearingValue: 'Premium-Bearing Value',
    premiumBearingHint: 'KRW-venue positions marked at their own book',
    valueFromPremium: 'Value From Premium',
    valueFromPremiumHint: 'What parity would remove',
    coinsCompared: 'Coins Compared',
    readOrder: 'Premium Read Order',
    readOrderInfo: 'Start with weighted exposure, then check premium-bearing value and coin-level rows.',
    threshold: 'Threshold',
    thresholdHint: 'Notable premium threshold',
    coverage: 'Coverage',
    coverageHint: 'Available premium history',
    byCoin: 'Current premium by coin',
    whatThisMeasures: 'What this measures',
    history: 'Premium history',
    nearParity: 'Near parity',
    noPairs: 'No coin is quoted on both a KRW and a USD book — nothing to compare.',
    noHistory: 'No overlapping history — run pnpm refresh.',
    axisLabel: 'Premium %',
    columns: {
      coin: 'Coin',
      krwVenue: 'Bithumb (KRW)',
      globalVenue: 'Global (USD)',
      impliedKrw: 'Implied KRW',
      premium: 'Premium',
      held: 'Held',
      valueFromPremium: 'Value From Premium',
    },
  },
  ko: {
    eyebrow: '가상자산',
    title: '코리아 프리미엄',
    emphasis: '프리미엄',
    subtitleWithData: (asOf: string) => `실제 보유한 코인의 국내·해외 가격 비교입니다. 기준 ${asOf}.`,
    subtitleNoData: '아직 가상자산 시세 스냅샷이 없습니다 — pnpm refresh를 실행하세요.',
    weightedPremium: '가중 프리미엄',
    weightedPremiumInfo:
      '보유 중인 원화 거래소 포지션의 평가금액으로 가중한 프리미엄입니다. 프리미엄 노출을 보는 대표 지표로 쓰세요.',
    premiumHeadline: '프리미엄 대표값',
    weightedHint: '원화 거래소 보유분 전체를 평가금액으로 가중',
    premiumBearingValue: '프리미엄 적용 금액',
    premiumBearingHint: '각 거래소 자체 호가로 평가한 원화 거래소 포지션',
    valueFromPremium: '프리미엄 기여분',
    valueFromPremiumHint: '가격이 같아지면 사라지는 금액',
    coinsCompared: '비교된 코인',
    readOrder: '프리미엄 읽는 순서',
    readOrderInfo: '가중 노출을 먼저 보고, 프리미엄 적용 금액과 코인별 행을 확인하세요.',
    threshold: '기준선',
    thresholdHint: '주목할 프리미엄 기준',
    coverage: '이력 범위',
    coverageHint: '확보된 프리미엄 이력',
    byCoin: '코인별 현재 프리미엄',
    whatThisMeasures: '이 지표의 의미',
    history: '프리미엄 추이',
    nearParity: '가격 차 거의 없음',
    noPairs: '원화·달러 양쪽에 호가가 있는 코인이 없어 비교할 대상이 없습니다.',
    noHistory: '겹치는 이력이 없습니다 — pnpm refresh를 실행하세요.',
    axisLabel: '프리미엄 %',
    columns: {
      coin: '코인',
      krwVenue: '빗썸 (원화)',
      globalVenue: '해외 (달러)',
      impliedKrw: '환산 원화',
      premium: '프리미엄',
      held: '보유량',
      valueFromPremium: '프리미엄 기여분',
    },
  },
})


const positionDetail = defineCopy({
  en: {
    eyebrow: (market: string) => `${market} holding`,
    subtitle: (accounts: string, lots: string, transactions: string) =>
      `${accounts} accounts · ${lots} open tax lots · ${transactions} transactions`,
    backToHoldings: 'Back to holdings',
    freshness: 'Valuation Data Freshness',
    firstChecks: 'First Checks',
    firstChecksInfo: "Summarizes whether this position's quantity, cost basis, and evidence agree.",
    reconciliationStatus: 'Reconciliation status',
    evidenceLinks: 'Evidence links',
    activityCoverage: 'Activity coverage',
    marketValue: 'Market Value',
    positionHeadline: 'Position headline',
    marketValueInfo:
      "Current position value in the position's native currency. Use this as the position-level headline before checking cost basis or gain/loss.",
    costBasis: 'Cost Basis',
    unrealized: 'Unrealized G/L',
    baseUnrealized: 'Base Unrealized G/L',
    coverage: 'Position Coverage',
    coverageInfo: 'Quantity, income, and row coverage for this single position.',
    quantity: 'Quantity',
    dividends: 'Dividends',
    reconciliation: 'Reconciliation',
    openQuantity: 'Open quantity',
    baseCost: 'Base cost',
    holdings: 'Holdings',
    taxLots: 'Tax lots',
    difference: 'Difference',
    matched: 'Matched',
    needsReview: 'Needs review',
    holdingMix: 'Holding-Period Mix',
    holdingMixInfo: 'Splits quantity into long-term and short-term buckets for tax review.',
    longQuantity: 'Long-term quantity',
    shortQuantity: 'Short-term quantity',
    longShortLots: 'Long / short tax-lot count',
    transactionMix: 'Transaction mix',
    accountHoldings: 'Account holdings',
    accountLotProfile: 'Account lot profile',
    activityTimeline: 'Activity timeline',
    evidenceSummary: 'Source evidence summary',
    lineage: 'Technical lineage',
    taxPreview: 'Tax realization preview',
    openTaxLots: 'Open tax lots',
    transactions: 'Transactions',
    noTransactions: 'No ticker-level transactions',
    noActivity: 'No dated activity for this ticker',
    noTaxPreview: 'No tax-lot sale preview available',
    noOpenLots: 'No open tax lots for this ticker',
    noDividends: 'No dividend rows for this ticker',
    noValue: 'No value',
    openPlanner: 'Open planner',
    eventKinds: { Dividend: 'Dividend', 'Tax lot': 'Tax lot', Buy: 'Buy', Sell: 'Sell' } as Record<string, string>,
    columns: {
      broker: 'Broker',
      account: 'Account',
      quantity: 'Qty',
      cost: 'Cost',
      market: 'Market',
      gainLoss: 'G/L',
      lots: 'Lots',
      long: 'LT',
      short: 'ST',
      lotCost: 'Lot Cost',
      status: 'Status',
      file: 'File / source',
      usage: 'Usage',
      rows: 'Rows',
      modified: 'Modified',
      source: 'Source',
      sha: 'SHA',
      acquired: 'Acquired',
      term: 'Term',
      proceeds: 'Proceeds',
      baseGainLoss: 'Base G/L',
      estimatedTax: 'Est. Tax',
      baseCost: 'Base Cost',
      date: 'Date',
      type: 'Type',
      amount: 'Amount',
      unit: 'Unit',
      page: 'Page',
      tax: 'Tax',
      baseAmount: 'Base Amount',
    },
  },
  ko: {
    eyebrow: (market: string) => `${market} 보유`,
    subtitle: (accounts: string, lots: string, transactions: string) =>
      `계좌 ${accounts}개 · 미결제 세금 단위 ${lots}개 · 거래 ${transactions}건`,
    backToHoldings: '보유종목으로 돌아가기',
    freshness: '평가 데이터 신선도',
    firstChecks: '먼저 확인할 것',
    firstChecksInfo: '이 종목의 수량·취득원가·증빙이 서로 맞는지 요약합니다.',
    reconciliationStatus: '정합성 상태',
    evidenceLinks: '증빙 연결',
    activityCoverage: '활동 반영 범위',
    marketValue: '평가금액',
    positionHeadline: '종목 대표값',
    marketValueInfo: '해당 종목의 거래 통화 기준 현재 평가금액입니다. 취득원가나 손익을 보기 전에 이 값을 종목 대표값으로 삼으세요.',
    costBasis: '취득원가',
    unrealized: '평가손익',
    baseUnrealized: '원화 평가손익',
    coverage: '종목 반영 범위',
    coverageInfo: '이 종목 하나에 대한 수량·수익·행 반영 범위입니다.',
    quantity: '수량',
    dividends: '배당',
    reconciliation: '정합성 확인',
    openQuantity: '미결제 수량',
    baseCost: '원화 취득원가',
    holdings: '보유종목',
    taxLots: '세금 단위',
    difference: '차이',
    matched: '일치',
    needsReview: '확인 필요',
    holdingMix: '보유기간 구성',
    holdingMixInfo: '세금 검토를 위해 수량을 장기·단기로 나눕니다.',
    longQuantity: '장기 수량',
    shortQuantity: '단기 수량',
    longShortLots: '장기 / 단기 세금 단위 수',
    transactionMix: '거래 구성',
    accountHoldings: '계좌별 보유',
    accountLotProfile: '계좌별 단위 구성',
    activityTimeline: '활동 이력',
    evidenceSummary: '원본 증빙 요약',
    lineage: '기술 계보',
    taxPreview: '세금 실현 미리보기',
    openTaxLots: '미결제 세금 단위',
    transactions: '거래 내역',
    noTransactions: '이 종목의 거래 행이 없습니다',
    noActivity: '이 종목의 날짜별 활동이 없습니다',
    noTaxPreview: '세금 단위 매도 미리보기를 만들 수 없습니다',
    noOpenLots: '이 종목의 미결제 세금 단위가 없습니다',
    noDividends: '이 종목의 배당 행이 없습니다',
    noValue: '값 없음',
    openPlanner: '세금 계획 열기',
    eventKinds: { Dividend: '배당', 'Tax lot': '세금 단위', Buy: '매수', Sell: '매도' } as Record<string, string>,
    columns: {
      broker: '증권사',
      account: '계좌',
      quantity: '수량',
      cost: '취득원가',
      market: '평가금액',
      gainLoss: '손익',
      lots: '단위',
      long: '장기',
      short: '단기',
      lotCost: '단위 원가',
      status: '상태',
      file: '파일 / 원본',
      usage: '용도',
      rows: '행 수',
      modified: '수정일',
      source: '원본',
      sha: 'SHA',
      acquired: '취득일',
      term: '과세 구분',
      proceeds: '매도금액',
      baseGainLoss: '원화 손익',
      estimatedTax: '예상 세금',
      baseCost: '원화 취득원가',
      date: '거래일',
      type: '유형',
      amount: '금액',
      unit: '단가',
      page: '페이지',
      tax: '원천징수',
      baseAmount: '원화 환산',
    },
  },
})


const dailyBriefing = defineCopy({
  en: {
    eyebrow: 'Portfolio',
    title: 'Daily Briefing',
    emphasis: 'Briefing',
    subtitle: 'Archived daily briefings, published each trading morning.',
    briefingDate: 'Briefing date',
    view: 'View',
    latest: 'Latest',
    latestSuffix: 'latest',
    costShort: 'Cost',
    archived: 'Archived',
    sessionReturn: 'Session Return',
    sessionPlInfo:
      'Price movement on the shares already held, measured against the previous archived snapshot. Shares bought or sold since then are excluded, so this is the market move and not the effect of trading.',
    sessionPl: 'Session P/L',
    dailyMove: 'Daily move',
    standingSnapshot: 'Standing snapshot',
    portfolioValue: 'Portfolio Value',
    unrealized: 'Unrealized P/L',
    readOrder: 'Briefing Read Order',
    readOrderInfo: 'Use the daily move first, then standing value and cumulative unrealized performance.',
    market: 'Market',
    costBasis: 'Cost Basis',
    standingVsCost: 'Standing versus purchase cost',
    cumulativeNote: 'cumulative since purchase — moves slowly',
    gainers: 'Session gainers',
    decliners: 'Session decliners',
    bestVsCost: 'Best vs cost',
    worstVsCost: 'Worst vs cost',
    largestPositions: 'Largest positions',
    marketContext: 'Market context',
    suggestedActions: 'Suggested actions to consider',
    documentBuilt: 'Document built',
    markets: 'Markets',
    archive: 'Archive',
    actNow: 'Act now',
    thisWeek: 'This week',
    noMovers: 'No movers in this briefing',
    noSnapshot: 'No holdings snapshot was retained for this briefing.',
    noPrices: 'The holdings sheet carried no usable prices on both sides of the comparison.',
    noNote: 'No note in this briefing.',
    unreadable: 'That briefing could not be read.',
    noArchive: 'No briefings archived yet.',
    noPriorSnapshot: 'No prior snapshot was available to compare against.',
    sessionZero: 'Session figures are therefore zero; the standing-versus-cost view below is unaffected.',
    columns: {
      ticker: 'Ticker',
      marketValue: 'Market Value',
      costBasis: 'Cost Basis',
      returnPct: 'Return',
      accounts: 'Accounts',
    },
  },
  ko: {
    eyebrow: '포트폴리오',
    title: '오늘의 브리핑',
    emphasis: '브리핑',
    subtitle: '거래일 아침마다 발행되어 보관된 일일 브리핑입니다.',
    briefingDate: '브리핑 날짜',
    view: '보기',
    latest: '최신',
    latestSuffix: '최신',
    costShort: '원가',
    archived: '보관됨',
    sessionReturn: '당일 수익률',
    sessionPlInfo: '이미 보유 중이던 주식의 가격 변동을, 직전에 보관된 스냅샷과 비교해 측정한 값입니다. 그 이후의 매수·매도는 제외하므로 매매의 효과가 아니라 시장의 움직임입니다.',
    sessionPl: '당일 손익',
    dailyMove: '당일 변동',
    standingSnapshot: '기준 스냅샷',
    portfolioValue: '포트폴리오 평가금액',
    unrealized: '평가손익',
    readOrder: '브리핑 읽는 순서',
    readOrderInfo: '당일 변동을 먼저 보고, 그다음 기준 평가금액과 누적 평가손익을 확인하세요.',
    market: '시장',
    costBasis: '취득원가',
    standingVsCost: '취득원가 대비 현재',
    cumulativeNote: '매수 이후 누적 — 천천히 움직입니다',
    gainers: '당일 상승',
    decliners: '당일 하락',
    bestVsCost: '원가 대비 최고',
    worstVsCost: '원가 대비 최저',
    largestPositions: '최대 보유',
    marketContext: '시장 상황',
    suggestedActions: '검토할 만한 조치',
    documentBuilt: '문서 생성',
    markets: '시장',
    archive: '보관함',
    actNow: '즉시',
    thisWeek: '이번 주',
    noMovers: '이 브리핑에는 변동 종목이 없습니다',
    noSnapshot: '이 브리핑에는 보유 스냅샷이 보관되지 않았습니다.',
    noPrices: '보유 시트에 비교 양쪽 모두 쓸 수 있는 가격이 없었습니다.',
    noNote: '이 브리핑에는 메모가 없습니다.',
    unreadable: '해당 브리핑을 읽을 수 없었습니다.',
    noArchive: '아직 보관된 브리핑이 없습니다.',
    noPriorSnapshot: '비교할 이전 스냅샷이 없었습니다.',
    sessionZero: '따라서 당일 수치는 0입니다. 아래의 원가 대비 현황은 영향을 받지 않습니다.',
    columns: {
      ticker: '종목코드',
      marketValue: '평가금액',
      costBasis: '취득원가',
      returnPct: '수익률',
      accounts: '계좌',
    },
  },
})

export const PAGE_COPY = {
  dailyBriefing,
  positionDetail,
  transactions,
  lots,
  costBasis,
  dividends,
  cryptoPremium,
}
