/**
 * Per-page wording, in both languages.
 *
 * `defineCopy` is the whole point: it infers the shape from `en` and requires
 * `ko` to match it exactly, so a page cannot gain an English string without
 * gaining its Korean counterpart. Seven pages had drifted to English-only
 * precisely because nothing stopped them.
 */
function defineCopy<T>(copy: { en: T; ko: T }) {
  return copy
}

const transactions = defineCopy({
  en: {
    eyebrow: 'Portfolio',
    title: 'Transactions',
    emphasis: 'Transactions',
    subtitle: 'Most recent ledger rows from the normalized transaction TSV.',
    card: 'Recent transactions',
    searchPlaceholder: 'Ticker, name, account, or broker',
    summary: (shown: string, total: string) => `${shown} of ${total} recent rows`,
    filters: { market: 'Market', broker: 'Broker', account: 'Account', type: 'Type', term: 'Term', status: 'Status' },
    columns: {
      market: 'Market',
      date: 'Date',
      broker: 'Broker',
      account: 'Account',
      type: 'Type',
      ticker: 'Ticker',
      name: 'Name',
      quantity: 'Qty',
      amount: 'Amount',
      baseAmount: 'Base Amount',
      source: 'Source',
      page: 'Page',
    },
  },
  ko: {
    eyebrow: '포트폴리오',
    title: '거래 내역',
    emphasis: '내역',
    subtitle: '정규화된 거래 TSV에서 읽은 최근 원장 행입니다.',
    card: '최근 거래',
    searchPlaceholder: '종목코드, 종목명, 계좌 또는 증권사',
    summary: (shown: string, total: string) => `최근 ${total}건 중 ${shown}건`,
    filters: { market: '시장', broker: '증권사', account: '계좌', type: '유형', term: '과세 구분', status: '상태' },
    columns: {
      market: '시장',
      date: '거래일',
      broker: '증권사',
      account: '계좌',
      type: '유형',
      ticker: '종목코드',
      name: '종목명',
      quantity: '수량',
      amount: '거래금액',
      baseAmount: '원화 환산',
      source: '원본',
      page: '페이지',
    },
  },
})

const lots = defineCopy({
  en: {
    eyebrow: 'Tax',
    title: 'Tax Lots',
    emphasis: 'Lots',
    subtitle: 'Open tax lots with search, account filters, sorting, and ticker drilldown.',
    card: 'Open tax lots',
    searchPlaceholder: 'ticker, name, account, source',
    filtered: 'Filtered',
    openQuantity: 'Open quantity',
    baseCost: 'Base cost',
    unknownTerm: 'Unknown',
    terms: { 'Long-term': 'Long-term', 'Short-term': 'Short-term' } as Record<string, string>,
    filters: { market: 'Market', broker: 'Broker', account: 'Account', type: 'Type', term: 'Term', status: 'Status' },
    columns: {
      market: 'Market',
      broker: 'Broker',
      account: 'Account',
      instrument: 'Instrument',
      acquired: 'Acquired',
      quantity: 'Qty',
      costBasis: 'Cost Basis',
      baseCost: 'Base Cost',
      days: 'Days',
      term: 'Term',
    },
  },
  ko: {
    eyebrow: '세금',
    title: '세금 계산 단위',
    emphasis: '단위',
    subtitle: '검색·계좌 필터·정렬·종목 드릴다운이 가능한 미결제 세금 단위입니다.',
    card: '미결제 세금 단위',
    searchPlaceholder: '종목코드, 종목명, 계좌, 원본',
    filtered: '필터 결과',
    openQuantity: '미결제 수량',
    baseCost: '원화 취득원가',
    unknownTerm: '미상',
    terms: { 'Long-term': '장기', 'Short-term': '단기' } as Record<string, string>,
    filters: { market: '시장', broker: '증권사', account: '계좌', type: '유형', term: '과세 구분', status: '상태' },
    columns: {
      market: '시장',
      broker: '증권사',
      account: '계좌',
      instrument: '종목',
      acquired: '취득일',
      quantity: '수량',
      costBasis: '취득원가',
      baseCost: '원화 취득원가',
      days: '보유일',
      term: '과세 구분',
    },
  },
})

const costBasis = defineCopy({
  en: {
    eyebrow: 'Records',
    title: 'Cost Basis',
    emphasis: 'Basis',
    subtitle: (rows: string, missing: string, estimated: string) =>
      `${rows} holdings with current value and total cost review. ${missing} missing cost, ${estimated} estimated.`,
    methodCard: 'Cost basis method',
    methodBody1:
      'Use this table as the read-only source for holdings that need a current shares, value, and Total Cost check. Match by Symbol, Name, Account/Broker, and Shares, then use the Total Cost value in the holding currency.',
    methodBody2:
      'Cost values come from the observatory holdings snapshot. Rows marked Estimated are usable for review but should be checked against statements; for crypto-style activity, reconcile source cost as purchases minus the cost removed by sales and rewards/disposals.',
    priceCard: 'Price basis',
    latestPriceDate: 'Latest price date',
    missingCostRows: 'Missing cost rows',
    estimatedRows: 'Estimated rows',
    card: 'Holdings cost basis',
    searchPlaceholder: 'symbol, name, account, broker',
    filtered: 'Filtered',
    totalValue: 'Total value',
    totalCost: 'Total cost',
    missingCost: 'Missing cost',
    estimated: 'Estimated',
    mixedCurrencies: 'Mixed currencies',
    status: {
      ready: 'Ready',
      missing_cost: 'Missing cost',
      estimated: 'Estimated',
      unpriced: 'Unpriced',
    },
    filters: { market: 'Market', broker: 'Broker', account: 'Account', type: 'Type', term: 'Term', status: 'Status' },
    columns: {
      symbol: 'Symbol',
      name: 'Name',
      broker: 'Broker',
      account: 'Account',
      shares: 'Shares',
      price: 'Price',
      value: 'Value',
      totalCost: 'Total Cost',
      gain: 'Gain',
      gainPct: 'Gain %',
      day: 'Day',
      dayPct: 'Day %',
      percentOfTotal: '% of Total',
      syncStatus: 'Sync Status',
      why: 'Why',
    },
  },
  ko: {
    eyebrow: '상세 기록',
    title: '취득원가',
    emphasis: '원가',
    subtitle: (rows: string, missing: string, estimated: string) =>
      `현재 평가금액과 총 취득원가를 검토할 ${rows}개 보유종목입니다. 원가 없음 ${missing}건, 추정 ${estimated}건.`,
    methodCard: '취득원가 기준',
    methodBody1:
      '현재 수량·평가금액·총 취득원가를 확인해야 하는 보유종목의 조회 전용 출처로 이 표를 쓰세요. 종목코드·종목명·계좌/증권사·수량으로 대조한 뒤, 보유 통화 기준의 총 취득원가 값을 사용합니다.',
    methodBody2:
      '취득원가는 관측소 보유 스냅샷에서 옵니다. 「추정」으로 표시된 행은 검토용으로는 쓸 수 있지만 명세서와 대조해야 하며, 가상자산성 활동은 매수액에서 매도·리워드/처분으로 빠져나간 원가를 뺀 값으로 원본 원가를 맞춥니다.',
    priceCard: '가격 기준',
    latestPriceDate: '최근 가격일',
    missingCostRows: '원가 없는 행',
    estimatedRows: '추정 행',
    card: '보유종목 취득원가',
    searchPlaceholder: '종목코드, 종목명, 계좌, 증권사',
    filtered: '필터 결과',
    totalValue: '총 평가금액',
    totalCost: '총 취득원가',
    missingCost: '원가 없음',
    estimated: '추정',
    mixedCurrencies: '통화 혼재',
    status: {
      ready: '확인됨',
      missing_cost: '원가 없음',
      estimated: '추정',
      unpriced: '가격 없음',
    },
    filters: { market: '시장', broker: '증권사', account: '계좌', type: '유형', term: '과세 구분', status: '상태' },
    columns: {
      symbol: '종목코드',
      name: '종목명',
      broker: '증권사',
      account: '계좌',
      shares: '수량',
      price: '가격',
      value: '평가금액',
      totalCost: '총 취득원가',
      gain: '평가손익',
      gainPct: '수익률',
      day: '전일 대비',
      dayPct: '전일 대비 %',
      percentOfTotal: '비중',
      syncStatus: '동기화 상태',
      why: '사유',
    },
  },
})

const dividends = defineCopy({
  en: {
    eyebrow: 'Portfolio',
    title: 'Dividends',
    emphasis: 'Dividends',
    subtitle: (total: string, rows: string) => `${total} across ${rows} dividend rows.`,
    openIncome: 'Open Income Review',
    trendCard: 'Annual dividend income',
    yearsCard: 'Yearly totals',
    axisLabel: 'KRW thousand / USD',
    note: 'KR bars are KRW thousands; US bars are native USD.',
    rows: (count: string) => `${count} rows`,
  },
  ko: {
    eyebrow: '상세 기록',
    title: '배당 내역',
    emphasis: '배당',
    subtitle: (total: string, rows: string) => `배당 ${rows}건, 합계 ${total}.`,
    openIncome: '수익 검토 열기',
    trendCard: '연간 배당 수익',
    yearsCard: '연도별 합계',
    axisLabel: '천 원 / 달러',
    note: '한국 막대는 천 원, 미국 막대는 달러 원화입니다.',
    rows: (count: string) => `${count}건`,
  },
})

const cryptoPremium = defineCopy({
  en: {
    eyebrow: 'Crypto',
    title: 'Korea Premium',
    emphasis: 'Premium',
    subtitleWithData: (asOf: string) => `Domestic versus global pricing for the coins actually held, as of ${asOf}.`,
    subtitleNoData: 'No crypto price snapshot yet — run pnpm refresh.',
    weightedPremium: 'Weighted Premium',
    weightedPremiumInfo:
      'KRW-venue crypto premium weighted by the value of held KRW-venue positions. Use this as the headline premium exposure signal.',
    premiumHeadline: 'Premium headline',
    weightedHint: 'Across KRW-venue holdings, weighted by value',
    premiumBearingValue: 'Premium-Bearing Value',
    premiumBearingHint: 'KRW-venue positions marked at their own book',
    valueFromPremium: 'Value From Premium',
    valueFromPremiumHint: 'What parity would remove',
    coinsCompared: 'Coins Compared',
    readOrder: 'Premium Read Order',
    readOrderInfo: 'Start with weighted exposure, then check premium-bearing value and coin-level rows.',
    threshold: 'Threshold',
    thresholdHint: 'Notable premium threshold',
    coverage: 'Coverage',
    coverageHint: 'Available premium history',
    byCoin: 'Current premium by coin',
    whatThisMeasures: 'What this measures',
    history: 'Premium history',
    nearParity: 'Near parity',
    noPairs: 'No coin is quoted on both a KRW and a USD book — nothing to compare.',
    noHistory: 'No overlapping history — run pnpm refresh.',
    axisLabel: 'Premium %',
    columns: {
      coin: 'Coin',
      krwVenue: 'Bithumb (KRW)',
      globalVenue: 'Global (USD)',
      impliedKrw: 'Implied KRW',
      premium: 'Premium',
      held: 'Held',
      valueFromPremium: 'Value From Premium',
    },
  },
  ko: {
    eyebrow: '가상자산',
    title: '코리아 프리미엄',
    emphasis: '프리미엄',
    subtitleWithData: (asOf: string) => `실제 보유한 코인의 국내·해외 가격 비교입니다. 기준 ${asOf}.`,
    subtitleNoData: '아직 가상자산 시세 스냅샷이 없습니다 — pnpm refresh를 실행하세요.',
    weightedPremium: '가중 프리미엄',
    weightedPremiumInfo:
      '보유 중인 원화 거래소 포지션의 평가금액으로 가중한 프리미엄입니다. 프리미엄 노출을 보는 대표 지표로 쓰세요.',
    premiumHeadline: '프리미엄 대표값',
    weightedHint: '원화 거래소 보유분 전체를 평가금액으로 가중',
    premiumBearingValue: '프리미엄 적용 금액',
    premiumBearingHint: '각 거래소 자체 호가로 평가한 원화 거래소 포지션',
    valueFromPremium: '프리미엄 기여분',
    valueFromPremiumHint: '가격이 같아지면 사라지는 금액',
    coinsCompared: '비교된 코인',
    readOrder: '프리미엄 읽는 순서',
    readOrderInfo: '가중 노출을 먼저 보고, 프리미엄 적용 금액과 코인별 행을 확인하세요.',
    threshold: '기준선',
    thresholdHint: '주목할 프리미엄 기준',
    coverage: '이력 범위',
    coverageHint: '확보된 프리미엄 이력',
    byCoin: '코인별 현재 프리미엄',
    whatThisMeasures: '이 지표의 의미',
    history: '프리미엄 추이',
    nearParity: '가격 차 거의 없음',
    noPairs: '원화·달러 양쪽에 호가가 있는 코인이 없어 비교할 대상이 없습니다.',
    noHistory: '겹치는 이력이 없습니다 — pnpm refresh를 실행하세요.',
    axisLabel: '프리미엄 %',
    columns: {
      coin: '코인',
      krwVenue: '빗썸 (원화)',
      globalVenue: '해외 (달러)',
      impliedKrw: '환산 원화',
      premium: '프리미엄',
      held: '보유량',
      valueFromPremium: '프리미엄 기여분',
    },
  },
})

export const PAGE_COPY = {
  transactions,
  lots,
  costBasis,
  dividends,
  cryptoPremium,
}
