import { defineCopy } from '@/lib/ui-copy/define'

export const accounts = defineCopy({
  en: {
    title: 'Accounts & Coverage',
    emphasis: 'Coverage',
    subtitle: (ingestedAt: string) =>
      `Every account in the database and the date range each kind of record covers. Last ingest: ${ingestedAt}.`,
    accounts: 'Accounts',
    accountsHint: (parts: string[]) => parts.join(' · '),
    marketCount: (market: string, count: string) => `${market} ${count}`,
    firstDate: 'Earliest record',
    firstDateHint: 'Oldest date in any table, any account',
    lastDate: 'Latest record',
    lastDateHint: 'Newest date in any table, any account',
    tableTitle: 'Account coverage',
    tableInfo:
      'First and last date per table. Tax lots run from the oldest open acquisition to the snapshot that listed them. A holdings date is when positions were last read, not how far statements reach.',
    nextDownloads: 'Next downloads',
    columns: {
      account: 'Account',
      timeline: 'Timeline',
      transactions: 'Transactions',
      dividends: 'Dividends',
      holdings: 'Holdings as of',
      lots: 'Tax lots',
      realized: 'Realized',
      balances: 'Balances',
    },
    legend: { transactions: 'Transactions', dividends: 'Dividends', holdings: 'Holdings snapshot' },
    timelineLabel: (name: string, start: string, end: string) => `${name}: records from ${start} to ${end}`,
    alsoStoredAs: (names: string) => `also stored as ${names}`,
    rangeEnd: (end: string) => `– ${end}`,
    since: (start: string) => `since ${start}`,
    rows: (count: number, formatted: string) => `${formatted} ${count === 1 ? 'row' : 'rows'}`,
    none: '—',
    empty: 'No accounts in the database yet.',
  },
  ko: {
    title: '계좌 · 데이터 범위',
    emphasis: '데이터 범위',
    subtitle: (ingestedAt: string) => `DB에 들어 있는 모든 계좌와, 자료 종류별로 어느 날짜부터 어느 날짜까지 있는지 보여줍니다. 마지막 ingest: ${ingestedAt}.`,
    accounts: '계좌',
    accountsHint: (parts: string[]) => parts.join(' · '),
    marketCount: (market: string, count: string) => `${market} ${count}개`,
    firstDate: '가장 오래된 자료',
    firstDateHint: '모든 계좌·모든 자료 중 가장 이른 날짜',
    lastDate: '가장 최근 자료',
    lastDateHint: '모든 계좌·모든 자료 중 가장 늦은 날짜',
    tableTitle: '계좌별 데이터 범위',
    tableInfo:
      '자료별 첫 날짜와 마지막 날짜입니다. Tax lot은 남아 있는 lot 중 가장 오래된 취득일부터 그 lot을 읽은 시점까지입니다. 보유 기준일은 보유내역을 마지막으로 읽은 날이며, 거래내역서가 그 날짜까지 있다는 뜻은 아닙니다.',
    nextDownloads: '다음 다운로드',
    columns: {
      account: '계좌',
      timeline: '기간',
      transactions: '거래내역',
      dividends: '배당·분배',
      holdings: '보유 기준일',
      lots: 'Tax lot',
      realized: '실현손익',
      balances: '예금 잔고',
    },
    legend: { transactions: '거래내역', dividends: '배당·분배', holdings: '보유 스냅샷' },
    timelineLabel: (name: string, start: string, end: string) => `${name}: ${start}부터 ${end}까지의 자료`,
    alsoStoredAs: (names: string) => `다른 이름: ${names}`,
    rangeEnd: (end: string) => `~ ${end}`,
    since: (start: string) => `${start}부터`,
    rows: (_count: number, formatted: string) => `${formatted}건`,
    none: '—',
    empty: 'DB에 계좌가 아직 없습니다.',
  },
})
