import { defineCopy } from '@/lib/ui-copy/define'

export const costBasis = defineCopy({
  en: {
    eyebrow: 'Records',
    title: 'Cost Basis',
    emphasis: 'Basis',
    subtitle: (rows: string, missing: string, estimated: string) =>
      `${rows} holdings with current value and total cost review. ${missing} missing cost, ${estimated} estimated.`,
    methodCard: 'Cost basis method',
    methodBody1:
      'Use this table as the read-only source for holdings that need a current shares, value, and Total Cost check. Match by Symbol, Name, Account/Broker, and Shares, then use the Total Cost value in the holding currency.',
    methodBody2:
      'Cost values come from the observatory holdings snapshot. Rows marked Estimated are usable for review but should be checked against statements; for crypto-style activity, reconcile source cost as purchases minus the cost removed by sales and rewards/disposals.',
    priceCard: 'Price basis',
    latestPriceDate: 'Latest price date',
    missingCostRows: 'Missing cost rows',
    estimatedRows: 'Estimated rows',
    card: 'Holdings cost basis',
    searchPlaceholder: 'symbol, name, account, broker',
    filtered: 'Filtered',
    totalValue: 'Total value',
    totalCost: 'Total cost',
    missingCost: 'Missing cost',
    estimated: 'Estimated',
    mixedCurrencies: 'Mixed currencies',
    status: {
      ready: 'Ready',
      missing_cost: 'Missing cost',
      estimated: 'Estimated',
      unpriced: 'Unpriced',
    },
    filters: { market: 'Market', broker: 'Broker', account: 'Account', type: 'Type', term: 'Term', status: 'Status' },
    columns: {
      symbol: 'Symbol',
      name: 'Name',
      broker: 'Broker',
      account: 'Account',
      shares: 'Shares',
      price: 'Price',
      value: 'Value',
      totalCost: 'Total Cost',
      gain: 'Gain',
      gainPct: 'Gain %',
      day: 'Day',
      dayPct: 'Day %',
      percentOfTotal: '% of Total',
      syncStatus: 'Sync Status',
      why: 'Why',
    },
  },
  ko: {
    eyebrow: '상세 기록',
    title: '취득원가',
    emphasis: '원가',
    subtitle: (rows: string, missing: string, estimated: string) =>
      `현재 평가금액과 총 취득원가를 검토할 ${rows}개 보유종목입니다. 원가 없음 ${missing}건, 추정 ${estimated}건.`,
    methodCard: '취득원가 기준',
    methodBody1:
      '현재 수량·평가금액·총 취득원가를 확인해야 하는 보유종목의 조회 전용 출처로 이 표를 쓰세요. 종목코드·종목명·계좌/증권사·수량으로 대조한 뒤, 보유 통화 기준의 총 취득원가 값을 사용합니다.',
    methodBody2:
      '취득원가는 관측소 보유 스냅샷에서 옵니다. 「추정」으로 표시된 행은 검토용으로는 쓸 수 있지만 명세서와 대조해야 하며, 가상자산성 활동은 매수액에서 매도·리워드/처분으로 빠져나간 원가를 뺀 값으로 원본 원가를 맞춥니다.',
    priceCard: '가격 기준',
    latestPriceDate: '최근 가격일',
    missingCostRows: '원가 없는 행',
    estimatedRows: '추정 행',
    card: '보유종목 취득원가',
    searchPlaceholder: '종목코드, 종목명, 계좌, 증권사',
    filtered: '필터 결과',
    totalValue: '총 평가금액',
    totalCost: '총 취득원가',
    missingCost: '원가 없음',
    estimated: '추정',
    mixedCurrencies: '통화 혼재',
    status: {
      ready: '확인됨',
      missing_cost: '원가 없음',
      estimated: '추정',
      unpriced: '가격 없음',
    },
    filters: { market: '시장', broker: '증권사', account: '계좌', type: '유형', term: '과세 구분', status: '상태' },
    columns: {
      symbol: '종목코드',
      name: '종목명',
      broker: '증권사',
      account: '계좌',
      shares: '수량',
      price: '가격',
      value: '평가금액',
      totalCost: '총 취득원가',
      gain: '평가손익',
      gainPct: '수익률',
      day: '전일 대비',
      dayPct: '전일 대비 %',
      percentOfTotal: '비중',
      syncStatus: '동기화 상태',
      why: '사유',
    },
  },
})
