import { defineCopy } from '@/lib/ui-copy/define'

export const cryptoPremium = defineCopy({
  en: {
    title: 'Korea Premium',
    emphasis: 'Premium',
    subtitleWithData: (asOf: string) => `Domestic versus global pricing for the coins actually held, as of ${asOf}.`,
    subtitleNoData: 'No crypto price snapshot yet — run pnpm refresh.',
    weightedPremium: 'Weighted Premium',
    weightedPremiumInfo:
      'KRW-venue crypto premium weighted by the value of held KRW-venue positions. Use this as the headline premium exposure signal.',
    premiumHeadline: 'Premium headline',
    weightedHint: 'Across KRW-venue holdings, weighted by value',
    premiumBearingValue: 'Premium-Bearing Value',
    premiumBearingHint: 'KRW-venue positions marked at their own book',
    valueFromPremium: 'Value From Premium',
    valueFromPremiumHint: 'What parity would remove',
    coinsCompared: 'Coins Compared',
    readOrder: 'Premium Read Order',
    readOrderInfo: 'Start with weighted exposure, then check premium-bearing value and coin-level rows.',
    threshold: 'Threshold',
    thresholdHint: 'Notable premium threshold',
    coverage: 'Coverage',
    coverageHint: 'Available premium history',
    byCoin: 'Current premium by coin',
    whatThisMeasures: 'What this measures',
    history: 'Premium history',
    nearParity: 'Near parity',
    noPairs: 'No coin is quoted on both a KRW and a USD book — nothing to compare.',
    noHistory: 'No overlapping history — run pnpm refresh.',
    axisLabel: 'Premium %',
    columns: {
      coin: 'Coin',
      krwVenue: 'Bithumb (KRW)',
      globalVenue: 'Global (USD)',
      impliedKrw: 'Implied KRW',
      premium: 'Premium',
      held: 'Held',
      valueFromPremium: 'Value From Premium',
    },
  },
  ko: {
    title: '코리아 프리미엄',
    emphasis: '프리미엄',
    subtitleWithData: (asOf: string) => `실제 보유한 코인의 국내·해외 가격 비교입니다. 기준 ${asOf}.`,
    subtitleNoData: '아직 가상자산 시세 스냅샷이 없습니다 — pnpm refresh를 실행하세요.',
    weightedPremium: '가중 프리미엄',
    weightedPremiumInfo:
      '보유 중인 원화 거래소 포지션의 평가금액으로 가중한 프리미엄입니다. 프리미엄 노출을 보는 대표 지표로 쓰세요.',
    premiumHeadline: '프리미엄 대표값',
    weightedHint: '원화 거래소 보유분 전체를 평가금액으로 가중',
    premiumBearingValue: '프리미엄 적용 금액',
    premiumBearingHint: '각 거래소 자체 호가로 평가한 원화 거래소 포지션',
    valueFromPremium: '프리미엄 기여분',
    valueFromPremiumHint: '가격이 같아지면 사라지는 금액',
    coinsCompared: '비교된 코인',
    readOrder: '프리미엄 읽는 순서',
    readOrderInfo: '가중 노출을 먼저 보고, 프리미엄 적용 금액과 코인별 행을 확인하세요.',
    threshold: '기준선',
    thresholdHint: '주목할 프리미엄 기준',
    coverage: '이력 범위',
    coverageHint: '확보된 프리미엄 이력',
    byCoin: '코인별 현재 프리미엄',
    whatThisMeasures: '이 지표의 의미',
    history: '프리미엄 추이',
    nearParity: '가격 차 거의 없음',
    noPairs: '원화·달러 양쪽에 호가가 있는 코인이 없어 비교할 대상이 없습니다.',
    noHistory: '겹치는 이력이 없습니다 — pnpm refresh를 실행하세요.',
    axisLabel: '프리미엄 %',
    columns: {
      coin: '코인',
      krwVenue: '빗썸 (원화)',
      globalVenue: '해외 (달러)',
      impliedKrw: '환산 원화',
      premium: '프리미엄',
      held: '보유량',
      valueFromPremium: '프리미엄 기여분',
    },
  },
})
