import { defineCopy } from '@/lib/ui-copy/define'

export const dailyBriefing = defineCopy({
  en: {
    eyebrow: 'Portfolio',
    title: 'Daily Briefing',
    emphasis: 'Briefing',
    subtitle: 'Archived daily briefings, published each trading morning.',
    briefingDate: 'Briefing date',
    view: 'View',
    latest: 'Latest',
    latestSuffix: 'latest',
    costShort: 'Cost',
    archived: 'Archived',
    sessionReturn: 'Session Return',
    sessionPlInfo:
      'Price movement on the shares already held, measured against the previous archived snapshot. Shares bought or sold since then are excluded, so this is the market move and not the effect of trading.',
    sessionPl: 'Session P/L',
    dailyMove: 'Daily move',
    standingSnapshot: 'Standing snapshot',
    portfolioValue: 'Portfolio Value',
    unrealized: 'Unrealized P/L',
    readOrder: 'Briefing Read Order',
    readOrderInfo: 'Use the daily move first, then standing value and cumulative unrealized performance.',
    market: 'Market',
    costBasis: 'Cost Basis',
    standingVsCost: 'Standing versus purchase cost',
    cumulativeNote: 'cumulative since purchase — moves slowly',
    gainers: 'Session gainers',
    decliners: 'Session decliners',
    bestVsCost: 'Best vs cost',
    worstVsCost: 'Worst vs cost',
    largestPositions: 'Largest positions',
    marketContext: 'Market context',
    suggestedActions: 'Suggested actions to consider',
    documentBuilt: 'Document built',
    markets: 'Markets',
    archive: 'Archive',
    actNow: 'Act now',
    thisWeek: 'This week',
    noMovers: 'No movers in this briefing',
    noSnapshot: 'No holdings snapshot was retained for this briefing.',
    noPrices: 'The holdings sheet carried no usable prices on both sides of the comparison.',
    noNote: 'No note in this briefing.',
    unreadable: 'That briefing could not be read.',
    noArchive: 'No briefings archived yet.',
    noPriorSnapshot: 'No prior snapshot was available to compare against.',
    sessionZero: 'Session figures are therefore zero; the standing-versus-cost view below is unaffected.',
    columns: {
      ticker: 'Ticker',
      marketValue: 'Market Value',
      costBasis: 'Cost Basis',
      returnPct: 'Return',
      accounts: 'Accounts',
    },
  },
  ko: {
    eyebrow: '포트폴리오',
    title: '오늘의 브리핑',
    emphasis: '브리핑',
    subtitle: '거래일 아침마다 발행되어 보관된 일일 브리핑입니다.',
    briefingDate: '브리핑 날짜',
    view: '보기',
    latest: '최신',
    latestSuffix: '최신',
    costShort: '원가',
    archived: '보관됨',
    sessionReturn: '당일 수익률',
    sessionPlInfo: '이미 보유 중이던 주식의 가격 변동을, 직전에 보관된 스냅샷과 비교해 측정한 값입니다. 그 이후의 매수·매도는 제외하므로 매매의 효과가 아니라 시장의 움직임입니다.',
    sessionPl: '당일 손익',
    dailyMove: '당일 변동',
    standingSnapshot: '기준 스냅샷',
    portfolioValue: '포트폴리오 평가금액',
    unrealized: '평가손익',
    readOrder: '브리핑 읽는 순서',
    readOrderInfo: '당일 변동을 먼저 보고, 그다음 기준 평가금액과 누적 평가손익을 확인하세요.',
    market: '시장',
    costBasis: '취득원가',
    standingVsCost: '취득원가 대비 현재',
    cumulativeNote: '매수 이후 누적 — 천천히 움직입니다',
    gainers: '당일 상승',
    decliners: '당일 하락',
    bestVsCost: '원가 대비 최고',
    worstVsCost: '원가 대비 최저',
    largestPositions: '최대 보유',
    marketContext: '시장 상황',
    suggestedActions: '검토할 만한 조치',
    documentBuilt: '문서 생성',
    markets: '시장',
    archive: '보관함',
    actNow: '즉시',
    thisWeek: '이번 주',
    noMovers: '이 브리핑에는 변동 종목이 없습니다',
    noSnapshot: '이 브리핑에는 보유 스냅샷이 보관되지 않았습니다.',
    noPrices: '보유 시트에 비교 양쪽 모두 쓸 수 있는 가격이 없었습니다.',
    noNote: '이 브리핑에는 메모가 없습니다.',
    unreadable: '해당 브리핑을 읽을 수 없었습니다.',
    noArchive: '아직 보관된 브리핑이 없습니다.',
    noPriorSnapshot: '비교할 이전 스냅샷이 없었습니다.',
    sessionZero: '따라서 당일 수치는 0입니다. 아래의 원가 대비 현황은 영향을 받지 않습니다.',
    columns: {
      ticker: '종목코드',
      marketValue: '평가금액',
      costBasis: '취득원가',
      returnPct: '수익률',
      accounts: '계좌',
    },
  },
})
