import { defineCopy } from '@/lib/ui-copy/define'

export const dataOps = defineCopy({
  en: {
    eyebrow: 'System & Advanced',
    title: 'Action Center',
    emphasis: 'Center',
    subtitle: 'Review ticker mapping, missing valuations, source freshness, and validation items that need attention.',
    needsReview: (count: string) => `Operations review ${count}`,
    noPending: 'No pending work',
    needsReviewTitle: 'Operations Review Queue',
    needsReviewInfo: 'Operational follow-up items from mapping suggestions, valuation fixes, source freshness, and validation checks. This is separate from confirmed portfolio discrepancies.',
    headline: 'Operations headline',
    triageHint: 'Items to triage before trusting downstream analysis',
    noPendingHint: 'No pending operations work',
    mappingSuggestions: 'Mapping Suggestions',
    mappingSuggestionsHint: 'Candidate manual rules',
    valuationFixes: 'Valuation Fixes',
    valuationFixesHint: 'Holdings needing price handling',
    sourceCheckIssues: 'Source & Check Issues',
    sourceCheckIssuesHint: 'Freshness or validation issues',
    manualCoverage: 'Manual Mapping Coverage',
    manualCoverageInfo: 'Rules and overrides that fill gaps when income rows cannot be linked automatically.',
    incomeRules: 'Income Rules',
    incomeRulesHint: 'Rules mapping dividends or interest to a ticker or category',
    manualOverrides: 'Manual Overrides',
    manualOverridesHint: 'Items assigned instead of automatic mapping',
    readOrder: 'Read order: queued work first, then mapping coverage, then detailed triage tables.',
    priorityWork: 'Priority Work',
    priorityWorkInfo: 'Items to review first, based on impact and count.',
    noPriorityWork: 'No operations work to review',
    priorityCaption: 'Priority operations work',
    view: 'View',
    manualSettings: 'Manual Mapping Settings',
    manualSettingsInfo: 'Advanced settings that fill gaps when income data cannot be linked automatically.',
    version: 'Version',
    notRecorded: 'Not recorded',
    incomeMappingRules: 'Income mapping rules',
    dividendOverrides: 'Dividend overrides',
    mappingStatus: 'Mapping Status',
    mappingStatusCaption: 'Income data mapping status',
    manualSuggestions: 'Manual mapping suggestions',
    noManualSuggestions: 'No manual mapping suggestions',
    valuationFixSuggestions: 'Valuation fix suggestions',
    noValuationFixes: 'No valuation fixes suggested',
    tickerlessTriage: 'Tickerless income triage',
    allIncomeMapped: 'All income rows are ticker-mapped',
    missingValuation: 'Missing valuation',
    noMissingValuation: 'No holdings missing market value',
    sourceValidationIssues: 'Source and validation issues',
    noSourceValidationIssues: 'No stale, drifted, missing, or failing inputs',
    columns: {
      priority: 'Priority',
      area: 'Area',
      count: 'Count',
      action: 'Needed action',
      open: 'Open',
      status: 'Status',
      category: 'Category',
      rows: 'Rows',
      baseIncome: 'Base Income',
      market: 'Market',
      broker: 'Broker',
      position: 'Position',
      reason: 'Reason',
      suggestion: 'Suggested handling',
      suggestedRule: 'Suggested rule',
      base: 'Base',
      rule: 'Rule',
      name: 'Name',
      type: 'Type',
      native: 'Native',
      account: 'Account',
      nativeCost: 'Native Cost',
      baseCost: 'Base Cost',
    },
  },
  ko: {
    eyebrow: '시스템 · 고급',
    title: '조치 센터',
    emphasis: '센터',
    subtitle: '종목 매핑, 평가금액 누락, 원본 최신성, 검증 항목 중 확인이 필요한 작업을 봅니다.',
    needsReview: (count: string) => `운영 검토 대기 ${count}건`,
    noPending: '대기 작업 없음',
    needsReviewTitle: '운영 검토 대기',
    needsReviewInfo: '매핑 제안, 평가금액 보정, 원본 최신성, 검증 항목에서 후속 확인이 필요한 운영 작업 합계입니다. 확정된 포트폴리오 discrepancy와는 별도입니다.',
    headline: '운영 핵심 지표',
    triageHint: '하위 분석을 신뢰하기 전에 확인할 항목',
    noPendingHint: '대기 중인 운영 작업 없음',
    mappingSuggestions: '매핑 제안',
    mappingSuggestionsHint: '수동 규칙 후보',
    valuationFixes: '평가금액 보정',
    valuationFixesHint: '가격 처리가 필요한 보유종목',
    sourceCheckIssues: '원본 및 검증 이슈',
    sourceCheckIssuesHint: '최신성 또는 검증 이슈',
    manualCoverage: '수동 매핑 범위',
    manualCoverageInfo: '수익 행이 자동으로 연결되지 않을 때 빈틈을 채우는 규칙과 override입니다.',
    incomeRules: '수익 규칙',
    incomeRulesHint: '배당 또는 이자를 종목/분류에 연결하는 규칙',
    manualOverrides: '수동 override',
    manualOverridesHint: '자동 매핑 대신 직접 지정한 항목',
    readOrder: '읽는 순서: 대기 작업, 매핑 범위, 상세 triage 표 순으로 확인합니다.',
    priorityWork: '우선 작업',
    priorityWorkInfo: '영향도와 건수 기준으로 먼저 확인할 항목입니다.',
    noPriorityWork: '확인할 운영 작업이 없습니다.',
    priorityCaption: '우선 운영 작업',
    view: '보기',
    manualSettings: '수동 매핑 설정',
    manualSettingsInfo: '수익 데이터가 자동 연결되지 않을 때 빈틈을 채우는 고급 설정입니다.',
    version: '버전',
    notRecorded: '기록 없음',
    incomeMappingRules: '수익 매핑 규칙',
    dividendOverrides: '배당 override',
    mappingStatus: '매핑 상태',
    mappingStatusCaption: '수익 데이터 매핑 상태',
    manualSuggestions: '수동 매핑 제안',
    noManualSuggestions: '수동 매핑 제안이 없습니다.',
    valuationFixSuggestions: '평가금액 보정 제안',
    noValuationFixes: '평가금액 보정 제안이 없습니다.',
    tickerlessTriage: '종목 미연결 수익 triage',
    allIncomeMapped: '모든 수익 행이 종목에 연결되어 있습니다.',
    missingValuation: '평가금액 누락',
    noMissingValuation: '평가금액이 누락된 보유종목이 없습니다.',
    sourceValidationIssues: '원본 및 검증 이슈',
    noSourceValidationIssues: '오래되었거나 변경되었거나 누락되었거나 실패한 입력값이 없습니다.',
    columns: {
      priority: '우선순위',
      area: '영역',
      count: '건수',
      action: '필요 조치',
      open: '열기',
      status: '상태',
      category: '분류',
      rows: '행',
      baseIncome: '원화 수익',
      market: '시장',
      broker: '증권사',
      position: '종목',
      reason: '이유',
      suggestion: '제안 처리',
      suggestedRule: '제안 규칙',
      base: '원화 기준',
      rule: '규칙',
      name: '이름',
      type: '유형',
      native: '현지 통화',
      account: '계좌',
      nativeCost: '현지 통화 원가',
      baseCost: '원화 원가',
    },
  },
})
