import { defineCopy } from '@/lib/ui-copy/define'

export const dataMap = defineCopy({
  en: {
    eyebrow: 'System',
    title: 'Source & Retention',
    emphasis: 'Retention',
    subtitle: (dir: string, ingestedAt: string) => `Source inventory for ${dir}. Last ingest: ${ingestedAt}.`,
    reviewItems: (count: string) => `${count} source issue(s)`,
    allMapped: 'No source issues',
    itemsToReview: 'Source Issues',
    itemsToReviewInfo: 'Source files that are missing or changed. Unused files are shown as inventory information because they may be retained for provenance.',
    inventoryHeadline: 'Inventory headline',
    issueHint: 'Drifted or missing sources',
    cleanHint: 'No missing or changed sources',
    unused: 'Inactive inventory',
    unusedHint: 'Present but not used by the latest ingest; may be retained',
    drift: 'Drift',
    driftHint: 'Changed versus expected',
    missing: 'Missing',
    missingHint: 'Expected but absent',
    inventoryCoverage: 'Inventory Coverage',
    inventoryCoverageInfo: 'Mapped source count and total inventory footprint from the latest ingest.',
    used: 'Used',
    usedHint: 'Sources mapped into the data model',
    inventorySize: 'Inventory Size',
    inventorySizeHint: 'Total bytes across tracked sources',
    readOrder: 'Read order: review queue first, then coverage, then full file inventory.',
    retentionGuide: 'Retention reason is the source role, not a delete instruction.',
    retentionLabels: { active: 'Active source', fallback: 'Fallback', archive: 'Archive', derived: 'Derived', review: 'Review' },
    reviewQueue: 'Source issue queue',
    noQueue: 'No drifted or missing source files',
    fullInventory: 'Full source inventory',
    driftMonitor: 'Source drift monitor',
    driftMonitorInfo: 'Whether a tracked file changed after the ingest read it. A drifted file means the dashboard and the file on disk no longer agree.',
    columns: {
      status: 'Status',
      category: 'Category',
      file: 'File',
      size: 'Size',
      detail: 'Detail',
      retention: 'Retention',
      dataset: 'Dataset',
      path: 'Path',
      rows: 'Rows',
      modified: 'Modified',
      sha: 'SHA-256',
    },
  },
  ko: {
    eyebrow: '시스템',
    title: '원본 · 보존',
    emphasis: '보존',
    subtitle: (dir: string, ingestedAt: string) => `${dir}의 원본 인벤토리입니다. 마지막 ingest: ${ingestedAt}.`,
    reviewItems: (count: string) => `원본 이슈 ${count}건`,
    allMapped: '원본 이슈 없음',
    itemsToReview: '원본 이슈',
    itemsToReviewInfo: '변경되었거나 누락된 원본 파일입니다. 미사용 파일은 provenance 보존을 위해 정보성 목록으로 표시합니다.',
    inventoryHeadline: '인벤토리 핵심 지표',
    issueHint: '변경 또는 누락된 원본',
    cleanHint: '변경·누락된 원본이 없습니다.',
    unused: '비활성 인벤토리',
    unusedHint: '현재 ingest에는 쓰이지 않지만 보존될 수 있는 파일',
    drift: '변경',
    driftHint: '예상 상태와 달라짐',
    missing: '누락',
    missingHint: '예상 파일이 없음',
    inventoryCoverage: '인벤토리 범위',
    inventoryCoverageInfo: '마지막 ingest 기준 매핑된 원본 수와 전체 인벤토리 크기입니다.',
    used: '사용 중',
    usedHint: '데이터 모델에 매핑된 원본',
    inventorySize: '인벤토리 크기',
    inventorySizeHint: '추적 중인 원본의 총 바이트',
    readOrder: '읽는 순서: 확인 대기열, 범위, 전체 파일 인벤토리 순으로 봅니다.',
    retentionGuide: '보존 이유는 파일의 역할을 설명하며, 삭제 지시가 아닙니다.',
    retentionLabels: { active: '운영 원본', fallback: '대체 원본', archive: '보관 원본', derived: '파생 산출물', review: '추가 확인' },
    reviewQueue: '원본 이슈 대기열',
    noQueue: '변경되거나 누락된 원본 파일이 없습니다.',
    fullInventory: '전체 원본 인벤토리',
    driftMonitor: '원본 변경 감시',
    driftMonitorInfo: 'ingest가 읽은 뒤 파일이 바뀌었는지 봅니다. 변경된 파일은 대시보드와 디스크의 내용이 더 이상 일치하지 않는다는 뜻입니다.',
    columns: {
      status: '상태',
      category: '분류',
      file: '파일',
      size: '크기',
      detail: '상세',
      retention: '보존 이유',
      dataset: '데이터셋',
      path: '경로',
      rows: '행',
      modified: '수정일',
      sha: 'SHA-256',
    },
  },
})
