import { defineCopy } from '@/lib/ui-copy/define'

export const income = defineCopy({
  en: {
    title: 'Income',
    emphasis: 'Income',
    subtitle: (rows: string, month: string) => `${rows} income rows across KR and US sources. Latest month: ${month}.`,
    tickerlessRows: (count: string) => `${count} tickerless row(s)`,
    tickerMapped: 'Ticker-mapped',
    trailing12mIncome: 'Trailing 12M Income',
    trailing12mInfo: 'Income received over the last twelve months, converted to KRW. Use this as the headline income run-rate.',
    incomeRunRate: 'Income run-rate',
    baseIncomeHint: 'KRW base income after applying FX',
    ytdIncome: 'YTD Income',
    latestMonth: (month: string) => `Latest month ${month}`,
    yieldOnMarket: 'Yield on Market',
    yieldOnMarketHint: 'Income divided by market value',
    yieldOnCost: 'Yield on Cost',
    yieldOnCostHint: 'Income divided by cost basis',
    incomeCoverage: 'Income Coverage',
    incomeCoverageInfo: 'Native-currency source totals and unmapped rows that can affect position-level income analysis.',
    nativeTotals: 'KRW / USD Native',
    sourceRows: (count: string) => `${count} source rows`,
    tickerlessRowsLabel: 'Tickerless Rows',
    tickerlessHint: 'Included in totals, excluded from position yield rankings',
    readOrder: 'Read order: run-rate first, then yield, then mapping coverage.',
    incomeMix: 'Income mix',
    dividendDistribution: 'Dividend / distribution',
    interest: 'Interest',
    otherIncome: 'Other income',
    marketIncome: 'Market income',
    native: 'native',
    rows: 'rows',
    dataQuality: 'Data quality',
    tickerMappedRows: 'Ticker-mapped rows',
    tickerlessRowsLower: 'Tickerless rows',
    tickerlessQualityNote: 'Tickerless rows are kept in income totals but excluded from position yield rankings until mapped.',
    monthlyIncomeTrend: 'Monthly income trend',
    yearlyNativeTotals: 'Yearly native totals',
    chartAxis: 'KRW thousand',
    chartAxisUsd: 'USD',
    chartNote: 'Values are KRW thousands after applying the configured FX snapshot.',
    chartNoteUsd: 'Values are USD after applying the configured FX snapshot.',
    topIncomePositions: 'Top income positions',
    tickerlessIncomeRows: 'Tickerless income rows',
    allIncomeMapped: 'All income rows are ticker-mapped',
    columns: {
      year: 'Year',
      currency: 'Currency',
      rows: 'Rows',
      native: 'Native',
      base: 'Base',
      position: 'Position',
      nativeIncome: 'Native Income',
      baseIncome: 'Base Income',
      marketValue: 'Market Value',
      yield: 'Yield',
      yieldOnCost: 'Yield on Cost',
      market: 'Market',
      type: 'Type',
      name: 'Name',
    },
  },
  ko: {
    title: '수익 내역',
    emphasis: '내역',
    subtitle: (rows: string, month: string) => `한국/미국 원본의 수익 행 ${rows}건입니다. 최신 월: ${month}.`,
    tickerlessRows: (count: string) => `종목 미연결 ${count}건`,
    tickerMapped: '종목 연결 완료',
    trailing12mIncome: '최근 12개월 수익',
    trailing12mInfo: '최근 12개월 동안 받은 수익을 원화로 환산한 값입니다. 수익 흐름의 대표 지표로 봅니다.',
    incomeRunRate: '수익 흐름',
    baseIncomeHint: '환율 적용 후 원화 기준 수익',
    ytdIncome: '연초 이후 수익',
    latestMonth: (month: string) => `최신 월 ${month}`,
    yieldOnMarket: '평가금액 대비 수익률',
    yieldOnMarketHint: '수익을 현재 평가금액으로 나눈 값',
    yieldOnCost: '취득원가 대비 수익률',
    yieldOnCostHint: '수익을 취득원가로 나눈 값',
    incomeCoverage: '수익 데이터 범위',
    incomeCoverageInfo: '현지 통화 기준 원본 합계와 종목에 연결되지 않은 행입니다. 종목별 수익 분석에 영향을 줄 수 있습니다.',
    nativeTotals: 'KRW / USD 원본 합계',
    sourceRows: (count: string) => `원본 ${count}행`,
    tickerlessRowsLabel: '종목 미연결 행',
    tickerlessHint: '합계에는 포함되지만 종목별 수익률 순위에서는 제외됩니다.',
    readOrder: '읽는 순서: 수익 흐름, 수익률, 매핑 범위 순으로 확인합니다.',
    incomeMix: '수익 구성',
    dividendDistribution: '배당 / 분배금',
    interest: '이자',
    otherIncome: '기타 수익',
    marketIncome: '시장별 수익',
    native: '현지 통화',
    rows: '행',
    dataQuality: '데이터 품질',
    tickerMappedRows: '종목 연결 행',
    tickerlessRowsLower: '종목 미연결 행',
    tickerlessQualityNote: '종목 미연결 행은 수익 합계에는 포함되지만, 매핑되기 전까지 종목별 수익률 순위에서는 제외됩니다.',
    monthlyIncomeTrend: '월별 수익 추이',
    yearlyNativeTotals: '연도별 현지 통화 합계',
    chartAxis: '천 원',
    chartAxisUsd: '달러',
    chartNote: '설정된 환율 스냅샷을 적용한 천 원 단위 값입니다.',
    chartNoteUsd: '설정된 환율 스냅샷을 적용한 달러 값입니다.',
    topIncomePositions: '수익 상위 종목',
    tickerlessIncomeRows: '종목 미연결 수익 행',
    allIncomeMapped: '모든 수익 행이 종목에 연결되어 있습니다.',
    columns: {
      year: '연도',
      currency: '통화',
      rows: '행',
      native: '현지 통화',
      base: '원화 기준',
      position: '종목',
      nativeIncome: '현지 통화 수익',
      baseIncome: '원화 수익',
      marketValue: '평가금액',
      yield: '수익률',
      yieldOnCost: '취득원가 대비 수익률',
      market: '시장',
      type: '유형',
      name: '이름',
    },
  },
})
