import { defineCopy } from '@/lib/ui-copy/define'

export const lots = defineCopy({
  en: {
    title: 'Tax Lots',
    emphasis: 'Lots',
    subtitle: 'Open tax lots with search, account filters, sorting, and ticker drilldown.',
    card: 'Open tax lots',
    searchPlaceholder: 'ticker, name, account, source',
    filtered: 'Filtered',
    openQuantity: 'Open quantity',
    baseCost: 'Base cost',
    unknownTerm: 'Unknown',
    terms: { 'Long-term': 'Long-term', 'Short-term': 'Short-term' } as Record<string, string>,
    filters: { market: 'Market', broker: 'Broker', account: 'Account', type: 'Type', term: 'Term', status: 'Status' },
    columns: {
      market: 'Market',
      broker: 'Broker',
      account: 'Account',
      instrument: 'Instrument',
      acquired: 'Acquired',
      quantity: 'Qty',
      costBasis: 'Cost Basis',
      baseCost: 'Base Cost',
      days: 'Days',
      term: 'Term',
    },
  },
  ko: {
    title: '세금 계산 단위',
    emphasis: '단위',
    subtitle: '검색·계좌 필터·정렬·종목 드릴다운이 가능한 미결제 세금 단위입니다.',
    card: '미결제 세금 단위',
    searchPlaceholder: '종목코드, 종목명, 계좌, 원본',
    filtered: '필터 결과',
    openQuantity: '미결제 수량',
    baseCost: '원화 취득원가',
    unknownTerm: '미상',
    terms: { 'Long-term': '장기', 'Short-term': '단기' } as Record<string, string>,
    filters: { market: '시장', broker: '증권사', account: '계좌', type: '유형', term: '과세 구분', status: '상태' },
    columns: {
      market: '시장',
      broker: '증권사',
      account: '계좌',
      instrument: '종목',
      acquired: '취득일',
      quantity: '수량',
      costBasis: '취득원가',
      baseCost: '원화 취득원가',
      days: '보유일',
      term: '과세 구분',
    },
  },
})
