import { defineCopy } from '@/lib/ui-copy/define'

export const netWorth = defineCopy({
  en: {
    title: 'Net Worth',
    emphasis: 'Worth',
    subtitle: (asOf: string) => `Securities, crypto, bank deposits, pensions and gold in one KRW figure. Portfolio data as of ${asOf}.`,
    total: 'Total net worth',
    byClass: 'By asset class',
    classes: { stocks: 'Stocks', crypto: 'Crypto', cash: 'Cash', pensions: 'Pensions', gold: 'Gold' },
    asOfNotesHint: "A dated class is valued from a snapshot, at cost, or from a balance older than today, not from today's price.",
    asOfNote: (label: string, asOf: string) => `${label} as of ${asOf}`,
    trend: 'Total assets trend',
    trendStarts: (parts: string[]) => (parts.length ? `Each class starts on its first data: ${parts.join(' · ')}` : 'No asset class has data yet.'),
    classSince: (label: string, date: string) => `${label} from ${date}`,
    trendNote:
      'Pensions move only on certificate and snapshot dates, and hold the last value between them. Gold is grams held times the KRX price on or before each date, at cost where no price is stored. Before a class starts it adds nothing. The last point is today.',
    chartAxisKrw: 'KRW million',
    chartAxisUsd: 'USD million',
    balances: 'Deposit balances',
    columns: { institution: 'Institution', account: 'Account', kind: 'Kind', asOf: 'As of', balance: 'Balance', krw: 'Value' },
    kinds: { checking: 'Checking', savings: 'Savings', cma: 'CMA', deposit: 'Deposit' },
    derived: 'Derived from an anchor balance',
    unpriced: (list: string) => `No USD/KRW rate is available for ${list}. These accounts are not in the total.`,
    history: 'Month-end history',
    historyColumns: { month: 'Month', stocks: 'Stocks', crypto: 'Crypto', cash: 'Cash', pensions: 'Pensions', gold: 'Gold', total: 'Total' },
    historyNote: "Each month's last portfolio snapshot, and today for the current month. A dash is a class with no data yet on that date.",
    historyFxNote: 'Past USD deposits are converted at the historical USD/KRW rate where one is stored, otherwise at today\'s rate.',
    none: '—',
    empty: 'No deposit balances collected yet',
  },
  ko: {
    title: '순자산',
    emphasis: '순자산',
    subtitle: (asOf: string) => `증권, 암호화폐, 은행 예금, 연금, 금을 원화 한 숫자로 보여줍니다. 포트폴리오 기준일: ${asOf}.`,
    total: '총 순자산',
    byClass: '자산군별',
    classes: { stocks: '주식', crypto: '암호화폐', cash: '현금', pensions: '연금', gold: '금' },
    asOfNotesHint: '날짜가 붙은 자산군은 오늘 시세가 아니라 snapshot, 취득원가 또는 오늘 이전 잔고 기준입니다.',
    asOfNote: (label: string, asOf: string) => `${label} ${asOf} 기준`,
    trend: '자산 현황 추이',
    trendStarts: (parts: string[]) => (parts.length ? `자산군별 데이터 시작일: ${parts.join(' · ')}` : '아직 데이터가 있는 자산군이 없습니다.'),
    classSince: (label: string, date: string) => `${label} ${date}부터`,
    trendNote:
      '연금은 증명서와 snapshot 날짜에만 바뀌고, 그 사이에는 마지막 값을 유지합니다. 금은 보유 그램 × 해당 날짜 이전 최신 KRX 시세이며, 시세가 없으면 취득원가입니다. 데이터가 시작되기 전의 자산군은 더하지 않습니다. 마지막 점은 오늘입니다.',
    chartAxisKrw: '백만 원',
    chartAxisUsd: '백만 달러',
    balances: '예금 잔고',
    columns: { institution: '기관', account: '계좌', kind: '종류', asOf: '기준일', balance: '잔고', krw: '평가액' },
    kinds: { checking: '입출금', savings: '저축', cma: 'CMA', deposit: '예금' },
    derived: '기준 잔고에서 역산',
    unpriced: (list: string) => `${list}은(는) USD/KRW 환율이 없어 합계에 포함되지 않았습니다.`,
    history: '월말 추이',
    historyColumns: { month: '월', stocks: '주식', crypto: '암호화폐', cash: '현금', pensions: '연금', gold: '금', total: '합계' },
    historyNote: '매월 마지막 포트폴리오 snapshot 기준이며, 이번 달은 오늘 기준입니다. 대시(—)는 그 날짜에 아직 데이터가 없는 자산군입니다.',
    historyFxNote: '과거 USD 예금은 저장된 당시 USD/KRW 환율로 환산하고, 없으면 오늘 환율을 씁니다.',
    none: '—',
    empty: '아직 수집된 예금 잔고가 없습니다',
  },
})
