import { defineCopy } from '@/lib/ui-copy/define'

export const netWorth = defineCopy({
  en: {
    title: 'Net Worth',
    emphasis: 'Worth',
    subtitle: (asOf: string) => `Securities, crypto, bank deposits, pensions and gold in one KRW figure. Portfolio data as of ${asOf}.`,
    total: 'Total net worth',
    byClass: 'By asset class',
    classes: { stocks: 'Stocks', crypto: 'Crypto', cash: 'Cash', pensions: 'Pensions', gold: 'Gold' },
    asOfNotesHint: "A dated class is valued from a snapshot, at cost, or from a balance older than today, not from today's price.",
    asOfNote: (label: string, asOf: string) => `${label} as of ${asOf}`,
    trend: 'Total assets trend',
    trendStarts: (parts: string[]) => (parts.length ? `Each class starts on its first data: ${parts.join(' · ')}` : 'No asset class has data yet.'),
    classSince: (label: string, date: string) => `${label} from ${date}`,
    trendNote:
      'Pensions move only on certificate and snapshot dates, and hold the last value between them. Gold is grams held times the KRX price on or before each date, at cost where no price is stored. Before a class starts it adds nothing. The last point is today.',
    chartAxisKrw: 'KRW million',
    chartAxisUsd: 'USD million',
    balances: 'Deposit balances',
    columns: { institution: 'Institution', account: 'Account', kind: 'Kind', asOf: 'As of', balance: 'Balance', krw: 'Value' },
    kinds: { checking: 'Checking', savings: 'Savings', cma: 'CMA', deposit: 'Deposit' },
    derived: 'Derived from an anchor balance',
    unpriced: (list: string) => `No USD/KRW rate is available for ${list}. These accounts are not in the total.`,
    history: 'Month-end history',
    historyColumns: { month: 'Month', stocks: 'Stocks', crypto: 'Crypto', cash: 'Cash', pensions: 'Pensions', gold: 'Gold', total: 'Total' },
    historyNote: "Each month's last portfolio snapshot, and today for the current month. A dash is a class with no data yet on that date.",
    historyFxNote: 'Past USD deposits are converted at the historical USD/KRW rate where one is stored, otherwise at today\'s rate.',
    none: '—',
    empty: 'No deposit balances collected yet',
    fbar: {
      title: 'Foreign account maximum balances (FBAR / Form 8938)',
      yearLabel: 'Year',
      note: 'Reference figures for preparing FBAR and Form 8938; filing thresholds depend on filing status — confirm with your preparer.',
      method:
        'Foreign accounts are every account not held at a US institution: Korean cash accounts, Korean brokerage accounts, pensions and gold. USD figures use the U.S. Treasury Reporting Rate of Exchange for the last day of the year; a USD account keeps its own dollar maximum.',
      rate: (krwPerUsd: string, date: string) => `Treasury rate: ${krwPerUsd} KRW per USD on ${date}.`,
      noRate: (year: number) => `No Treasury year-end rate is on file for ${year}, so the figures are in KRW only.`,
      understatedNote: 'An "understated" row was not found from daily balances, so the true maximum may be higher.',
      columns: { account: 'Account', kind: 'Kind', maxDate: 'Date of maximum', maxKrw: 'Maximum (KRW)', maxUsd: 'Maximum (USD)', coverage: 'Basis' },
      kinds: { cash: 'Cash', brokerage: 'Brokerage', pension: 'Pension', gold: 'Gold' },
      coverage: { daily: 'Daily balances', month_end: 'Month-end values', year_end: 'Year-end totals', partial: 'Part of the year' },
      understated: 'Understated',
      aggregate: 'Aggregate of maximums',
      empty: (year: number) => `No foreign account has data for ${year}.`,
    },
  },
  ko: {
    title: '순자산',
    emphasis: '순자산',
    subtitle: (asOf: string) => `증권, 암호화폐, 은행 예금, 연금, 금을 원화 한 숫자로 보여줍니다. 포트폴리오 기준일: ${asOf}.`,
    total: '총 순자산',
    byClass: '자산군별',
    classes: { stocks: '주식', crypto: '암호화폐', cash: '현금', pensions: '연금', gold: '금' },
    asOfNotesHint: '날짜가 붙은 자산군은 오늘 시세가 아니라 snapshot, 취득원가 또는 오늘 이전 잔고 기준입니다.',
    asOfNote: (label: string, asOf: string) => `${label} ${asOf} 기준`,
    trend: '자산 현황 추이',
    trendStarts: (parts: string[]) => (parts.length ? `자산군별 데이터 시작일: ${parts.join(' · ')}` : '아직 데이터가 있는 자산군이 없습니다.'),
    classSince: (label: string, date: string) => `${label} ${date}부터`,
    trendNote:
      '연금은 증명서와 snapshot 날짜에만 바뀌고, 그 사이에는 마지막 값을 유지합니다. 금은 보유 그램 × 해당 날짜 이전 최신 KRX 시세이며, 시세가 없으면 취득원가입니다. 데이터가 시작되기 전의 자산군은 더하지 않습니다. 마지막 점은 오늘입니다.',
    chartAxisKrw: '백만 원',
    chartAxisUsd: '백만 달러',
    balances: '예금 잔고',
    columns: { institution: '기관', account: '계좌', kind: '종류', asOf: '기준일', balance: '잔고', krw: '평가액' },
    kinds: { checking: '입출금', savings: '저축', cma: 'CMA', deposit: '예금' },
    derived: '기준 잔고에서 역산',
    unpriced: (list: string) => `${list}은(는) USD/KRW 환율이 없어 합계에 포함되지 않았습니다.`,
    history: '월말 추이',
    historyColumns: { month: '월', stocks: '주식', crypto: '암호화폐', cash: '현금', pensions: '연금', gold: '금', total: '합계' },
    historyNote: '매월 마지막 포트폴리오 snapshot 기준이며, 이번 달은 오늘 기준입니다. 대시(—)는 그 날짜에 아직 데이터가 없는 자산군입니다.',
    historyFxNote: '과거 USD 예금은 저장된 당시 USD/KRW 환율로 환산하고, 없으면 오늘 환율을 씁니다.',
    none: '—',
    empty: '아직 수집된 예금 잔고가 없습니다',
    fbar: {
      title: '해외 계좌 최대 잔고 (FBAR / Form 8938)',
      yearLabel: '연도',
      note: 'FBAR와 Form 8938 준비용 참고 수치입니다. 신고 기준 금액은 신고 유형에 따라 다르니 세무 대리인과 확인하세요.',
      method:
        '해외 계좌는 미국 금융기관에 있지 않은 모든 계좌입니다: 한국 현금 계좌, 한국 증권 계좌, 연금, 금. USD 금액은 그해 마지막 날의 미국 재무부 Reporting Rate of Exchange를 쓰며, USD 계좌는 달러 기준 최대값을 그대로 씁니다.',
      rate: (krwPerUsd: string, date: string) => `재무부 환율: ${date} 기준 1 USD = ${krwPerUsd} KRW.`,
      noRate: (year: number) => `${year}년 재무부 연말 환율이 없어 원화로만 표시합니다.`,
      understatedNote: '"과소 추정" 표시는 일별 잔고로 구한 값이 아니라 실제 최대값이 더 클 수 있다는 뜻입니다.',
      columns: { account: '계좌', kind: '종류', maxDate: '최대값 날짜', maxKrw: '최대값 (KRW)', maxUsd: '최대값 (USD)', coverage: '기준' },
      kinds: { cash: '현금', brokerage: '증권', pension: '연금', gold: '금' },
      coverage: { daily: '일별 잔고', month_end: '월말 평가액', year_end: '연말 합계', partial: '연중 일부' },
      understated: '과소 추정',
      aggregate: '최대값 합계',
      empty: (year: number) => `${year}년 데이터가 있는 해외 계좌가 없습니다.`,
    },
  },
})
