import { defineCopy } from '@/lib/ui-copy/define'

export const netWorth = defineCopy({
  en: {
    title: 'Net Worth',
    emphasis: 'Worth',
    subtitle: (asOf: string) => `Securities, crypto and bank deposits in one KRW figure. Portfolio data as of ${asOf}.`,
    total: 'Total net worth',
    byClass: 'By asset class',
    classes: { stocks: 'Stocks', crypto: 'Crypto', cash: 'Cash', pension: 'Pension', gold: 'Gold' },
    balances: 'Deposit balances',
    columns: { institution: 'Institution', account: 'Account', kind: 'Kind', asOf: 'As of', balance: 'Balance', krw: 'Value (KRW)' },
    kinds: { checking: 'Checking', savings: 'Savings', cma: 'CMA', deposit: 'Deposit' },
    derived: 'Derived from an anchor balance',
    unpriced: (list: string) => `No USD/KRW rate is available for ${list}. These accounts are not in the total.`,
    history: 'Month-end history',
    historyColumns: { month: 'Month', stocks: 'Stocks', cash: 'Cash' },
    historyNote: 'Stocks line includes crypto (portfolio snapshots)',
    historyFxNote: 'Past USD deposits are converted at the historical USD/KRW rate where one is stored, otherwise at today\'s rate.',
    none: '—',
    empty: 'No deposit balances collected yet',
  },
  ko: {
    title: '순자산',
    emphasis: '순자산',
    subtitle: (asOf: string) => `증권, 암호화폐, 은행 예금을 원화 한 숫자로 보여줍니다. 포트폴리오 기준일: ${asOf}.`,
    total: '총 순자산',
    byClass: '자산군별',
    classes: { stocks: '주식', crypto: '암호화폐', cash: '현금', pension: '연금', gold: '금' },
    balances: '예금 잔고',
    columns: { institution: '기관', account: '계좌', kind: '종류', asOf: '기준일', balance: '잔고', krw: '평가액 (KRW)' },
    kinds: { checking: '입출금', savings: '저축', cma: 'CMA', deposit: '예금' },
    derived: '기준 잔고에서 역산',
    unpriced: (list: string) => `${list}은(는) USD/KRW 환율이 없어 합계에 포함되지 않았습니다.`,
    history: '월말 추이',
    historyColumns: { month: '월', stocks: '주식', cash: '현금' },
    historyNote: '주식 선에는 crypto가 포함됩니다 (포트폴리오 snapshot)',
    historyFxNote: '과거 USD 예금은 저장된 당시 USD/KRW 환율로 환산하고, 없으면 오늘 환율을 씁니다.',
    none: '—',
    empty: '아직 수집된 예금 잔고가 없습니다',
  },
})
