import { defineCopy } from '@/lib/ui-copy/define'

export const overview = defineCopy({
  en: {
    title: 'Portfolio Overview',
    emphasis: 'Overview',
    subtitle: (ingestedAt: string, fx: string | null) =>
      `Read-only status loaded from local investment data at ${ingestedAt}.${fx ? ` Applied FX: ${fx}.` : ''}`,
    needsReview: (count: number) => `Operations review ${count}`,
    healthy: 'Healthy',
    freshnessTitle: 'Data Freshness',
    allAssets: 'All Assets Summary',
    portfolioValue: 'Total Portfolio Value',
    portfolioValueInfo: 'Current market value converted to the selected display currency across all priced holdings.',
    allMarkets: 'All markets',
    valueHint: 'Current value after applying prices and FX',
    returnOnPricedCost: 'Return on priced cost',
    primaryMetrics: 'Primary Metrics',
    supportingMetrics: 'Supporting Metrics',
    totalCost: 'Total Cost Basis',
    totalGain: 'Total Unrealized G/L',
    koreaGain: 'Korea Unrealized G/L',
    usGain: 'US Unrealized G/L',
    cryptoGain: 'Crypto Unrealized G/L',
    koreaCost: 'Korea Cost Basis',
    usCost: 'US Cost Basis',
    cryptoCost: 'Crypto Cost Basis',
    nativeCurrency: 'Native currency',
    totalShare: 'Share of total',
    holdings: 'Holdings',
    totalQuantity: 'Total quantity',
    dividends: 'Dividends',
    count: (value: string) => `${value} rows`,
    marketAllocation: 'Market Allocation',
    marketBreakdown: 'Market Breakdown',
    marketBreakdownInfo: 'Market-value share as one portfolio mix, followed by cost basis and unrealized gain/loss by market.',
    activitySummary: 'Activity Summary',
    korea: 'Korea',
    us: 'United States',
    crypto: 'Crypto',
    fxNote: (fx: string | null) => `USD assets use ${fx ?? 'the configured FX rate'}.`,
    concentration: 'Top Holding Concentration',
    concentrationInfo: 'Share of the total portfolio held by the top five positions, measured by cost basis.',
    concentrationHint: 'Cost-basis share of the top five holdings',
    termMix: 'Holding-Period Classification',
    termMixInfo: 'Value-weighted tax-lot holding-period coverage. Positions with no long/short split are shown as unclassified; crypto is included when lot terms are present.',
    termCoverage: 'classified by value',
    shortTermExposure: 'Short-term exposure',
    longTerm: 'Long-term value',
    shortTerm: 'Short-term value',
    unclassifiedTerm: 'Unclassified',
    marketValue: 'Market value',
    costBasis: 'Cost basis',
    gain: 'Gain',
    return: 'Return',
    share: 'Share',
    dbMissingTitle: 'Portfolio DB not found',
    dbMissingHint: (path: string) => <>Run <code className="font-mono text-caption">pnpm ingest</code> to generate <code className="font-mono text-caption">{path}</code>.</>,
    snapshotTrend: (scope: string) => `${scope} snapshot trend`,
    combinedTrendSummary: (scope: string) => `${scope} · Market value, cost basis, and unrealized G/L · KRW millions`,
    trendUnit: (metric: string, unit: string) => `${metric} · ${unit}`,
    percentagePoints: 'percentage points',
    krwMillions: 'KRW millions',
    usdMillions: 'USD millions',
    costPriced: (value: string) => `${value}% of cost basis priced`,
    positionsPriced: (value: string) => `${value}% of positions priced`,
    noCoveredHistory: 'No sufficiently covered history',
    partialValuation: 'Partial valuation: less than 95% of cost basis is priced.',
    since: (date: string) => `since ${date}`,
    needTwoSnapshots: 'Need at least two covered snapshots',
    individual: 'Individual',
    combined: 'Combined',
    noCombinedHistory: 'No combined history recorded',
    noPortfolioHistory: 'No portfolio history recorded',
    firstSnapshotHint: 'Run pnpm refresh or pnpm ingest to record the first snapshot.',
    chartAxisReturn: 'Percentage points',
    chartAxisKrw: 'KRW million',
    chartAxisUsd: 'USD million',
    trendRangeSummary: (start: string, end: string, valued: number, total: number, gaps: number) =>
      `${start} to ${end} · ${valued} valued / ${total} total snapshot(s)${gaps ? ` · ${gaps} gap(s)` : ''}`,
    snapshotsOnce: 'Snapshots are recorded once per ingest date.',
    trendExplanation: 'Cost basis, holdings, and dividends are reconstructed from tax-lot and transaction dates. Foreign-currency quotes are converted using FX snapshots, then displayed in the selected currency. Valuation points below 90% cost-basis coverage remain visible as chart gaps; 90–95% coverage is marked partial. Cost-basis history itself does not require a market price.',
    topHoldingsByCost: 'Top holdings by base cost',
    topHoldingsNote: 'Bar values use the selected display currency after applying the configured FX snapshot.',
    dividendTrend: 'Dividend trend',
    dividendTrendNote: 'KR bars are KRW thousands; US bars are native USD.',
    dividendAxis: 'KRW thousand / USD',
    accountAllocation: 'Account allocation',
    noAccountData: 'No account data',
    holdingRows: (count: number) => `${count} holdings`,
    largestPositions: 'Largest positions',
    transactionTypes: 'Transaction types',
    metricLabels: {
      market_value: 'Market value',
      cost_basis: 'Cost basis',
      unrealized_gl: 'Unrealized G/L',
      return_pct: 'Return %',
    },
    scopeLabels: {
      global: 'Global',
      KR: 'Korea',
      US: 'United States',
      CRYPTO: 'Crypto',
    },
  },
  ko: {
    title: '포트폴리오 개요',
    emphasis: '개요',
    subtitle: (ingestedAt: string, fx: string | null) =>
      `로컬 투자 자료를 ${ingestedAt}에 불러온 읽기 전용 현황입니다.${fx ? ` 적용 환율: ${fx}.` : ''}`,
    needsReview: (count: number) => `운영 검토 대기 ${count}건`,
    healthy: '정상',
    freshnessTitle: '데이터 최신 상태',
    allAssets: '전체 자산 요약',
    portfolioValue: '전체 평가금액',
    portfolioValueInfo: '가격과 환율을 적용해 선택한 표시 통화로 환산한 전체 보유자산의 현재 평가금액입니다.',
    allMarkets: '전체 시장',
    valueHint: '현재 가격과 환율을 적용한 평가금액',
    returnOnPricedCost: '가격 확인된 취득원가 대비 수익률',
    primaryMetrics: '핵심 지표',
    supportingMetrics: '보조 지표',
    totalCost: '전체 취득원가',
    totalGain: '전체 평가손익',
    koreaGain: '한국 평가손익',
    usGain: '미국 평가손익',
    cryptoGain: '가상자산 평가손익',
    koreaCost: '한국 취득원가',
    usCost: '미국 취득원가',
    cryptoCost: '가상자산 취득원가',
    nativeCurrency: '현지 통화',
    totalShare: '전체의',
    holdings: '보유종목',
    totalQuantity: '총 수량',
    dividends: '배당',
    count: (value: string) => `${value}건`,
    marketAllocation: '시장별 비중',
    marketBreakdown: '시장별 상세',
    marketBreakdownInfo: '전체 포트폴리오 안의 시장별 평가액 비중과 각 시장의 취득원가, 평가손익입니다.',
    activitySummary: '활동 요약',
    korea: '한국',
    us: '미국',
    crypto: '가상자산',
    fxNote: (fx: string | null) => `달러 자산은 ${fx ?? '설정된 환율'}을 적용했습니다.`,
    concentration: '상위 종목 집중도',
    concentrationInfo: '취득원가 기준 상위 5개 종목이 전체 포트폴리오에서 차지하는 비율입니다.',
    concentrationHint: '상위 5개 종목의 취득원가 비중',
    termMix: '보유기간 분류',
    termMixInfo: 'Tax lot의 장기/단기 분류가 있는 평가액 기준입니다. 장/단기 수량 분리가 없는 포지션은 미분류로 표시하며, 가상자산도 lot 기간 정보가 있으면 포함합니다.',
    termCoverage: '평가액 기준 분류됨',
    shortTermExposure: '단기 노출',
    longTerm: '장기 평가액',
    shortTerm: '단기 평가액',
    unclassifiedTerm: '미분류',
    marketValue: '평가금액',
    costBasis: '취득원가',
    gain: '손익',
    return: '수익률',
    share: '비중',
    dbMissingTitle: '포트폴리오 DB를 찾을 수 없습니다',
    dbMissingHint: (path: string) => <><code className="font-mono text-caption">pnpm ingest</code>를 실행해 <code className="font-mono text-caption">{path}</code>를 생성하세요.</>,
    snapshotTrend: (scope: string) => `${scope} 스냅샷 추이`,
    combinedTrendSummary: (scope: string) => `${scope} · 평가금액, 취득원가, 평가손익 · 백만 원 단위`,
    trendUnit: (metric: string, unit: string) => `${metric} · ${unit}`,
    percentagePoints: '퍼센트포인트',
    krwMillions: '백만 원 단위',
    usdMillions: '백만 달러 단위',
    costPriced: (value: string) => `취득원가의 ${value}% 가격 확인`,
    positionsPriced: (value: string) => `종목의 ${value}% 가격 확인`,
    noCoveredHistory: '충분히 가격이 확인된 이력이 없습니다.',
    partialValuation: '부분 평가: 취득원가의 95% 미만만 가격이 확인되었습니다.',
    since: (date: string) => `${date} 이후`,
    needTwoSnapshots: '가격이 확인된 스냅샷이 최소 2개 필요합니다.',
    individual: '개별',
    combined: '통합',
    noCombinedHistory: '통합 이력이 없습니다.',
    noPortfolioHistory: '포트폴리오 이력이 없습니다.',
    firstSnapshotHint: '첫 스냅샷을 기록하려면 pnpm refresh 또는 pnpm ingest를 실행하세요.',
    chartAxisReturn: '퍼센트포인트',
    chartAxisKrw: '백만 원',
    chartAxisUsd: '백만 달러',
    trendRangeSummary: (start: string, end: string, valued: number, total: number, gaps: number) =>
      `${start}부터 ${end}까지 · 가격 확인 ${valued}개 / 전체 ${total}개 스냅샷${gaps ? ` · 공백 ${gaps}개` : ''}`,
    snapshotsOnce: '스냅샷은 ingest 날짜마다 한 번 기록됩니다.',
    trendExplanation: '취득원가, 보유수량, 배당은 세금 단위와 거래일 기준으로 재구성됩니다. 외화 가격은 환율 스냅샷으로 환산한 뒤 선택 표시 통화로 표시됩니다. 취득원가 기준 가격 확인률이 90% 미만인 평가 지점은 차트 공백으로 남기고, 90~95%는 부분 평가로 표시합니다. 취득원가 이력 자체에는 시장 가격이 필요하지 않습니다.',
    topHoldingsByCost: '취득원가 상위 보유종목',
    topHoldingsNote: '막대 값은 설정된 환율 스냅샷을 적용한 선택 표시 통화 단위입니다.',
    dividendTrend: '배당 추이',
    dividendTrendNote: '한국 막대는 천 원 단위, 미국 막대는 현지 USD 단위입니다.',
    dividendAxis: '천 원 / USD',
    accountAllocation: '계좌별 배분',
    noAccountData: '계좌 데이터가 없습니다.',
    holdingRows: (count: number) => `${count}개 보유`,
    largestPositions: '상위 보유종목',
    transactionTypes: '거래 유형',
    metricLabels: {
      market_value: '평가금액',
      cost_basis: '취득원가',
      unrealized_gl: '평가손익',
      return_pct: '수익률 %',
    },
    scopeLabels: {
      global: '전체',
      KR: '한국',
      US: '미국',
      CRYPTO: '가상자산',
    },
  },
})
