import { defineCopy } from '@/lib/ui-copy/define'

export const pension = defineCopy({
  en: {
    title: 'Pension',
    emphasis: 'Pension',
    subtitle: (asOf: string) =>
      `IRP and pension-savings accounts: value, contributions against the Korean tax-credit limit, and the US tax review. Portfolio data as of ${asOf}.`,
    empty: 'No pension accounts in the database yet.',
    wrappers: { irp: 'IRP', pension_savings: 'Pension savings' } as Record<string, string>,
    value: 'Value',
    cost: 'Cost (contributions)',
    return: 'Return',
    snapshotAsOf: (date: string) => `Snapshot as of ${date}`,
    snapshotNote: 'Funds and cash are valued from the snapshot and do not move until the next one. ETFs are re-priced daily.',
    holdings: 'Holdings',
    kinds: { ETF: 'ETF', FUND: 'Fund', CASH: 'Cash' } as Record<string, string>,
    columns: { name: 'Name', kind: 'Type', value: 'Value', cost: 'Cost', asOf: 'Valued as of' },
    priced: "Today's price",
    atCost: (date: string) => `At cost, ${date}`,
    contributions: 'Contributions by year',
    contributionsInfo:
      'Own contributions across IRP and pension savings against the combined credit limit, and pension savings alone against its own limit. The limits come from tax-policy.json. Employer contributions never count toward the credit.',
    contributionColumns: {
      year: 'Year',
      irp: 'IRP (own)',
      pensionSavings: 'Pension savings (own)',
      pensionSavingsLimit: 'Pension savings limit',
      combined: 'Combined (own)',
      combinedLimit: 'Combined limit',
      eligible: 'Credit-eligible',
      employer: 'Employer (IRP)',
    },
    over: 'Over',
    noLimit: 'No limit in the policy for this year',
    employerUnknown: 'Not in the evidence',
    noContributions: 'No contributions on file.',
    none: '—',
  },
  ko: {
    title: '연금',
    emphasis: '연금',
    subtitle: (asOf: string) =>
      `IRP와 연금저축 계좌: 평가액, 세액공제 한도 대비 납입액, 미국 세금 검토. 포트폴리오 기준일: ${asOf}.`,
    empty: '아직 DB에 연금 계좌가 없습니다.',
    wrappers: { irp: 'IRP', pension_savings: '연금저축' } as Record<string, string>,
    value: '평가액',
    cost: '원금 (납입액)',
    return: '수익률',
    snapshotAsOf: (date: string) => `${date} snapshot 기준`,
    snapshotNote: '펀드와 현금은 snapshot 금액이며 다음 snapshot까지 바뀌지 않습니다. ETF는 매일 시세로 다시 평가합니다.',
    holdings: '보유 상품',
    kinds: { ETF: 'ETF', FUND: '펀드', CASH: '현금' } as Record<string, string>,
    columns: { name: '상품명', kind: '유형', value: '평가액', cost: '원금', asOf: '평가 기준일' },
    priced: '오늘 시세',
    atCost: (date: string) => `원금 기준, ${date}`,
    contributions: '연도별 납입액',
    contributionsInfo:
      'IRP와 연금저축 본인 납입 합계를 합산 공제 한도와, 연금저축 납입만 연금저축 한도와 비교합니다. 한도는 tax-policy.json에서 읽습니다. 회사 부담금은 세액공제 대상이 아닙니다.',
    contributionColumns: {
      year: '연도',
      irp: 'IRP (본인)',
      pensionSavings: '연금저축 (본인)',
      pensionSavingsLimit: '연금저축 한도',
      combined: '합계 (본인)',
      combinedLimit: '합산 한도',
      eligible: '공제 대상',
      employer: '회사 부담금 (IRP)',
    },
    over: '초과',
    noLimit: '정책에 해당 연도 한도가 없습니다',
    employerUnknown: '증빙에 없음',
    noContributions: '납입 기록이 없습니다.',
    none: '—',
  },
})
