import { defineCopy } from '@/lib/ui-copy/define'

export const positionDetail = defineCopy({
  en: {
    eyebrow: (market: string) => `${market} holding`,
    subtitle: (accounts: string, lots: string, transactions: string) =>
      `${accounts} accounts · ${lots} open tax lots · ${transactions} transactions`,
    backToHoldings: 'Back to holdings',
    freshness: 'Valuation Data Freshness',
    firstChecks: 'First Checks',
    firstChecksInfo: "Summarizes whether this position's quantity, cost basis, and evidence agree.",
    reconciliationStatus: 'Reconciliation status',
    evidenceLinks: 'Evidence links',
    activityCoverage: 'Activity coverage',
    marketValue: 'Market Value',
    positionHeadline: 'Position headline',
    marketValueInfo:
      "Current position value in the position's native currency. Use this as the position-level headline before checking cost basis or gain/loss.",
    costBasis: 'Cost Basis',
    unrealized: 'Unrealized G/L',
    baseUnrealized: 'Base Unrealized G/L',
    coverage: 'Position Coverage',
    coverageInfo: 'Quantity, income, and row coverage for this single position.',
    quantity: 'Quantity',
    dividends: 'Dividends',
    reconciliation: 'Reconciliation',
    openQuantity: 'Open quantity',
    baseCost: 'Base cost',
    holdings: 'Holdings',
    taxLots: 'Tax lots',
    difference: 'Difference',
    matched: 'Matched',
    needsReview: 'Needs review',
    holdingMix: 'Holding-Period Mix',
    holdingMixInfo: 'Splits quantity into long-term and short-term buckets for tax review.',
    longQuantity: 'Long-term quantity',
    shortQuantity: 'Short-term quantity',
    longShortLots: 'Long / short tax-lot count',
    transactionMix: 'Transaction mix',
    accountHoldings: 'Account holdings',
    accountLotProfile: 'Account lot profile',
    activityTimeline: 'Activity timeline',
    evidenceSummary: 'Source evidence summary',
    lineage: 'Technical lineage',
    taxPreview: 'Tax realization preview',
    openTaxLots: 'Open tax lots',
    transactions: 'Transactions',
    noTransactions: 'No ticker-level transactions',
    noActivity: 'No dated activity for this ticker',
    noTaxPreview: 'No tax-lot sale preview available',
    noOpenLots: 'No open tax lots for this ticker',
    noDividends: 'No dividend rows for this ticker',
    noValue: 'No value',
    openPlanner: 'Open planner',
    eventKinds: { Dividend: 'Dividend', 'Tax lot': 'Tax lot', Buy: 'Buy', Sell: 'Sell' } as Record<string, string>,
    columns: {
      broker: 'Broker',
      account: 'Account',
      quantity: 'Qty',
      cost: 'Cost',
      market: 'Market',
      gainLoss: 'G/L',
      lots: 'Lots',
      long: 'LT',
      short: 'ST',
      lotCost: 'Lot Cost',
      status: 'Status',
      file: 'File / source',
      usage: 'Usage',
      rows: 'Rows',
      modified: 'Modified',
      source: 'Source',
      sha: 'SHA',
      acquired: 'Acquired',
      term: 'Term',
      proceeds: 'Proceeds',
      baseGainLoss: 'Base G/L',
      estimatedTax: 'Est. Tax',
      baseCost: 'Base Cost',
      date: 'Date',
      type: 'Type',
      amount: 'Amount',
      unit: 'Unit',
      page: 'Page',
      tax: 'Tax',
      baseAmount: 'Base Amount',
    },
  },
  ko: {
    eyebrow: (market: string) => `${market} 보유`,
    subtitle: (accounts: string, lots: string, transactions: string) =>
      `계좌 ${accounts}개 · 미결제 세금 단위 ${lots}개 · 거래 ${transactions}건`,
    backToHoldings: '보유종목으로 돌아가기',
    freshness: '평가 데이터 신선도',
    firstChecks: '먼저 확인할 것',
    firstChecksInfo: '이 종목의 수량·취득원가·증빙이 서로 맞는지 요약합니다.',
    reconciliationStatus: '정합성 상태',
    evidenceLinks: '증빙 연결',
    activityCoverage: '활동 반영 범위',
    marketValue: '평가금액',
    positionHeadline: '종목 대표값',
    marketValueInfo: '해당 종목의 거래 통화 기준 현재 평가금액입니다. 취득원가나 손익을 보기 전에 이 값을 종목 대표값으로 삼으세요.',
    costBasis: '취득원가',
    unrealized: '평가손익',
    baseUnrealized: '원화 평가손익',
    coverage: '종목 반영 범위',
    coverageInfo: '이 종목 하나에 대한 수량·수익·행 반영 범위입니다.',
    quantity: '수량',
    dividends: '배당',
    reconciliation: '정합성 확인',
    openQuantity: '미결제 수량',
    baseCost: '원화 취득원가',
    holdings: '보유종목',
    taxLots: '세금 단위',
    difference: '차이',
    matched: '일치',
    needsReview: '확인 필요',
    holdingMix: '보유기간 구성',
    holdingMixInfo: '세금 검토를 위해 수량을 장기·단기로 나눕니다.',
    longQuantity: '장기 수량',
    shortQuantity: '단기 수량',
    longShortLots: '장기 / 단기 세금 단위 수',
    transactionMix: '거래 구성',
    accountHoldings: '계좌별 보유',
    accountLotProfile: '계좌별 단위 구성',
    activityTimeline: '활동 이력',
    evidenceSummary: '원본 증빙 요약',
    lineage: '기술 계보',
    taxPreview: '세금 실현 미리보기',
    openTaxLots: '미결제 세금 단위',
    transactions: '거래 내역',
    noTransactions: '이 종목의 거래 행이 없습니다',
    noActivity: '이 종목의 날짜별 활동이 없습니다',
    noTaxPreview: '세금 단위 매도 미리보기를 만들 수 없습니다',
    noOpenLots: '이 종목의 미결제 세금 단위가 없습니다',
    noDividends: '이 종목의 배당 행이 없습니다',
    noValue: '값 없음',
    openPlanner: '세금 계획 열기',
    eventKinds: { Dividend: '배당', 'Tax lot': '세금 단위', Buy: '매수', Sell: '매도' } as Record<string, string>,
    columns: {
      broker: '증권사',
      account: '계좌',
      quantity: '수량',
      cost: '취득원가',
      market: '평가금액',
      gainLoss: '손익',
      lots: '단위',
      long: '장기',
      short: '단기',
      lotCost: '단위 원가',
      status: '상태',
      file: '파일 / 원본',
      usage: '용도',
      rows: '행 수',
      modified: '수정일',
      source: '원본',
      sha: 'SHA',
      acquired: '취득일',
      term: '과세 구분',
      proceeds: '매도금액',
      baseGainLoss: '원화 손익',
      estimatedTax: '예상 세금',
      baseCost: '원화 취득원가',
      date: '거래일',
      type: '유형',
      amount: '금액',
      unit: '단가',
      page: '페이지',
      tax: '원천징수',
      baseAmount: '원화 환산',
    },
  },
})
