import { defineCopy } from '@/lib/ui-copy/define'

export const rebalance = defineCopy({
  en: {
    eyebrow: 'Portfolio',
    title: 'Rebalancing',
    emphasis: 'Rebalancing',
    subtitle: (targets: string, cap: string) => `Policy baseline: ${targets} with ${cap}% single-position cap.`,
    freshnessIssues: (count: number) => `${count} freshness issue(s)`,
    inputsReady: 'Inputs ready',
    largestMarketGap: 'Largest Market Gap',
    primarySignal: 'Primary rebalance signal',
    marketGapHint: 'Compared with the configured market target policy',
    baseMarketValue: 'Base Market Value',
    baseMarketValueHint: 'Current priced portfolio value',
    reduceCandidates: 'Reduce Candidates',
    reduceCandidatesHint: 'Positions above cap',
    watchBeforeAction: 'Watch Before Action',
    watchBeforeActionHint: 'Valuation or freshness blockers',
    executionRisk: 'Execution Risk',
    executionRiskInfo: 'Tax and data-quality flags that should be checked before turning a rebalance signal into an action.',
    taxSensitive: 'Tax-Sensitive',
    taxSensitiveHint: 'High short-term exposure rows',
    freshnessIssuesLabel: 'Freshness Issues',
    freshnessIssuesHint: 'Operational inputs to refresh',
    decisionOrder: 'Decision order: market gap, cap excess, tax sensitivity, then data readiness.',
    marketTargetGaps: 'Market target gaps',
    addContext: 'Add context',
    noMarketAddGap: 'No market-level add gap',
    underTarget: 'under target',
    gap: 'gap',
    existingPositions: (count: string) => `${count} existing positions`,
    outsidePolicy: 'Outside the policy',
    everyMarketTargeted: 'Every market held has a target',
    ofPortfolioNoTarget: (pctValue: string) => `${pctValue} of the portfolio · no target set`,
    outsidePolicyNote: (markets: string) =>
      `Held but not covered by the market policy above, so excluded from its gaps — the ${markets} split is measured between those markets only. Single-position caps still apply here.`,
    executionGuardrails: 'Execution guardrails',
    marketGapTolerance: 'Market gap tolerance',
    singlePositionCap: 'Single-position cap',
    shortTermWarning: 'Short-term warning',
    guardrailNote: 'This page surfaces sizing gaps and risk flags only. Check lots, source lineage, and freshness before making any trade decision.',
    noPositionAboveCap: 'No position exceeds the cap',
    taxSensitiveWatchlist: 'Tax-sensitive watchlist',
    noHighShortTerm: 'No high short-term exposure rows',
    holdWatch: 'Hold / watch before action',
    noBlockers: 'No valuation or freshness blockers',
    staleInputs: (count: number) => `${count} stale, drifted, or missing operational input(s)`,
    openHealth: 'Open Health',
    columns: {
      market: 'Market',
      current: 'Current',
      target: 'Target',
      gap: 'Gap',
      action: 'Action',
      position: 'Position',
      currentPct: 'Current %',
      overCap: 'Over Cap',
      gapValue: 'Gap Value',
      baseGl: 'Base G/L',
      shortPct: 'Short %',
      baseMarket: 'Base Market',
      shortQty: 'Short Qty',
      reason: 'Reason',
      baseCost: 'Base Cost',
      nativeCost: 'Native Cost',
    },
  },
  ko: {
    eyebrow: '포트폴리오',
    title: '리밸런싱',
    emphasis: '리밸런싱',
    subtitle: (targets: string, cap: string) => `정책 기준: ${targets}, 단일 종목 상한 ${cap}%.`,
    freshnessIssues: (count: number) => `최신성 이슈 ${count}건`,
    inputsReady: '입력값 준비 완료',
    largestMarketGap: '가장 큰 시장 비중 차이',
    primarySignal: '주요 리밸런싱 신호',
    marketGapHint: '설정된 시장 목표 비중과 비교한 값',
    baseMarketValue: '원화 기준 평가금액',
    baseMarketValueHint: '가격이 확인된 현재 포트폴리오 평가금액',
    reduceCandidates: '축소 후보',
    reduceCandidatesHint: '상한을 넘은 종목',
    watchBeforeAction: '실행 전 관찰',
    watchBeforeActionHint: '평가금액 또는 최신성 확인 항목',
    executionRisk: '실행 리스크',
    executionRiskInfo: '리밸런싱 신호를 실제 행동으로 옮기기 전에 확인해야 하는 세금 및 데이터 품질 플래그입니다.',
    taxSensitive: '세금 민감',
    taxSensitiveHint: '단기 보유 비중이 높은 행',
    freshnessIssuesLabel: '최신성 이슈',
    freshnessIssuesHint: '갱신이 필요한 운영 입력값',
    decisionOrder: '판단 순서: 시장 비중 차이, 종목 상한 초과, 세금 민감도, 데이터 준비 상태 순으로 확인합니다.',
    marketTargetGaps: '시장 목표 차이',
    addContext: '추가 매수 맥락',
    noMarketAddGap: '시장 단위 추가 매수 차이가 없습니다.',
    underTarget: '목표보다 부족',
    gap: '차이',
    existingPositions: (count: string) => `기존 종목 ${count}개`,
    outsidePolicy: '정책 밖 보유',
    everyMarketTargeted: '보유 중인 모든 시장에 목표가 있습니다.',
    ofPortfolioNoTarget: (pctValue: string) => `포트폴리오의 ${pctValue} · 목표 없음`,
    outsidePolicyNote: (markets: string) =>
      `보유 중이지만 위 시장 정책에는 포함되지 않아 차이 계산에서 제외됩니다. ${markets} 비중은 해당 시장들 사이에서만 계산됩니다. 단일 종목 상한은 여기에도 적용됩니다.`,
    executionGuardrails: '실행 가드레일',
    marketGapTolerance: '시장 차이 허용 범위',
    singlePositionCap: '단일 종목 상한',
    shortTermWarning: '단기 보유 경고',
    guardrailNote: '이 화면은 비중 차이와 리스크 플래그만 보여줍니다. 실제 거래 판단 전 세금 단위, 원본 이력, 최신성을 확인해야 합니다.',
    noPositionAboveCap: '상한을 넘은 종목이 없습니다.',
    taxSensitiveWatchlist: '세금 민감 관찰 목록',
    noHighShortTerm: '단기 보유 비중이 높은 행이 없습니다.',
    holdWatch: '실행 전 보류 / 관찰',
    noBlockers: '평가금액 또는 최신성 차단 항목이 없습니다.',
    staleInputs: (count: number) => `오래되었거나 변경되었거나 누락된 운영 입력값 ${count}건`,
    openHealth: '데이터 상태 열기',
    columns: {
      market: '시장',
      current: '현재',
      target: '목표',
      gap: '차이',
      action: '조치',
      position: '종목',
      currentPct: '현재 %',
      overCap: '상한 초과',
      gapValue: '차이 금액',
      baseGl: '원화 손익',
      shortPct: '단기 %',
      baseMarket: '원화 평가금액',
      shortQty: '단기 수량',
      reason: '이유',
      baseCost: '원화 취득원가',
      nativeCost: '현지 통화 원가',
    },
  },
})
