import { defineCopy } from '@/lib/ui-copy/define'

export const reconciliation = defineCopy({
  en: {
    eyebrow: 'System',
    title: 'Reconciliation',
    emphasis: 'Reconciliation',
    subtitle: 'Check holdings, tax lots, valuation coverage, and source readiness from the latest ingest.',
    reviewItems: (count: string) => `${count} confirmed discrepancy(ies)`,
    reconciled: 'Reconciled',
    reviewItemsTitle: 'Confirmed Discrepancies',
    reviewItemsInfo: 'Confirmed differences between holdings, tax lots, and valuation data. Informational income coverage is shown separately.',
    headline: 'Reconciliation headline',
    queuedHint: 'Items queued for review',
    noActionsHint: 'No reconciliation actions queued',
    positions: 'Positions',
    markets: (count: string) => `${count} markets`,
    tickerlessIncome: 'Informational Income Rows',
    tickerlessHint: 'Cash income that does not need a security ticker',
    sourceIssues: 'Source Issues',
    sourceIssuesHint: 'Freshness or validation issues',
    coverageScope: 'Coverage Scope',
    coverageScopeInfo: 'The source coverage represented in the reconciliation run.',
    brokerages: 'Brokerages',
    marketsCovered: (count: string) => `${count} markets covered`,
    lotPositions: 'Lot Positions',
    lotPositionsHint: 'Positions represented by tax lots',
    readOrder: 'Read order: queued findings first, then source coverage and detailed break tables.',
    actionQueue: 'Action queue',
    noQueuedActions: 'No reconciliation actions queued',
    marketCoverage: 'Market and brokerage coverage',
    positionBreaks: 'Holdings vs tax lots breaks',
    noPositionBreaks: 'No holdings-to-lots breaks above the current tolerance',
    incomeBreaks: 'Tickerless income coverage',
    allIncomeMapped: 'All income rows are linked to a ticker',
    valuationBreaks: 'Missing valuation breaks',
    allValued: 'All holdings have market valuation',
    view: 'View',
    columns: {
      priority: 'Priority',
      area: 'Area',
      count: 'Count',
      action: 'Action',
      open: 'Open',
      market: 'Market',
      brokerage: 'Brokerage',
      holdings: 'Holdings',
      lotPos: 'Lot Pos.',
      lotRows: 'Lot Rows',
      txRows: 'Tx Rows',
      incomeRows: 'Income Rows',
      holdingCost: 'Holding Cost',
      lotCost: 'Lot Cost',
      status: 'Status',
      position: 'Position',
      holdingQty: 'Holding Qty',
      lotQty: 'Lot Qty',
      qtyDiff: 'Qty Diff',
      costDiff: 'Cost Diff',
      category: 'Category',
      rows: 'Rows',
      baseIncome: 'Base Income',
      nativeCost: 'Native Cost',
      baseCost: 'Base Cost',
    },
  },
  ko: {
    eyebrow: '시스템',
    title: '데이터 일치 확인',
    emphasis: '일치 확인',
    subtitle: '마지막 ingest 기준 보유종목, 세금 단위, 평가금액, 원본 상태 사이의 실제 차이를 확인합니다.',
    reviewItems: (count: string) => `확정 불일치 ${count}건`,
    reconciled: '일치 확인 완료',
    reviewItemsTitle: '확정 불일치',
    reviewItemsInfo: '보유종목·세금 단위·평가금액 사이에서 실제로 확인된 차이입니다. 종목 연결이 불필요한 현금성 수익은 별도 현황으로 표시합니다.',
    headline: '일치 확인 핵심 지표',
    queuedHint: '검토 대기 항목',
    noActionsHint: '대기 중인 일치 확인 작업 없음',
    positions: '종목',
    markets: (count: string) => `${count}개 시장`,
    tickerlessIncome: '정보성 수익 행',
    tickerlessHint: '종목 연결이 필요하지 않은 현금성 수익 행',
    sourceIssues: '원본 이슈',
    sourceIssuesHint: '최신성 또는 검증 이슈',
    coverageScope: '범위',
    coverageScopeInfo: '일치 확인 실행에 포함된 원본 범위입니다.',
    brokerages: '증권사',
    marketsCovered: (count: string) => `${count}개 시장 포함`,
    lotPositions: '세금 단위 종목',
    lotPositionsHint: '세금 단위로 표현된 종목',
    readOrder: '읽는 순서: 확정 불일치, 원본 범위, 정보성 수익 현황 순으로 확인합니다.',
    actionQueue: '작업 대기열',
    noQueuedActions: '대기 중인 일치 확인 작업이 없습니다.',
    marketCoverage: '시장 및 증권사 범위',
    positionBreaks: '보유종목 vs 세금 단위 차이',
    noPositionBreaks: '현재 허용 범위를 넘는 보유종목-세금 단위 차이가 없습니다.',
    incomeBreaks: '종목 미연결 수익 차이',
    allIncomeMapped: '모든 수익 행이 종목에 연결되어 있습니다.',
    valuationBreaks: '평가금액 누락',
    allValued: '모든 보유종목에 평가금액이 있습니다.',
    view: '보기',
    columns: {
      priority: '우선순위',
      area: '영역',
      count: '건수',
      action: '조치',
      open: '열기',
      market: '시장',
      brokerage: '증권사',
      holdings: '보유',
      lotPos: '세금 단위 종목',
      lotRows: '세금 단위 행',
      txRows: '거래 행',
      incomeRows: '수익 행',
      holdingCost: '보유 원가',
      lotCost: '세금 단위 원가',
      status: '상태',
      position: '종목',
      holdingQty: '보유 수량',
      lotQty: '세금 단위 수량',
      qtyDiff: '수량 차이',
      costDiff: '원가 차이',
      category: '분류',
      rows: '행',
      baseIncome: '원화 수익',
      nativeCost: '현지 통화 원가',
      baseCost: '원화 원가',
    },
  },
})
