import { defineCopy } from '@/lib/ui-copy/define'

export const review = defineCopy({
  en: {
    eyebrow: 'Portfolio',
    title: 'Portfolio Review',
    emphasis: 'Review',
    subtitle: 'A global review surface for concentration, winners, losers, short-term exposure, and operational readiness.',
    freshnessIssues: (count: number) => `${count} freshness issue(s)`,
    ready: 'Ready',
    baseMarketValue: 'Base Market Value',
    baseMarketValueInfo: 'Current portfolio value converted to KRW. Use this as the review page headline before checking concentration or data readiness.',
    reviewHeadline: 'Review headline',
    globalValueHint: 'Global value across priced positions',
    unrealizedGl: 'Unrealized G/L',
    top5Concentration: 'Top 5 Concentration',
    concentrationHint: 'Cost-basis concentration',
    freshnessIssuesLabel: 'Freshness Issues',
    inputsNeedingReview: 'Inputs needing review',
    reviewScope: 'Review Scope',
    reviewScopeInfo: 'The size of the review universe and the split between positions with positive and negative unrealized gain/loss.',
    positions: 'Positions',
    accounts: (count: string) => `${count} accounts`,
    positiveNegative: 'Positive / Negative',
    positionsByResult: 'Positions by unrealized result',
    readOrder: 'Review order: value first, then concentration, freshness, and outliers.',
    marketSummary: 'Market-aware summary',
    positionCount: (count: string) => `${count} positions`,
    concentration: 'Concentration',
    operationalReadiness: 'Operational readiness',
    noOperationalInputs: 'No stale, drifted, or missing inputs',
    largestPositions: 'Largest positions',
    topGains: 'Top unrealized gains',
    topLosses: 'Top unrealized losses',
    shortTermHeavy: 'Short-term-heavy positions',
    missingMarketValue: 'Positions missing market value',
    noRows: 'No rows',
    columns: {
      position: 'Position',
      accounts: 'Accts',
      quantity: 'Qty',
      market: 'Market',
      baseMarket: 'Base Market',
      shortPct: 'Short %',
      baseGl: 'Base G/L',
      lots: 'Lots',
      glPct: 'G/L %',
    },
  },
  ko: {
    eyebrow: '포트폴리오',
    title: '포트폴리오 검토',
    emphasis: '검토',
    subtitle: '집중도, 수익/손실 종목, 단기 보유 비중, 운영 준비 상태를 한 화면에서 확인합니다.',
    freshnessIssues: (count: number) => `최신성 이슈 ${count}건`,
    ready: '준비 완료',
    baseMarketValue: '원화 기준 평가금액',
    baseMarketValueInfo: '현재 포트폴리오 평가금액을 원화로 환산한 값입니다. 집중도나 데이터 준비 상태를 보기 전 먼저 확인합니다.',
    reviewHeadline: '검토 핵심 지표',
    globalValueHint: '가격이 확인된 종목의 전체 평가금액',
    unrealizedGl: '평가손익',
    top5Concentration: '상위 5개 집중도',
    concentrationHint: '취득원가 기준 집중도',
    freshnessIssuesLabel: '최신성 이슈',
    inputsNeedingReview: '확인이 필요한 입력값',
    reviewScope: '검토 범위',
    reviewScopeInfo: '검토 대상 규모와 평가손익이 양수/음수인 종목 분포입니다.',
    positions: '종목',
    accounts: (count: string) => `${count}개 계좌`,
    positiveNegative: '수익 / 손실',
    positionsByResult: '평가손익 기준 종목 수',
    readOrder: '읽는 순서: 평가금액, 집중도, 최신성, 이상치 순으로 확인합니다.',
    marketSummary: '시장별 요약',
    positionCount: (count: string) => `${count}개 종목`,
    concentration: '집중도',
    operationalReadiness: '운영 준비 상태',
    noOperationalInputs: '오래되었거나 변경되었거나 누락된 입력값이 없습니다.',
    largestPositions: '평가금액 상위 종목',
    topGains: '평가이익 상위 종목',
    topLosses: '평가손실 상위 종목',
    shortTermHeavy: '단기 보유 비중 높은 종목',
    missingMarketValue: '평가금액 누락 종목',
    noRows: '표시할 행이 없습니다.',
    columns: {
      position: '종목',
      accounts: '계좌',
      quantity: '수량',
      market: '시장',
      baseMarket: '원화 평가금액',
      shortPct: '단기 %',
      baseGl: '원화 손익',
      lots: '세금 단위',
      glPct: '손익 %',
    },
  },
})
