import { defineCopy } from '@/lib/ui-copy/define'

export const taxPlanning = defineCopy({
  en: {
    page: {
      eyebrow: 'Tax',
      title: 'Tax Planning',
      emphasis: 'Planning',
      subtitle: 'Compare Korea and US stock sale timing across multiple years. Results are review estimates, not tax filing advice.',
      usingExampleAssumptions: 'Using example assumptions',
      editAssumptions: 'Edit assumptions',
      openStaticOpportunityAnalysis: 'Open static opportunity analysis',
      annualFilingProfile: 'Annual filing profile',
      annualFilingProfileInfo: "Filing flags track whether that country needs reporting work in a year. Tax calc flags decide whether that country's tax estimate is included in planning math.",
      baseAssumptions: 'Base assumptions',
      annualTargetScenarioComparison: 'Annual target scenario comparison',
      selectedSingleYearTaxSplit: 'Selected single-year tax split',
      warnings: 'Warnings',
      recommendedSaleLotSequence: 'Recommended sale-lot sequence',
      allOpenLotCandidates: 'All open lot candidates',
      year: 'Year',
      taxCalc: 'Tax calc',
      projectedWages: 'Projected wages',
      projectedWagesInfo: 'W-2 base wages grown by the annual income-growth assumption. This is not projected taxable income.',
      usFiling: 'US filing',
      usFilingInfo: "Whether this year needs US tax reporting workflow and evidence review. This does not by itself change the planner's tax math.",
      krFiling: 'KR filing',
      krFilingInfo: "Whether this year needs Korea tax reporting workflow and evidence review. This does not by itself change the planner's tax math.",
      status: 'Status',
      required: 'Required',
      off: 'Off',
      scenario: 'Scenario',
      filingState: 'Filing / state',
      w2WageBase: 'W-2 wage base',
      annualIncomeGrowth: 'Annual income growth',
      federalMethod: 'Federal method',
      federalMethodValue: '2026 MFJ progressive',
      fallbackShortLong: 'Fallback ST / LT',
      fallbackStateNiit: 'Fallback state / NIIT',
      ytdCarryovers: 'YTD realized / carryovers',
      krStockDeduction: 'KR stock deduction',
      krForeignStockRate: 'KR foreign stock rate',
      creditModel: 'Credit model',
      annualTargetInfo: 'These rows compare how to satisfy the same annual KRW sale target across the planning horizon. They do not model whether Korea or the US return is filed first within the same year.',
      annualTargetNote: 'Each row uses the same annual test amount, then changes which market is sold first. Read this only after choosing a rough yearly sale range from the Opportunity map.',
      totalSales: 'Total sales',
      realizedGainLoss: 'Realized G/L',
      estimatedTax: 'Est. tax',
      afterTaxCash: 'After tax cash',
      peakYearTax: 'Peak year tax',
      lotsUsed: 'Lots used',
      lowestTax: 'Lowest tax',
      sameTax: 'Same tax',
      annualTargetHidden: 'This comparison is hidden until an annual test amount is entered. Without a repeated yearly sale amount, labels like lowest tax or same tax are not decision-grade because the planner has not been asked to satisfy a concrete sale range.',
      annualTargetHiddenHint: 'Use the Opportunity map first to find promising years and markets, then enter a KRW amount above to compare execution scenarios.',
      singleYearTaxSplitInfo: 'This is the tax estimate for the currently selected lot sequence, not the full portfolio. Federal and California amounts are incremental tax above projected wage income.',
      federalShortTerm: 'Federal short-term',
      federalLongTerm: 'Federal long-term',
      niit: 'NIIT',
      californiaState: 'California / state',
      usGrossEstimate: 'US gross estimate',
      krGrossTax: 'KR gross tax',
      usFtcLimitUsed: 'US FTC limit / used',
      krCreditUsed: 'KR credit used',
      combinedAfterCredit: 'Combined after credit',
      afterTaxProceeds: 'After-tax proceeds',
      method: 'Method',
      methodNote: (method: string) => `Method: ${method}. FTC is applied only in the selected credit mode; source and treaty percentages remain manual inputs.`,
      noPlannerWarnings: 'No planner warnings',
      inputs: 'Inputs',
      resolveFreshness: (count: string) => `Resolve ${count} freshness issue(s) before trading.`,
      review: 'Review',
    },
    settings: {
      title: 'Plan Settings',
      subtitle: 'Choose sale-timing rules and date ranges, then recalculate the plan.',
      badge: 'Calculated with current prices and FX',
      schedulingRule: 'Scheduling rule',
      schedulingRuleInfo: 'Choose the deterministic scheduling rule. Tax calculations remain rule-based; no market forecast or LLM judgment is applied here.',
      staged: 'Stage sales after long-term eligibility',
      earliestLongTerm: 'Sell at earliest long-term eligibility',
      waitUsOnly: 'Wait for US-only filing',
      accelerateLosses: 'Accelerate loss harvesting',
      schedulingHint: 'Controls when each tax lot first enters the schedule.',
      executionWindow: 'Execution window',
      executionWindowInfo: 'For the staged plan, divide current priced lot value across this many months. Other plans use their earliest permitted dates.',
      months: 'months',
      executionHint: 'Applies to staged plans.',
      taxHorizon: 'Tax horizon',
      years: 'years',
      horizonHint: 'Includes annual filing-profile changes.',
      rebuild: 'Rebuild plan',
    },
    candidateTable: {
      empty: 'No sale candidates with open tax lots',
      position: 'Position',
      account: 'Account',
      acquired: 'Acquired',
      term: 'Term',
      quantity: 'Qty',
      proceeds: 'Proceeds',
      baseGainLoss: 'Base G/L',
      grossLotTax: 'Gross Lot Tax',
      afterTax: 'After Tax',
      notAvailable: 'n/a',
    },
    overview: {
      title: 'Selected plan',
      info: 'This plan uses tax-lot acquisition dates, annual filing profiles, current prices, and current FX. It does not use a market forecast.',
      executionWindow: 'Recommended execution window',
      to: 'to',
      whyThisMatters: 'Why this matters',
      longTermTreatment: (pct: string) => `${pct}% of planned proceeds receive long-term treatment under this schedule.`,
      plannedSales: 'Planned sales',
      pricedLots: (count: string) => `${count} priced lots`,
      estimatedTax: 'Estimated tax',
      longTermPct: (pct: string) => `${pct}% long-term`,
      afterTaxCash: 'After-tax cash',
      saleInstructions: (count: string) => `${count} sale instructions`,
      inputCoverage: 'Input coverage',
      inputCoverageInfo: 'How much of the current holdings value can be connected to priced tax lots for planning.',
      coverageHint: (issues: string, unpriced: string) => `${issues} issues · ${unpriced} unpriced`,
      reviewInputRange: 'Review the input range.',
      coverageWarning: 'The planned amount is greater than the current holding market value, so coverage exceeds 100%. Check for duplicate tax lots or stale prices before using the result.',
      lotsStillWaiting: 'Lots still waiting',
      waitingLots: (lots: string, amount: string, next: string | null) => `${lots} lots representing ${amount} have not crossed one year.${next ? ` Next: ${next}.` : ''}`,
      estimatedTermBenefit: 'Estimated term benefit',
      termBenefit: (amount: string) => `Waiting for long-term treatment avoids an estimated ${amount} of federal rate difference on currently profitable short-term lots.`,
      waitingUntil2028: 'Waiting until 2028',
      saving: 'saving',
      extraTax: 'extra tax',
      waitUntil2028: (label: string, amount: string, duration: string, earliest: string, wait: string) => `Estimated ${label}: ${amount}, for about ${duration} more waiting. KR top-up changes from ${earliest} to ${wait}.`,
    },
    comparison: {
      title: 'Plan comparison',
      info: 'Every row sells the same currently priced lots. Only timing and holding-term treatment change.',
      lowestEstimatedTax: 'Lowest estimated tax',
      scale: 'Tax bars share one scale. Shorter is lower.',
      selected: 'Selected',
      lowestTax: 'Lowest tax',
      estimatedTax: 'Estimated tax',
      earliestBaseline: 'Earliest baseline',
      less: (amount: string) => `${amount} less`,
      more: (amount: string) => `${amount} more`,
      execution: 'Execution',
      to: 'to',
      longTermSales: 'Long-term sales',
      averageWait: 'Average wait',
      krTopUp: 'KR top-up',
    },
    savedPlans: {
      title: 'Saved execution plans',
      info: 'Saving creates an immutable calculation snapshot. Review and execution states are recorded separately from the original tax estimate.',
      recent: (count: string) => `${count} recent`,
      saveCurrentCalculation: 'Save current calculation',
      saveDescription: 'Freeze the selected strategy, quantities, dates, tax assumptions, and lot-level instructions before review.',
      planName: 'Plan name',
      placeholder: 'e.g. 2026 staged baseline',
      saveAsDraft: 'Save as draft',
      storageNote: 'Stored locally in an ignored private JSON file; it is not committed to the public repository.',
      execution: 'Execution',
      planned: 'planned',
      executed: (done: string, total: string) => `${done} / ${total} executed`,
      empty: 'No saved plans yet. Save the current calculation when it is ready for review.',
    },
    savedPlanDetail: {
      eyebrow: 'Tax · Saved plan',
      subtitle: (date: string, revision: string | number) => `Immutable calculation snapshot from ${date} · revision ${revision}`,
      backToPlanner: 'Back to planner',
      executionOverview: 'Execution overview',
      executionOverviewInfo: 'The tax calculation snapshot stays unchanged. Review and execution updates are recorded separately so the original plan remains auditable.',
      plannedSales: 'Planned sales',
      estimatedTax: 'Estimated tax',
      instructions: 'Instructions',
      complete: 'Complete',
      executed: 'executed',
      reviewed: 'reviewed',
      planned: 'planned',
      skipped: 'skipped',
      actualProceeds: 'actual proceeds',
      planStatus: 'Plan status',
      updateStatus: 'Update status',
      created: 'Created',
      updated: 'Updated',
      currentDataDrift: 'Current-data drift',
      currentDataDriftInfo: "This compares the saved immutable snapshot with a fresh calculation using today's holdings, prices, FX, and tax policy. It does not alter the saved plan.",
      reviewChanges: 'Review changes',
      noMaterialChange: 'No material change',
      noChange: 'No change',
      afterTaxCash: 'After-tax cash',
      driftSummary: (savedDate: string, liveDate: string, savedVersion: string | number, liveVersion: string | number) =>
        `Saved as of ${savedDate}; fresh calculation as of ${liveDate}. Tax policy version ${savedVersion} → ${liveVersion}.`,
      openFreshCalculation: 'Open fresh calculation',
      snapshotProvenance: 'Snapshot provenance',
      strategy: 'Strategy',
      executionWindow: 'Execution window',
      taxHorizon: 'Tax horizon',
      taxPolicy: 'Tax policy',
      months: 'months',
      years: 'years',
      version: 'version',
      statusLabels: {
        draft: 'Draft',
        reviewed: 'Reviewed',
        active: 'Active',
        completed: 'Completed',
        archived: 'Archived',
      },
    },
    timeline: {
      saleTimeline: 'Sale timeline',
      saleTimelineInfo: "Each column is one active sale month. Bar height shows planned proceeds relative to the busiest month; color shows whether that month's net result is a gain or loss.",
      activeMonths: (count: string) => `${count} active months`,
      executionSpan: 'Execution span',
      to: 'to',
      inspectHint: 'Select a month to inspect exact lots and quantities. Selection stays in place without reloading the page.',
      netGain: 'Net gain',
      netLoss: 'Net loss',
      saleTimelineAria: (year: string | number) => `${year} sale timeline`,
      plannedSalesAria: (label: string, amount: string) => `${label}: ${amount} planned sales`,
      positions: 'positions',
      instructions: (count: string) => `${count} instructions`,
      monthDetailHint: 'Exact sale lots for this month. Tax is netted at the annual level shown below.',
      page: 'Page',
      of: 'of',
      saleDate: 'Sale date',
      position: 'Position',
      account: 'Account',
      quantity: 'Quantity',
      purpose: 'Purpose',
      estimatedProceeds: 'Est. proceeds',
      estimatedGainLoss: 'Est. G/L',
      execution: 'Execution',
      longTermFrom: (date: string) => `LT from ${date}`,
      washSaleReview: 'Wash-sale review',
      washSaleReviewDetail: (count: string | number) => `Wash-sale review: ${count} same-ticker open-lot acquisition(s) in the configured window.`,
      lossOffset: 'Loss offset',
      gainSale: 'Gain sale',
      neutral: 'Neutral',
      actualsAndNote: 'Actuals and note',
      executedDate: 'Executed date',
      actualProceedsKrw: 'Actual proceeds KRW',
      actualGainLossKrw: 'Actual gain/loss KRW',
      actualGainOrLossKrw: 'Actual gain or loss KRW',
      executionNote: 'Execution note',
      save: 'Save',
      executionStatus: 'Execution status',
      plannedStatus: 'Planned',
      reviewedStatus: 'Reviewed',
      executedStatus: 'Executed',
      skippedStatus: 'Skipped',
      plannedSales: 'Planned sales',
      grossGains: 'Gross gains',
      pairedLosses: 'Paired losses',
      netGainLoss: 'Net gain / loss',
      showing: 'Showing',
      previous: 'Previous',
      next: 'Next',
      noScheduledSaleInstructions: 'No scheduled sale instructions',
      noProfile: 'No profile',
      usOnly: 'US only',
      krOnly: 'KR only',
    },
    annualTax: {
      title: 'Annual tax roll-up',
      info: 'The annual result nets scheduled gains and losses, stacks short-term gains on projected ordinary income, applies long-term brackets, NIIT and California tax, then applies only the configured cross-border credit model.',
      netTax: 'Net tax',
      sales: 'Sales',
      netGainLoss: 'Net G/L',
      usGross: 'US gross',
      krGross: 'KR gross',
      creditUsed: 'Credit used',
      afterTaxCash: 'After-tax cash',
      taxComponents: 'Tax components',
      taxYear: 'Tax year',
      profile: 'Profile',
      credit: 'Credit',
      federalShortTerm: 'Federal ST',
      federalLongTerm: 'Federal LT',
      niit: 'NIIT',
      california: 'California',
      usFtcLimit: 'US FTC limit',
      usFtcUsed: 'US FTC used',
      krCreditUsed: 'KR credit used',
    },
    opportunity: {
      timingSignal: 'Timing signal',
      timingSignalTitle: (amount: string) => `Deferring optional US-market gains may reduce tax by ${amount}`,
      timingSignalBody: (yearLabel: string, grossKrTax: string, credit: string, increment: string) =>
        `${yearLabel} has ${grossKrTax} of gross KR tax and ${credit} of estimated cross-border credit. The remaining KR increment is ${increment}.`,
      timingSignalAction: (yearLabel: string) =>
        `Compare executing optional gains in ${yearLabel}, after confirming the credit limitation and source treatment.`,
      timingSignalCaveat: (isExample: boolean) =>
        `The estimate uses only modeled US federal tax as the credit pool and excludes California and NIIT from that pool. Final creditability, FX, and Form 1116/Korean filing treatment require review.${isExample ? ' The deduction and rate are example defaults.' : ''}`,
      afterCreditMetric: (amount: string) => `${amount} after credit`,
      filingProfileOnly: 'Filing-profile only',
      filingProfileOnlyTitle: 'The filing-profile change alone shows ₩0 saving',
      filingProfileOnlyBody: (yearLabel: string, grossKrTax: string, credit: string, increment: string, combined: string, lowestYearLabel: string) =>
        `${yearLabel} gross KR tax is ${grossKrTax}, but the estimated credit is ${credit}. That leaves ${increment} of additional KR tax and ${combined} combined tax, the same modeled total as ${lowestYearLabel}.`,
      filingProfileOnlyAction: 'Do not treat this as a sell-now signal. A real timing decision must also roll each lot forward from short-term to long-term and model future prices and FX.',
      filingProfileOnlyCaveat: (isExample: boolean) =>
        `This static comparison freezes today's short/long buckets in every year. By 2028, current short-term lots may become long-term and reduce US federal tax, which can also change the Korea credit ceiling. US-listed gains are treated as US-source; California and NIIT are excluded from the credit pool.${isExample ? ' The rates are example defaults.' : ''}`,
      modeledSavingMetric: (amount: string) => `${amount} modeled saving`,
      potentialPairing: 'Potential pairing',
      potentialPairingTitle: 'Pair KR loss lots with US short-term gains in the same US tax year',
      potentialPairingBody: (krLoss: string, usGain: string, pairable: string) =>
        `The current screen shows ${krLoss} of KR short-term unrealized losses and ${usGain} of net US-market short-term gains. A screening match of up to ${pairable} could reduce the modeled US short-term gain.`,
      potentialPairingAction: 'When a US short-term gain sale is planned, review enough KR short-term loss lots in that same US tax year before choosing the exact tickers.',
      potentialPairingCaveat: (impact: string, ratePct: string) =>
        `The screening tax effect is up to ${impact} at the current ${ratePct}% assumption. A KRW loss is not automatically the US tax loss: USD tax basis, transaction-date FX, account eligibility, wash-sale rules, and other capital activity must be verified.`,
      gainToScreenMetric: (amount: string) => `${amount} gain to screen`,
      meaningOfNumber: 'Meaning of the number',
      meaningOfNumberTitle: (amount: string) => `${amount} is loss-lot proceeds, not a tax-free allowance`,
      meaningOfNumberBody: (proceeds: string, loss: string) =>
        `Selling the currently identified KR loss lots would produce about ${proceeds} of cash and realize about ${loss} of loss at today's values. Profitable KR lots are not included in that proceeds number.`,
      meaningOfNumberAction: 'Use the loss amount as offset inventory and the proceeds amount only for liquidity planning.',
      meaningOfNumberCaveat: 'US tax can still apply to profitable Korea-listed stock sales because US citizens and residents generally report worldwide income.',
      lossInventoryMetric: (amount: string) => `${amount} loss inventory`,
      currentDecision: 'Current decision',
      reviewTimingSignals: 'Review timing signals before choosing sales',
      noTaxDifference: 'No tax difference across timing choices',
      currentLowestTaxPath: (label: string) => `Current lowest-tax path: ${label}`,
      noPlanningTargetBody: 'The opportunity map separates gross timing differences, loss-pairing candidates, and jurisdiction estimates. Use those signals to choose a plausible annual range before testing exact sale amounts.',
      tiedTaxBody: 'Under the current assumptions, changing the market order does not change estimated tax. Focus on cash needs, exposure, and data issues before reading the lot table.',
      recommendationBody: 'Use the yearly action plan first. The lot table below is only the execution detail behind the selected market timing path.',
      explore: 'Explore',
      tie: 'Tie',
      recommendation: 'Recommendation',
      step1: 'Step 1',
      step1Body: 'Find timing signals and loss inventory',
      step2: 'Step 2',
      step2Body: 'Pick a tentative annual range',
      step3: 'Step 3',
      step3Body: 'Test that range against scenarios',
      openLots: 'Open Lots',
      openLotsHint: 'Available tax-lot rows',
      inputIssues: 'Input Issues',
      inputIssuesInfo: 'Data quality or freshness items that should be resolved before relying on planning output.',
      inputIssuesHint: 'Items to resolve before relying on output',
      annualTest: 'Annual Test',
      lossLotProceeds: 'Loss-Lot Proceeds',
      scenarioInputAmount: 'Scenario input amount',
      estimatedTax: 'Est. Tax',
      lossHarvest: 'Loss Harvest',
      modeledLossInventory: 'Modeled loss inventory',
      actionPlanTitle: 'Year-by-year action plan',
      opportunityMapTitle: 'Opportunity map',
      actionPlanInfo: 'This is the decision layer: which market to realize in each tax year. Specific lots are shown later as execution detail.',
      opportunityMapInfo: 'This exploration layer separates timing signals, loss inventory, and jurisdiction-level tax estimates before you commit to a target amount.',
      noPlanningOpportunities: 'No planning opportunities from current tax lots',
      stressTestNote: "This is a sell-all stress test for every currently priced open tax lot with an acquisition record. It is not quite the full holdings balance: positions without complete lot allocation are excluded from tax-term analysis. Each future year currently reuses today's price, FX, and short/long classification, so the table isolates filing-profile changes rather than forecasting an actual future sale. Gross country tax, estimated cross-border credit, and after-credit tax are shown separately.",
      fullHoldingsGl: 'Full holdings unrealized G/L',
      taxLotModeledGl: 'Tax-lot modeled G/L',
      unallocatedHoldingValue: 'Unallocated holding value',
      unmodeledGlDifference: 'Unmodeled G/L difference',
      whatToConsider: 'What to consider',
      years: 'Years',
      market: 'Market',
      taxProfile: 'Tax profile',
      taxProfileInfo: 'Which country tax calculations are enabled for that year. US_AND_KR means both US and Korea estimates are included.',
      netGainLoss: 'Net G/L',
      netGainLossInfo: 'Estimated gain or loss if every currently priced lot in this market were sold. This stress case is not a sale recommendation.',
      lossInventory: 'Loss inventory',
      lossInventoryInfo: 'Unrealized loss in the loss lots. The related sale proceeds are shown in the row detail; they are not a tax-free allowance.',
      usEstimate: 'US estimate',
      usEstimateInfo: 'US planning estimate after short-term and long-term netting. It uses KRW gains as a proxy; filing requires USD basis and transaction-date FX.',
      krEstimate: 'KR estimate',
      krEstimateInfo: 'Korea planning estimate after applicable loss netting and the configured annual deduction. Domestic listed-stock taxability follows Tax Settings.',
      beforeCredits: 'Before credits',
      beforeCreditsInfo: 'US plus Korea estimates before any foreign tax credit. Do not interpret this as final combined cash tax.',
      estimatedCredit: 'Est. credit',
      estimatedCreditInfo: 'Estimated Korea credit for modeled US federal tax attributable to US-market gains, capped at gross KR tax. California and NIIT are excluded from this credit pool.',
      afterCredit: 'After credit',
      afterCreditInfo: 'US estimate plus KR gross tax minus the estimated cross-border credit. This is still a planning estimate, not a filed credit calculation.',
      whyItMatters: 'Why it matters',
      whyItMattersInfo: 'The specific timing or jurisdiction implication to review before selecting individual lots.',
      rowReadoutUsKr: (krGross: string, credit: string, increment: string) => `KR gross ${krGross} - estimated credit ${credit} = ${increment} incremental KR tax.`,
      rowReadoutUsOnly: 'KR tax calc is off in this profile; the US estimate remains.',
      rowReadoutKrUs: 'US estimate still applies to Korea-listed gains under the worldwide-income assumption.',
      rowReadoutNone: 'No positive aggregate tax is modeled for this row.',
      rowDetail: (count: string, lossProceeds: string, totalProceeds: string) =>
        `${count} priced lots · loss-lot proceeds ${lossProceeds} · all-lot proceeds ${totalProceeds}`,
      year: 'Year',
      filingProfile: 'Filing profile',
      sellKrMarket: 'Sell KR market',
      sellUsMarket: 'Sell US market',
      target: 'Target',
      readout: 'Readout',
      mostlyKrSales: 'Mostly Korea-listed sales',
      mostlyUsSales: 'Mostly US-listed sales',
      mixedMarketSales: 'Mixed market sales',
      noPlannedSale: 'No planned sale',
      noAllocatedSaleLots: 'No allocated sale lots',
      tax: 'Tax',
    },
  },
  ko: {
    page: {
      eyebrow: '세금',
      title: '세금 계획',
      emphasis: '계획',
      subtitle: '한국/미국 주식 매도 시점을 여러 해에 걸쳐 비교합니다. 결과는 검토용 추정치이며 세금 신고 조언이 아닙니다.',
      usingExampleAssumptions: '예시 가정 사용 중',
      editAssumptions: '가정 수정',
      openStaticOpportunityAnalysis: '정적 기회 분석 열기',
      annualFilingProfile: '연도별 신고 프로필',
      annualFilingProfileInfo: '신고 플래그는 해당 국가의 보고 작업 필요 여부를 추적합니다. 세금 계산 플래그는 해당 국가의 세금 추정치를 계획 계산에 포함할지 결정합니다.',
      baseAssumptions: '기본 가정',
      annualTargetScenarioComparison: '연간 목표 시나리오 비교',
      selectedSingleYearTaxSplit: '선택한 단일 연도 세금 분해',
      warnings: '경고',
      recommendedSaleLotSequence: '추천 매도 lot 순서',
      allOpenLotCandidates: '전체 열린 lot 후보',
      year: '연도',
      taxCalc: '세금 계산',
      projectedWages: '예상 임금',
      projectedWagesInfo: 'W-2 기준 임금에 연소득 증가율 가정을 적용한 값입니다. 예상 과세소득이 아닙니다.',
      usFiling: '미국 신고',
      usFilingInfo: '해당 연도에 미국 세금 보고 workflow와 증빙 검토가 필요한지 여부입니다. 이 값만으로 플래너 계산이 바뀌지는 않습니다.',
      krFiling: '한국 신고',
      krFilingInfo: '해당 연도에 한국 세금 보고 workflow와 증빙 검토가 필요한지 여부입니다. 이 값만으로 플래너 계산이 바뀌지는 않습니다.',
      status: '상태',
      required: '필요',
      off: '꺼짐',
      scenario: '시나리오',
      filingState: '신고 / 주',
      w2WageBase: 'W-2 임금 기준',
      annualIncomeGrowth: '연소득 증가율',
      federalMethod: '연방 계산 방식',
      federalMethodValue: '2026 MFJ 누진세율',
      fallbackShortLong: '대체 단기 / 장기',
      fallbackStateNiit: '대체 주세 / NIIT',
      ytdCarryovers: '연초 이후 실현 / 이월',
      krStockDeduction: '한국 주식 공제',
      krForeignStockRate: '한국 해외주식 세율',
      creditModel: '공제 모델',
      annualTargetInfo: '이 행들은 계획 기간 동안 같은 연간 KRW 매도 목표를 어떻게 충족할지 비교합니다. 같은 해 안에서 한국 또는 미국 신고가 먼저 되는지는 모델링하지 않습니다.',
      annualTargetNote: '각 행은 같은 연간 테스트 금액을 사용하고, 어느 시장을 먼저 매도하는지만 바꿉니다. Opportunity map에서 대략적인 연간 매도 범위를 고른 뒤 읽으세요.',
      totalSales: '총 매도',
      realizedGainLoss: '실현 손익',
      estimatedTax: '추정 세금',
      afterTaxCash: '세후 현금',
      peakYearTax: '최대 연도 세금',
      lotsUsed: '사용 lot',
      lowestTax: '최저 세금',
      sameTax: '동일 세금',
      annualTargetHidden: '연간 테스트 금액을 입력하기 전까지 이 비교는 숨깁니다. 반복되는 연간 매도 금액이 없으면 최저 세금 또는 동일 세금 같은 라벨은 의사결정 수준이 아닙니다.',
      annualTargetHiddenHint: '먼저 Opportunity map에서 유망한 연도와 시장을 찾고, 위에 KRW 금액을 입력해 실행 시나리오를 비교하세요.',
      singleYearTaxSplitInfo: '현재 선택한 lot 순서의 세금 추정치입니다. 전체 포트폴리오 세금이 아닙니다. 연방/캘리포니아 금액은 예상 임금소득 위에 추가되는 증분 세금입니다.',
      federalShortTerm: '연방 단기',
      federalLongTerm: '연방 장기',
      niit: 'NIIT',
      californiaState: '캘리포니아 / 주',
      usGrossEstimate: '미국 총 추정',
      krGrossTax: '한국 총세금',
      usFtcLimitUsed: '미국 FTC 한도 / 사용',
      krCreditUsed: '한국 공제 사용',
      combinedAfterCredit: '공제 후 합산',
      afterTaxProceeds: '세후 매도대금',
      method: '방식',
      methodNote: (method: string) => `방식: ${method}. FTC는 선택한 공제 모드에서만 적용되며, 원천 및 조세조약 비율은 수동 입력값으로 남습니다.`,
      noPlannerWarnings: '플래너 경고 없음',
      inputs: '입력',
      resolveFreshness: (count: string) => `거래 전 freshness 이슈 ${count}개를 해결하세요.`,
      review: '검토',
    },
    settings: {
      title: '계획 설정',
      subtitle: '매도 시점 규칙과 기간을 선택한 뒤 계획을 다시 계산하세요.',
      badge: '현재 가격과 FX로 계산',
      schedulingRule: '일정 규칙',
      schedulingRuleInfo: '결정론적 일정 규칙을 선택합니다. 세금 계산은 규칙 기반이며 시장 전망이나 LLM 판단을 사용하지 않습니다.',
      staged: '장기 보유 요건 충족 후 단계적 매도',
      earliestLongTerm: '가장 이른 장기 보유 가능일에 매도',
      waitUsOnly: '미국만 신고하는 시점까지 대기',
      accelerateLosses: '손실 수확 앞당기기',
      schedulingHint: '각 tax lot이 일정에 처음 들어가는 시점을 제어합니다.',
      executionWindow: '실행 기간',
      executionWindowInfo: '단계적 계획에서는 현재 가격이 있는 lot 가치를 이 개월 수로 나눕니다. 다른 계획은 허용되는 가장 이른 날짜를 사용합니다.',
      months: '개월',
      executionHint: '단계적 계획에 적용됩니다.',
      taxHorizon: '세금 계획 기간',
      years: '년',
      horizonHint: '연도별 신고 프로필 변화를 포함합니다.',
      rebuild: '계획 다시 계산',
    },
    candidateTable: {
      empty: '열린 tax lot이 있는 매도 후보가 없습니다',
      position: '포지션',
      account: '계좌',
      acquired: '취득일',
      term: '기간',
      quantity: '수량',
      proceeds: '매도 금액',
      baseGainLoss: '기준 손익',
      grossLotTax: 'lot별 총세금',
      afterTax: '세후 금액',
      notAvailable: '없음',
    },
    overview: {
      title: '선택한 계획',
      info: '이 계획은 tax-lot 취득일, 연도별 신고 프로필, 현재 가격, 현재 FX를 사용합니다. 시장 전망은 사용하지 않습니다.',
      executionWindow: '추천 실행 기간',
      to: '부터',
      whyThisMatters: '중요한 이유',
      longTermTreatment: (pct: string) => `이 일정에서는 계획 매도 금액의 ${pct}%가 장기 보유 처리를 받습니다.`,
      plannedSales: '계획 매도',
      pricedLots: (count: string) => `가격이 있는 lot ${count}개`,
      estimatedTax: '추정 세금',
      longTermPct: (pct: string) => `${pct}% 장기`,
      afterTaxCash: '세후 현금',
      saleInstructions: (count: string) => `매도 지시 ${count}개`,
      inputCoverage: '입력 커버리지',
      inputCoverageInfo: '현재 보유 평가액 중 계획에 사용할 수 있는 가격 있는 tax lot과 연결된 비중입니다.',
      coverageHint: (issues: string, unpriced: string) => `이슈 ${issues}개 · 가격 없음 ${unpriced}개`,
      reviewInputRange: '입력 범위를 확인하세요.',
      coverageWarning: '계획 금액이 현재 보유 평가액보다 커서 커버리지가 100%를 초과합니다. 결과를 사용하기 전에 중복 tax lot이나 오래된 가격을 확인하세요.',
      lotsStillWaiting: '아직 대기 중인 lot',
      waitingLots: (lots: string, amount: string, next: string | null) => `${lots}개 lot, ${amount} 규모가 아직 1년을 넘기지 않았습니다.${next ? ` 다음: ${next}.` : ''}`,
      estimatedTermBenefit: '추정 기간 혜택',
      termBenefit: (amount: string) => `장기 보유 처리를 기다리면 현재 수익 중인 단기 lot에서 연방 세율 차이 약 ${amount}를 피할 수 있습니다.`,
      waitingUntil2028: '2028년까지 대기',
      saving: '절감',
      extraTax: '추가 세금',
      waitUntil2028: (label: string, amount: string, duration: string, earliest: string, wait: string) => `추정 ${label}: ${amount}, 약 ${duration} 더 대기. 한국 추가세는 ${earliest}에서 ${wait}로 바뀝니다.`,
    },
    comparison: {
      title: '계획 비교',
      info: '모든 행은 현재 가격이 있는 동일한 lot을 매도합니다. 달라지는 것은 시점과 보유기간 처리뿐입니다.',
      lowestEstimatedTax: '가장 낮은 추정 세금',
      scale: '세금 막대는 같은 기준을 씁니다. 짧을수록 낮습니다.',
      selected: '선택됨',
      lowestTax: '최저 세금',
      estimatedTax: '추정 세금',
      earliestBaseline: '가장 이른 매도 기준',
      less: (amount: string) => `${amount} 적음`,
      more: (amount: string) => `${amount} 많음`,
      execution: '실행',
      to: '부터',
      longTermSales: '장기 매도',
      averageWait: '평균 대기',
      krTopUp: '한국 추가세',
    },
    savedPlans: {
      title: '저장된 실행 계획',
      info: '저장은 변경 불가능한 계산 스냅샷을 만듭니다. 검토와 실행 상태는 원래 세금 추정치와 별도로 기록됩니다.',
      recent: (count: string) => `최근 ${count}개`,
      saveCurrentCalculation: '현재 계산 저장',
      saveDescription: '검토 전에 선택 전략, 수량, 날짜, 세금 가정, lot별 지시를 고정합니다.',
      planName: '계획 이름',
      placeholder: '예: 2026 staged baseline',
      saveAsDraft: '초안으로 저장',
      storageNote: 'git에 커밋되지 않는 ignored private JSON 파일에 로컬로 저장됩니다.',
      execution: '실행',
      planned: '계획됨',
      executed: (done: string, total: string) => `${done} / ${total} 실행`,
      empty: '저장된 계획이 아직 없습니다. 검토 준비가 되면 현재 계산을 저장하세요.',
    },
    savedPlanDetail: {
      eyebrow: '세금 · 저장된 계획',
      subtitle: (date: string, revision: string | number) => `${date} 기준 변경 불가능한 계산 snapshot · revision ${revision}`,
      backToPlanner: '플래너로 돌아가기',
      executionOverview: '실행 개요',
      executionOverviewInfo: '세금 계산 snapshot은 바뀌지 않습니다. 원래 계획을 감사 가능하게 유지하기 위해 검토와 실행 업데이트는 별도로 기록됩니다.',
      plannedSales: '계획 매도',
      estimatedTax: '추정 세금',
      instructions: '지시',
      complete: '완료',
      executed: '실행됨',
      reviewed: '검토됨',
      planned: '계획됨',
      skipped: '건너뜀',
      actualProceeds: '실제 매도대금',
      planStatus: '계획 상태',
      updateStatus: '상태 업데이트',
      created: '생성',
      updated: '수정',
      currentDataDrift: '현재 데이터 차이',
      currentDataDriftInfo: '저장된 변경 불가능 snapshot과 오늘의 보유, 가격, FX, 세금 정책으로 새로 계산한 값을 비교합니다. 저장된 계획은 변경하지 않습니다.',
      reviewChanges: '변경 검토',
      noMaterialChange: '중요 변경 없음',
      noChange: '변화 없음',
      afterTaxCash: '세후 현금',
      driftSummary: (savedDate: string, liveDate: string, savedVersion: string | number, liveVersion: string | number) =>
        `저장 기준일 ${savedDate}; 새 계산 기준일 ${liveDate}. 세금 정책 version ${savedVersion} → ${liveVersion}.`,
      openFreshCalculation: '새 계산 열기',
      snapshotProvenance: 'Snapshot 출처',
      strategy: '전략',
      executionWindow: '실행 기간',
      taxHorizon: '세금 기간',
      taxPolicy: '세금 정책',
      months: '개월',
      years: '년',
      version: 'version',
      statusLabels: {
        draft: '초안',
        reviewed: '검토됨',
        active: '진행 중',
        completed: '완료',
        archived: '보관됨',
      },
    },
    timeline: {
      saleTimeline: '매도 타임라인',
      saleTimelineInfo: '각 열은 활성 매도 월입니다. 막대 높이는 가장 바쁜 달 대비 계획 매도대금을 보여주며, 색상은 그 달의 순결과가 이익인지 손실인지 보여줍니다.',
      activeMonths: (count: string) => `활성 월 ${count}개`,
      executionSpan: '실행 범위',
      to: '부터',
      inspectHint: '정확한 lot과 수량을 보려면 월을 선택하세요. 선택은 페이지를 다시 로드하지 않고 유지됩니다.',
      netGain: '순이익',
      netLoss: '순손실',
      saleTimelineAria: (year: string | number) => `${year} 매도 타임라인`,
      plannedSalesAria: (label: string, amount: string) => `${label}: 계획 매도 ${amount}`,
      positions: '포지션',
      instructions: (count: string) => `지시 ${count}개`,
      monthDetailHint: '이 달의 정확한 매도 lot입니다. 세금은 아래에 표시된 연간 수준에서 netting됩니다.',
      page: '페이지',
      of: '/',
      saleDate: '매도일',
      position: '포지션',
      account: '계좌',
      quantity: '수량',
      purpose: '목적',
      estimatedProceeds: '추정 매도대금',
      estimatedGainLoss: '추정 손익',
      execution: '실행',
      longTermFrom: (date: string) => `장기 전환일 ${date}`,
      washSaleReview: 'Wash-sale 검토',
      washSaleReviewDetail: (count: string | number) => `Wash-sale 검토: 설정된 기간 내 같은 ticker 열린 lot 취득 ${count}건.`,
      lossOffset: '손실 상계',
      gainSale: '이익 매도',
      neutral: '중립',
      actualsAndNote: '실제값과 메모',
      executedDate: '실행일',
      actualProceedsKrw: '실제 매도대금 KRW',
      actualGainLossKrw: '실제 손익 KRW',
      actualGainOrLossKrw: '실제 이익 또는 손실 KRW',
      executionNote: '실행 메모',
      save: '저장',
      executionStatus: '실행 상태',
      plannedStatus: '계획됨',
      reviewedStatus: '검토됨',
      executedStatus: '실행됨',
      skippedStatus: '건너뜀',
      plannedSales: '계획 매도',
      grossGains: '총이익',
      pairedLosses: '매칭 손실',
      netGainLoss: '순손익',
      showing: '표시',
      previous: '이전',
      next: '다음',
      noScheduledSaleInstructions: '예약된 매도 지시가 없습니다',
      noProfile: '프로필 없음',
      usOnly: '미국만',
      krOnly: '한국만',
    },
    annualTax: {
      title: '연도별 세금 합계',
      info: '연도별 결과는 예정된 이익과 손실을 상계하고, 단기 이익을 예상 근로소득 위에 쌓으며, 장기 구간, NIIT, 캘리포니아 세금, 설정된 국경 간 공제 모델만 적용합니다.',
      netTax: '순세금',
      sales: '매도',
      netGainLoss: '순손익',
      usGross: '미국 총세금',
      krGross: '한국 총세금',
      creditUsed: '사용 공제',
      afterTaxCash: '세후 현금',
      taxComponents: '세금 구성',
      taxYear: '세금 연도',
      profile: '프로필',
      credit: '공제',
      federalShortTerm: '연방 단기',
      federalLongTerm: '연방 장기',
      niit: 'NIIT',
      california: '캘리포니아',
      usFtcLimit: '미국 FTC 한도',
      usFtcUsed: '미국 FTC 사용',
      krCreditUsed: '한국 공제 사용',
    },
    opportunity: {
      timingSignal: '시점 신호',
      timingSignalTitle: (amount: string) => `선택적 미국시장 이익 실현을 미루면 세금을 ${amount} 줄일 수 있습니다`,
      timingSignalBody: (yearLabel: string, grossKrTax: string, credit: string, increment: string) =>
        `${yearLabel}에는 한국 총세금 ${grossKrTax}, 추정 국경 간 공제 ${credit}가 있습니다. 남는 한국 추가세는 ${increment}입니다.`,
      timingSignalAction: (yearLabel: string) =>
        `공제 한도와 소득 원천 처리를 확인한 뒤, 선택적 이익 실현을 ${yearLabel}에 실행하는 안과 비교하세요.`,
      timingSignalCaveat: (isExample: boolean) =>
        `이 추정은 모델링된 미국 연방세만 공제 풀로 사용하며 캘리포니아와 NIIT는 제외합니다. 최종 공제 가능성, FX, Form 1116/한국 신고 처리는 검토가 필요합니다.${isExample ? ' 공제와 세율은 예시 기본값입니다.' : ''}`,
      afterCreditMetric: (amount: string) => `${amount} 공제 후`,
      filingProfileOnly: '신고 프로필 효과만',
      filingProfileOnlyTitle: '신고 프로필 변화만으로는 ₩0 절감입니다',
      filingProfileOnlyBody: (yearLabel: string, grossKrTax: string, credit: string, increment: string, combined: string, lowestYearLabel: string) =>
        `${yearLabel} 한국 총세금은 ${grossKrTax}이지만 추정 공제는 ${credit}입니다. 따라서 추가 한국세 ${increment}, 합산 세금 ${combined}가 남고, ${lowestYearLabel}와 같은 모델링 결과입니다.`,
      filingProfileOnlyAction: '이를 즉시 매도 신호로 보지 마세요. 실제 시점 결정은 각 lot이 단기에서 장기로 바뀌는 효과와 미래 가격/FX까지 함께 모델링해야 합니다.',
      filingProfileOnlyCaveat: (isExample: boolean) =>
        `이 정적 비교는 모든 연도에서 오늘의 단기/장기 구분을 고정합니다. 2028년에는 현재 단기 lot이 장기가 되어 미국 연방세와 한국 공제 한도가 달라질 수 있습니다. 미국 상장 이익은 미국 원천으로 취급하며 캘리포니아와 NIIT는 공제 풀에서 제외합니다.${isExample ? ' 세율은 예시 기본값입니다.' : ''}`,
      modeledSavingMetric: (amount: string) => `${amount} 모델상 절감`,
      potentialPairing: '상계 후보',
      potentialPairingTitle: '같은 미국 세금연도 안에서 한국 손실 lot과 미국 단기 이익을 맞춰보세요',
      potentialPairingBody: (krLoss: string, usGain: string, pairable: string) =>
        `현재 화면에는 한국 단기 미실현 손실 ${krLoss}, 미국시장 순 단기 이익 ${usGain}가 보입니다. 최대 ${pairable}까지 미국 단기 이익을 줄이는 상계 후보로 볼 수 있습니다.`,
      potentialPairingAction: '미국 단기 이익 매도가 계획되어 있다면, 정확한 티커 선택 전 같은 미국 세금연도 안에서 충분한 한국 단기 손실 lot을 검토하세요.',
      potentialPairingCaveat: (impact: string, ratePct: string) =>
        `현재 ${ratePct}% 가정에서 스크리닝상 세금 효과는 최대 ${impact}입니다. KRW 손실이 자동으로 미국 세법상 손실이 되는 것은 아닙니다. USD 기준가, 거래일 FX, 계좌 적격성, wash sale, 기타 자본거래를 확인해야 합니다.`,
      gainToScreenMetric: (amount: string) => `${amount} 검토할 이익`,
      meaningOfNumber: '숫자의 의미',
      meaningOfNumberTitle: (amount: string) => `${amount}는 손실 lot 매도대금이지 비과세 한도가 아닙니다`,
      meaningOfNumberBody: (proceeds: string, loss: string) =>
        `현재 식별된 한국 손실 lot을 팔면 약 ${proceeds}의 현금과 약 ${loss}의 손실이 발생합니다. 이 매도대금에는 수익 중인 한국 lot이 포함되지 않습니다.`,
      meaningOfNumberAction: '손실 금액은 상계 재고로, 매도대금은 유동성 계획용으로만 보세요.',
      meaningOfNumberCaveat: '미국 시민/거주자는 일반적으로 전세계 소득을 신고하므로, 한국 상장 주식의 이익에도 미국 세금이 적용될 수 있습니다.',
      lossInventoryMetric: (amount: string) => `${amount} 손실 재고`,
      currentDecision: '현재 판단',
      reviewTimingSignals: '매도 선택 전에 시점 신호를 먼저 검토하세요',
      noTaxDifference: '시점 선택 간 세금 차이가 없습니다',
      currentLowestTaxPath: (label: string) => `현재 최저세금 경로: ${label}`,
      noPlanningTargetBody: '기회 지도는 총 시점 차이, 손실 상계 후보, 관할별 세금 추정치를 분리해서 보여줍니다. 정확한 매도 금액을 테스트하기 전에 그 신호로 그럴듯한 연간 범위를 정하세요.',
      tiedTaxBody: '현재 가정에서는 시장 순서를 바꿔도 추정 세금이 달라지지 않습니다. lot 표를 읽기 전에 현금 필요, 노출, 데이터 이슈를 먼저 보세요.',
      recommendationBody: '연도별 실행 계획을 먼저 보세요. 아래 lot 표는 선택한 시장 시점 경로의 실행 세부사항입니다.',
      explore: '탐색',
      tie: '동률',
      recommendation: '추천',
      step1: '1단계',
      step1Body: '시점 신호와 손실 재고 확인',
      step2: '2단계',
      step2Body: '임시 연간 범위 선택',
      step3: '3단계',
      step3Body: '그 범위를 시나리오로 테스트',
      openLots: '열린 lot',
      openLotsHint: '사용 가능한 tax-lot 행',
      inputIssues: '입력 이슈',
      inputIssuesInfo: '계획 결과에 의존하기 전에 해결해야 할 데이터 품질 또는 freshness 항목입니다.',
      inputIssuesHint: '결과를 신뢰하기 전 해결할 항목',
      annualTest: '연간 테스트',
      lossLotProceeds: '손실 lot 매도대금',
      scenarioInputAmount: '시나리오 입력 금액',
      estimatedTax: '추정 세금',
      lossHarvest: '손실 수확',
      modeledLossInventory: '모델링된 손실 재고',
      actionPlanTitle: '연도별 실행 계획',
      opportunityMapTitle: '기회 지도',
      actionPlanInfo: '의사결정 레이어입니다. 각 세금연도에 어느 시장에서 실현할지 보여주며, 구체적 lot은 뒤의 실행 세부사항에 있습니다.',
      opportunityMapInfo: '목표 금액을 확정하기 전에 시점 신호, 손실 재고, 관할별 세금 추정치를 분리해서 보는 탐색 레이어입니다.',
      noPlanningOpportunities: '현재 tax lot에서 계획 기회를 찾지 못했습니다',
      stressTestNote: '이 표는 취득 기록과 현재 가격이 있는 열린 tax lot 전체를 전부 판다고 가정한 스트레스 테스트입니다. 완전한 lot 배분이 없는 포지션은 보유 전체 잔고와 다를 수 있어 보유기간 분석에서 제외됩니다. 미래 연도도 현재 가격, FX, 단기/장기 구분을 재사용하므로 실제 미래 매도를 예측하기보다 신고 프로필 변화만 분리해서 봅니다. 국가별 총세금, 추정 국경 간 공제, 공제 후 세금을 따로 표시합니다.',
      fullHoldingsGl: '전체 보유 미실현 손익',
      taxLotModeledGl: 'tax-lot 모델 손익',
      unallocatedHoldingValue: '미배분 보유 평가액',
      unmodeledGlDifference: '모델 밖 손익 차이',
      whatToConsider: '검토할 점',
      years: '연도',
      market: '시장',
      taxProfile: '세금 프로필',
      taxProfileInfo: '해당 연도에 어느 국가의 세금 계산이 활성화되는지입니다. US_AND_KR은 미국과 한국 추정치를 모두 포함한다는 뜻입니다.',
      netGainLoss: '순손익',
      netGainLossInfo: '현재 가격이 있는 이 시장의 모든 lot을 판다고 가정한 손익입니다. 이 스트레스 케이스는 매도 추천이 아닙니다.',
      lossInventory: '손실 재고',
      lossInventoryInfo: '손실 lot의 미실현 손실입니다. 관련 매도대금은 행 세부정보에 표시되며, 비과세 한도가 아닙니다.',
      usEstimate: '미국 추정',
      usEstimateInfo: '단기/장기 상계 후 미국 계획 추정치입니다. KRW 손익을 proxy로 쓰며, 신고에는 USD 기준가와 거래일 FX가 필요합니다.',
      krEstimate: '한국 추정',
      krEstimateInfo: '적용 가능한 손실 상계와 설정된 연간 공제 후 한국 계획 추정치입니다. 국내 상장주식 과세 여부는 Tax Settings를 따릅니다.',
      beforeCredits: '공제 전',
      beforeCreditsInfo: '외국납부세액공제 전 미국+한국 추정치입니다. 최종 합산 현금 세금으로 해석하지 마세요.',
      estimatedCredit: '추정 공제',
      estimatedCreditInfo: '미국시장 이익에 귀속되는 모델링된 미국 연방세에 대한 한국 공제 추정치이며, 한국 총세금으로 한도가 걸립니다. 캘리포니아와 NIIT는 이 공제 풀에서 제외됩니다.',
      afterCredit: '공제 후',
      afterCreditInfo: '미국 추정치 + 한국 총세금 - 추정 국경 간 공제입니다. 여전히 계획 추정치이며 신고된 공제 계산이 아닙니다.',
      whyItMatters: '중요한 이유',
      whyItMattersInfo: '개별 lot을 선택하기 전에 검토할 구체적인 시점 또는 관할상 의미입니다.',
      rowReadoutUsKr: (krGross: string, credit: string, increment: string) => `한국 총세금 ${krGross} - 추정 공제 ${credit} = 한국 추가세 ${increment}.`,
      rowReadoutUsOnly: '이 프로필에서는 한국 세금 계산이 꺼져 있으며 미국 추정치는 남습니다.',
      rowReadoutKrUs: '전세계소득 가정상 한국 상장 이익에도 미국 추정치가 적용됩니다.',
      rowReadoutNone: '이 행에는 양의 합산 세금이 모델링되지 않았습니다.',
      rowDetail: (count: string, lossProceeds: string, totalProceeds: string) =>
        `가격 있는 lot ${count}개 · 손실 lot 매도대금 ${lossProceeds} · 전체 lot 매도대금 ${totalProceeds}`,
      year: '연도',
      filingProfile: '신고 프로필',
      sellKrMarket: '한국시장 매도',
      sellUsMarket: '미국시장 매도',
      target: '목표',
      readout: '해석',
      mostlyKrSales: '대부분 한국 상장 매도',
      mostlyUsSales: '대부분 미국 상장 매도',
      mixedMarketSales: '혼합 시장 매도',
      noPlannedSale: '계획 매도 없음',
      noAllocatedSaleLots: '배정된 매도 lot 없음',
      tax: '세금',
    },
  },
})
