import { defineCopy } from '@/lib/ui-copy/define'

export const taxSettings = defineCopy({
  en: {
    page: {
      title: 'Tax Settings',
      emphasis: 'Settings',
      subtitle: 'Local assumptions for realization planning. This writes only to ignored data/tax-policy.json.',
      saved: 'Saved',
      openPlanner: 'Open planner',
    },
    hero: {
      eyebrow: 'Tax settings headline',
      title: 'Policy Source',
      info: 'Shows whether the planner is using your local ignored tax-policy.json file or the example fallback assumptions.',
      local: 'Local',
      example: 'Example',
      localHint: 'Using local planning assumptions',
      exampleHint: 'Using example assumptions until local settings are saved',
      scenario: 'Scenario',
      scenarioHint: 'Default filing scenario',
      jurisdictions: 'Jurisdictions',
      jurisdictionsHint: 'Enabled tax regimes',
      updated: 'Updated',
      updatedHint: 'Last settings write',
      notAvailable: 'n/a',
    },
    readOrder: {
      title: 'Settings Read Order',
      info: 'Start with the policy source, then confirm scenario, jurisdictions, and annual filing assumptions.',
      planningHorizon: 'Planning Horizon',
      planningHorizonHint: 'Years projected in planner scenarios',
      years: 'years',
      baseCurrency: 'Base Currency',
      baseCurrencyHint: 'Currency used for planning summaries',
      note: 'Settings are assumptions for planning; filing forms and tax professional review remain outside the app.',
    },
    scenarios: {
      US_ONLY: 'US only',
      KR_ONLY: 'Korea only',
      US_AND_KR: 'US + Korea',
    },
    filingProfile: {
      title: 'Filing profile',
      activeScenario: 'Active scenario',
      baseCurrency: 'Base currency',
      planningHorizon: 'Planning horizon',
      note: 'Settings are assumptions for planning. Lot evidence, filing forms, residency, treaty positions, and tax professional review remain outside the app.',
    },
    annualTimeline: {
      title: 'Annual filing timeline',
      info: "Filing means reporting workflow is required for that country/year. Tax calc means the planner includes that country's tax estimate in scenario math.",
      year: 'Year',
      defaultScenario: 'Default scenario',
      usFiling: 'US filing',
      usFilingInfo: 'Tracks whether this year needs US filing work, evidence collection, and reporting review.',
      usTaxCalc: 'US tax calc',
      usTaxCalcInfo: 'Controls whether US capital gain tax assumptions are included in planning estimates for this year.',
      krFiling: 'KR filing',
      krFilingInfo: 'Tracks whether this year needs Korea filing work, evidence collection, and reporting review.',
      krTaxCalc: 'KR tax calc',
      krTaxCalcInfo: 'Controls whether Korea stock tax assumptions are included in planning estimates for this year.',
      status: 'Status',
      assumed: 'Assumed',
      confirmed: 'Confirmed',
      note: 'In normal cases filing and tax calc should usually move together. Keep them separate only when reporting duty is known but the taxable calculation needs manual review, or when stress-testing a planning assumption.',
    },
    compactCheck: {
      usFilingRequired: 'US filing required',
      usTaxCalculationEnabled: 'US tax calculation enabled',
      krFilingRequired: 'KR filing required',
      krTaxCalculationEnabled: 'KR tax calculation enabled',
    },
    us: {
      title: 'US assumptions',
      fallbackShortTermRate: 'Fallback short-term rate',
      fallbackLongTermRate: 'Fallback long-term rate',
      fallbackStateRate: 'Fallback state rate',
      niitRate: 'NIIT rate',
      filingStatus: 'Filing status',
      state: 'State',
      wageBaseYear: 'Wage base year',
      w2Wages: 'W-2 wages',
      annualIncomeGrowth: 'Annual income growth',
      federalBracketInflation: 'Federal bracket inflation',
      californiaBracketInflation: 'California bracket inflation',
      planningUsdKrw: 'Planning USD/KRW',
      currentTaxInputYear: 'Current tax input year',
      lossDeductionLimit: 'Loss deduction limit',
      ytdRealizedShort: 'YTD realized short G/L',
      ytdRealizedLong: 'YTD realized long G/L',
      shortLossCarryover: 'Short loss carryover',
      longLossCarryover: 'Long loss carryover',
      ftcCarryover: 'FTC carryover',
      ftcForeignSourceShare: 'FTC foreign-source share',
      washSaleBefore: 'Wash sale before',
      washSaleAfter: 'Wash sale after',
      days: 'days',
      ytdHint: (basis: string, taxYear: string, value: string, lots: number) => `${basis} for ${taxYear}: ${value} USD across ${lots} lot(s)`,
      note: 'MFJ uses the official 2026 federal brackets and long-term capital-gain thresholds. Later federal years and the 2025 California schedule are inflation projections. Fallback rates apply to unsupported filing statuses or states. FTC foreign-source share must be supported by sourcing or treaty analysis; zero prevents the planner from claiming a US credit automatically.',
    },
    kr: {
      title: 'Korea assumptions',
      stockBasicDeduction: 'Stock basic deduction',
      foreignStockRate: 'Foreign stock rate',
      foreignTaxableResidenceThreshold: 'Foreign taxable residence threshold',
      residentThroughYear: 'Resident through year',
      crossBorderCreditModel: 'Cross-border credit model',
      noAutomaticCredit: 'No automatic credit',
      krCreditForUsTax: 'KR credit for modeled US federal tax',
      usForm1116Limit: 'US Form 1116-style limit for KR tax',
      domesticMajorShareholder: 'KR domestic major shareholder taxable scope',
      listedOffMarketSale: 'KR listed off-market sale taxable scope',
    },
    localPolicy: {
      title: 'Local policy file',
      localPath: 'Local path',
      fallback: 'Fallback',
      save: 'Save local tax assumptions',
    },
    calculationBasis: {
      title: 'Calculation basis',
      info: 'Primary sources used by the planner. Later-year inflation and treaty sourcing remain planning assumptions, not filing conclusions.',
      federalBrackets: '2026 federal brackets',
      federalBracketsNote: 'IRS Rev. Proc. 2025-32 summary',
      capitalGainNetting: 'Capital gain netting',
      capitalGainNettingNote: 'IRS Topic 409',
      foreignTaxCreditLimit: 'Foreign tax credit limit',
      foreignTaxCreditLimitNote: 'IRS Form 1116 overview',
      californiaSchedule: 'California schedule',
      californiaScheduleNote: '2025 FTB Schedule Y',
    },
  },
  ko: {
    page: {
      title: '세금 설정',
      emphasis: '설정',
      subtitle: '매도 실현 계획에 쓰는 로컬 가정입니다. 저장 시 git에 포함되지 않는 data/tax-policy.json 파일에만 기록됩니다.',
      saved: '저장됨',
      openPlanner: '플래너 열기',
    },
    hero: {
      eyebrow: '세금 설정 핵심',
      title: '정책 출처',
      info: '플래너가 로컬 tax-policy.json 설정을 쓰는지, 예시 기본값을 쓰는지 보여줍니다.',
      local: '로컬',
      example: '예시',
      localHint: '로컬 계획 가정을 사용 중',
      exampleHint: '로컬 설정을 저장하기 전까지 예시 가정을 사용 중',
      scenario: '시나리오',
      scenarioHint: '기본 신고 시나리오',
      jurisdictions: '관할',
      jurisdictionsHint: '활성화된 세금 체계',
      updated: '업데이트',
      updatedHint: '마지막 설정 저장일',
      notAvailable: '없음',
    },
    readOrder: {
      title: '설정 확인 순서',
      info: '정책 출처를 먼저 보고, 시나리오, 관할, 연도별 신고 가정을 차례로 확인하세요.',
      planningHorizon: '계획 기간',
      planningHorizonHint: '플래너 시나리오에 반영할 연수',
      years: '년',
      baseCurrency: '기준 통화',
      baseCurrencyHint: '계획 요약에 쓰는 통화',
      note: '이 설정은 계획용 가정입니다. 실제 신고 서식과 세무 전문가 검토는 앱 범위 밖입니다.',
    },
    scenarios: {
      US_ONLY: '미국만',
      KR_ONLY: '한국만',
      US_AND_KR: '미국 + 한국',
    },
    filingProfile: {
      title: '신고 프로필',
      activeScenario: '활성 시나리오',
      baseCurrency: '기준 통화',
      planningHorizon: '계획 기간',
      note: '이 설정은 계획용 가정입니다. lot 증빙, 신고 서식, 거주자 판정, 조세조약 포지션, 세무 전문가 검토는 앱 범위 밖입니다.',
    },
    annualTimeline: {
      title: '연도별 신고 일정',
      info: '신고는 해당 국가/연도에 보고 작업이 필요하다는 뜻입니다. 세금 계산은 플래너가 해당 국가의 세금 추정치를 시나리오 계산에 포함한다는 뜻입니다.',
      year: '연도',
      defaultScenario: '기본 시나리오',
      usFiling: '미국 신고',
      usFilingInfo: '해당 연도에 미국 신고 작업, 증빙 수집, 보고 검토가 필요한지 추적합니다.',
      usTaxCalc: '미국 세금 계산',
      usTaxCalcInfo: '해당 연도의 계획 추정치에 미국 양도소득세 가정을 포함할지 제어합니다.',
      krFiling: '한국 신고',
      krFilingInfo: '해당 연도에 한국 신고 작업, 증빙 수집, 보고 검토가 필요한지 추적합니다.',
      krTaxCalc: '한국 세금 계산',
      krTaxCalcInfo: '해당 연도의 계획 추정치에 한국 주식 세금 가정을 포함할지 제어합니다.',
      status: '상태',
      assumed: '가정',
      confirmed: '확정',
      note: '일반적으로 신고와 세금 계산은 함께 움직이는 것이 자연스럽습니다. 신고 의무는 알지만 과세 계산은 수동 검토가 필요하거나, 계획 가정을 스트레스 테스트할 때만 분리하세요.',
    },
    compactCheck: {
      usFilingRequired: '미국 신고 필요',
      usTaxCalculationEnabled: '미국 세금 계산 활성화',
      krFilingRequired: '한국 신고 필요',
      krTaxCalculationEnabled: '한국 세금 계산 활성화',
    },
    us: {
      title: '미국 가정',
      fallbackShortTermRate: '대체 단기 세율',
      fallbackLongTermRate: '대체 장기 세율',
      fallbackStateRate: '대체 주 세율',
      niitRate: 'NIIT 세율',
      filingStatus: '신고 상태',
      state: '주',
      wageBaseYear: '임금 기준 연도',
      w2Wages: 'W-2 임금',
      annualIncomeGrowth: '연소득 증가율',
      federalBracketInflation: '연방 구간 인플레이션',
      californiaBracketInflation: '캘리포니아 구간 인플레이션',
      planningUsdKrw: '계획용 USD/KRW',
      currentTaxInputYear: '현재 세금 입력 연도',
      lossDeductionLimit: '손실 공제 한도',
      ytdRealizedShort: '연초 이후 단기 실현 손익',
      ytdRealizedLong: '연초 이후 장기 실현 손익',
      shortLossCarryover: '단기 손실 이월',
      longLossCarryover: '장기 손실 이월',
      ftcCarryover: '외국납부세액공제 이월',
      ftcForeignSourceShare: '외국원천 이익 비중',
      washSaleBefore: '워시세일 이전 기간',
      washSaleAfter: '워시세일 이후 기간',
      days: '일',
      ytdHint: (basis: string, taxYear: string, value: string, lots: number) => `${taxYear} ${basis}: ${value} USD, ${lots}개 lot 기준`,
      note: 'MFJ는 공식 2026년 연방 세율 구간과 장기 양도소득 기준을 사용합니다. 이후 연방 연도와 2025년 캘리포니아 스케줄은 인플레이션 추정입니다. 지원하지 않는 신고 상태나 주에는 대체 세율을 적용합니다. 외국원천 이익 비중은 소득 원천 또는 조세조약 분석으로 뒷받침되어야 하며, 0은 플래너가 미국 세액공제를 자동 청구하지 못하게 합니다.',
    },
    kr: {
      title: '한국 가정',
      stockBasicDeduction: '주식 기본공제',
      foreignStockRate: '해외주식 세율',
      foreignTaxableResidenceThreshold: '해외주식 과세 거주기간 기준',
      residentThroughYear: '거주자 적용 종료 연도',
      crossBorderCreditModel: '국경 간 세액공제 모델',
      noAutomaticCredit: '자동 공제 없음',
      krCreditForUsTax: '모델링된 미국 연방세에 대한 한국 공제',
      usForm1116Limit: '한국 세금에 대한 미국 Form 1116식 한도',
      domesticMajorShareholder: '한국 국내 대주주 과세 범위',
      listedOffMarketSale: '한국 상장주식 장외거래 과세 범위',
    },
    localPolicy: {
      title: '로컬 정책 파일',
      localPath: '로컬 경로',
      fallback: '대체 예시',
      save: '로컬 세금 가정 저장',
    },
    calculationBasis: {
      title: '계산 기준',
      info: '플래너가 사용하는 주요 출처입니다. 이후 연도의 인플레이션과 조세조약상 원천 판단은 신고 결론이 아니라 계획 가정입니다.',
      federalBrackets: '2026년 연방 세율 구간',
      federalBracketsNote: 'IRS Rev. Proc. 2025-32 요약',
      capitalGainNetting: '양도소득 상계',
      capitalGainNettingNote: 'IRS Topic 409',
      foreignTaxCreditLimit: '외국납부세액공제 한도',
      foreignTaxCreditLimitNote: 'IRS Form 1116 개요',
      californiaSchedule: '캘리포니아 스케줄',
      californiaScheduleNote: '2025 FTB Schedule Y',
    },
  },
})
