import { defineCopy } from '@/lib/ui-copy/define'

export const transactions = defineCopy({
  en: {
    title: 'Transactions',
    emphasis: 'Transactions',
    subtitle: 'Most recent ledger rows from the normalized transaction TSV.',
    card: 'Recent transactions',
    searchPlaceholder: 'Ticker, name, account, or broker',
    summary: (shown: string, total: string) => `${shown} of ${total} recent rows`,
    filters: { market: 'Market', broker: 'Broker', account: 'Account', type: 'Type', term: 'Term', status: 'Status' },
    columns: {
      market: 'Market',
      date: 'Date',
      broker: 'Broker',
      account: 'Account',
      type: 'Type',
      ticker: 'Ticker',
      name: 'Name',
      quantity: 'Qty',
      amount: 'Amount',
      baseAmount: 'Base Amount',
      source: 'Source',
      page: 'Page',
    },
  },
  ko: {
    title: '거래 내역',
    emphasis: '내역',
    subtitle: '정규화된 거래 TSV에서 읽은 최근 원장 행입니다.',
    card: '최근 거래',
    searchPlaceholder: '종목코드, 종목명, 계좌 또는 증권사',
    summary: (shown: string, total: string) => `최근 ${total}건 중 ${shown}건`,
    filters: { market: '시장', broker: '증권사', account: '계좌', type: '유형', term: '과세 구분', status: '상태' },
    columns: {
      market: '시장',
      date: '거래일',
      broker: '증권사',
      account: '계좌',
      type: '유형',
      ticker: '종목코드',
      name: '종목명',
      quantity: '수량',
      amount: '거래금액',
      baseAmount: '원화 환산',
      source: '원본',
      page: '페이지',
    },
  },
})
