import type { Language } from '@/lib/i18n'

export const TAX_PLANNING_COPY = {
  en: {
    page: {
      eyebrow: 'Tax',
      title: 'Tax Planning',
      emphasis: 'Planning',
      subtitle: 'Compare Korea and US stock sale timing across multiple years. Results are review estimates, not tax filing advice.',
      usingExampleAssumptions: 'Using example assumptions',
      editAssumptions: 'Edit assumptions',
      openStaticOpportunityAnalysis: 'Open static opportunity analysis',
      annualFilingProfile: 'Annual filing profile',
      annualFilingProfileInfo: "Filing flags track whether that country needs reporting work in a year. Tax calc flags decide whether that country's tax estimate is included in planning math.",
      baseAssumptions: 'Base assumptions',
      annualTargetScenarioComparison: 'Annual target scenario comparison',
      selectedSingleYearTaxSplit: 'Selected single-year tax split',
      warnings: 'Warnings',
      recommendedSaleLotSequence: 'Recommended sale-lot sequence',
      allOpenLotCandidates: 'All open lot candidates',
    },
    settings: {
      title: 'Plan Settings',
      subtitle: 'Choose sale-timing rules and date ranges, then recalculate the plan.',
      badge: 'Calculated with current prices and FX',
      schedulingRule: 'Scheduling rule',
      schedulingRuleInfo: 'Choose the deterministic scheduling rule. Tax calculations remain rule-based; no market forecast or LLM judgment is applied here.',
      staged: 'Stage sales after long-term eligibility',
      earliestLongTerm: 'Sell at earliest long-term eligibility',
      waitUsOnly: 'Wait for US-only filing',
      accelerateLosses: 'Accelerate loss harvesting',
      schedulingHint: 'Controls when each tax lot first enters the schedule.',
      executionWindow: 'Execution window',
      executionWindowInfo: 'For the staged plan, divide current priced lot value across this many months. Other plans use their earliest permitted dates.',
      months: 'months',
      executionHint: 'Applies to staged plans.',
      taxHorizon: 'Tax horizon',
      years: 'years',
      horizonHint: 'Includes annual filing-profile changes.',
      rebuild: 'Rebuild plan',
    },
    candidateTable: {
      empty: 'No sale candidates with open tax lots',
      position: 'Position',
      account: 'Account',
      acquired: 'Acquired',
      term: 'Term',
      quantity: 'Qty',
      proceeds: 'Proceeds',
      baseGainLoss: 'Base G/L',
      grossLotTax: 'Gross Lot Tax',
      afterTax: 'After Tax',
      notAvailable: 'n/a',
    },
    overview: {
      title: 'Selected plan',
      info: 'This plan uses tax-lot acquisition dates, annual filing profiles, current prices, and current FX. It does not use a market forecast.',
      executionWindow: 'Recommended execution window',
      to: 'to',
      whyThisMatters: 'Why this matters',
      longTermTreatment: (pct: string) => `${pct}% of planned proceeds receive long-term treatment under this schedule.`,
      plannedSales: 'Planned sales',
      pricedLots: (count: string) => `${count} priced lots`,
      estimatedTax: 'Estimated tax',
      longTermPct: (pct: string) => `${pct}% long-term`,
      afterTaxCash: 'After-tax cash',
      saleInstructions: (count: string) => `${count} sale instructions`,
      inputCoverage: 'Input coverage',
      inputCoverageInfo: 'How much of the current holdings value can be connected to priced tax lots for planning.',
      coverageHint: (issues: string, unpriced: string) => `${issues} issues · ${unpriced} unpriced`,
      reviewInputRange: 'Review the input range.',
      coverageWarning: 'The planned amount is greater than the current holding market value, so coverage exceeds 100%. Check for duplicate tax lots or stale prices before using the result.',
      lotsStillWaiting: 'Lots still waiting',
      waitingLots: (lots: string, amount: string, next: string | null) => `${lots} lots representing ${amount} have not crossed one year.${next ? ` Next: ${next}.` : ''}`,
      estimatedTermBenefit: 'Estimated term benefit',
      termBenefit: (amount: string) => `Waiting for long-term treatment avoids an estimated ${amount} of federal rate difference on currently profitable short-term lots.`,
      waitingUntil2028: 'Waiting until 2028',
      saving: 'saving',
      extraTax: 'extra tax',
      waitUntil2028: (label: string, amount: string, duration: string, earliest: string, wait: string) => `Estimated ${label}: ${amount}, for about ${duration} more waiting. KR top-up changes from ${earliest} to ${wait}.`,
    },
    comparison: {
      title: 'Plan comparison',
      info: 'Every row sells the same currently priced lots. Only timing and holding-term treatment change.',
      lowestEstimatedTax: 'Lowest estimated tax',
      scale: 'Tax bars share one scale. Shorter is lower.',
      selected: 'Selected',
      lowestTax: 'Lowest tax',
      estimatedTax: 'Estimated tax',
      earliestBaseline: 'Earliest baseline',
      less: (amount: string) => `${amount} less`,
      more: (amount: string) => `${amount} more`,
      execution: 'Execution',
      to: 'to',
      longTermSales: 'Long-term sales',
      averageWait: 'Average wait',
      krTopUp: 'KR top-up',
    },
    savedPlans: {
      title: 'Saved execution plans',
      info: 'Saving creates an immutable calculation snapshot. Review and execution states are recorded separately from the original tax estimate.',
      recent: (count: string) => `${count} recent`,
      saveCurrentCalculation: 'Save current calculation',
      saveDescription: 'Freeze the selected strategy, quantities, dates, tax assumptions, and lot-level instructions before review.',
      planName: 'Plan name',
      placeholder: 'e.g. 2026 staged baseline',
      saveAsDraft: 'Save as draft',
      storageNote: 'Stored locally in an ignored private JSON file; it is not committed to the public repository.',
      execution: 'Execution',
      planned: 'planned',
      executed: (done: string, total: string) => `${done} / ${total} executed`,
      empty: 'No saved plans yet. Save the current calculation when it is ready for review.',
    },
    annualTax: {
      title: 'Annual tax roll-up',
      info: 'The annual result nets scheduled gains and losses, stacks short-term gains on projected ordinary income, applies long-term brackets, NIIT and California tax, then applies only the configured cross-border credit model.',
      netTax: 'Net tax',
      sales: 'Sales',
      netGainLoss: 'Net G/L',
      usGross: 'US gross',
      krGross: 'KR gross',
      creditUsed: 'Credit used',
      afterTaxCash: 'After-tax cash',
      taxComponents: 'Tax components',
      taxYear: 'Tax year',
      profile: 'Profile',
      credit: 'Credit',
      federalShortTerm: 'Federal ST',
      federalLongTerm: 'Federal LT',
      niit: 'NIIT',
      california: 'California',
      usFtcLimit: 'US FTC limit',
      usFtcUsed: 'US FTC used',
      krCreditUsed: 'KR credit used',
    },
  },
  ko: {
    page: {
      eyebrow: '세금',
      title: '세금 계획',
      emphasis: '계획',
      subtitle: '한국/미국 주식 매도 시점을 여러 해에 걸쳐 비교합니다. 결과는 검토용 추정치이며 세금 신고 조언이 아닙니다.',
      usingExampleAssumptions: '예시 가정 사용 중',
      editAssumptions: '가정 수정',
      openStaticOpportunityAnalysis: '정적 기회 분석 열기',
      annualFilingProfile: '연도별 신고 프로필',
      annualFilingProfileInfo: '신고 플래그는 해당 국가의 보고 작업 필요 여부를 추적합니다. 세금 계산 플래그는 해당 국가의 세금 추정치를 계획 계산에 포함할지 결정합니다.',
      baseAssumptions: '기본 가정',
      annualTargetScenarioComparison: '연간 목표 시나리오 비교',
      selectedSingleYearTaxSplit: '선택한 단일 연도 세금 분해',
      warnings: '경고',
      recommendedSaleLotSequence: '추천 매도 lot 순서',
      allOpenLotCandidates: '전체 열린 lot 후보',
    },
    settings: {
      title: '계획 설정',
      subtitle: '매도 시점 규칙과 기간을 선택한 뒤 계획을 다시 계산하세요.',
      badge: '현재 가격과 FX로 계산',
      schedulingRule: '일정 규칙',
      schedulingRuleInfo: '결정론적 일정 규칙을 선택합니다. 세금 계산은 규칙 기반이며 시장 전망이나 LLM 판단을 사용하지 않습니다.',
      staged: '장기 보유 요건 충족 후 단계적 매도',
      earliestLongTerm: '가장 이른 장기 보유 가능일에 매도',
      waitUsOnly: '미국만 신고하는 시점까지 대기',
      accelerateLosses: '손실 수확 앞당기기',
      schedulingHint: '각 tax lot이 일정에 처음 들어가는 시점을 제어합니다.',
      executionWindow: '실행 기간',
      executionWindowInfo: '단계적 계획에서는 현재 가격이 있는 lot 가치를 이 개월 수로 나눕니다. 다른 계획은 허용되는 가장 이른 날짜를 사용합니다.',
      months: '개월',
      executionHint: '단계적 계획에 적용됩니다.',
      taxHorizon: '세금 계획 기간',
      years: '년',
      horizonHint: '연도별 신고 프로필 변화를 포함합니다.',
      rebuild: '계획 다시 계산',
    },
    candidateTable: {
      empty: '열린 tax lot이 있는 매도 후보가 없습니다',
      position: '포지션',
      account: '계좌',
      acquired: '취득일',
      term: '기간',
      quantity: '수량',
      proceeds: '매도 금액',
      baseGainLoss: '기준 손익',
      grossLotTax: 'lot별 총세금',
      afterTax: '세후 금액',
      notAvailable: '없음',
    },
    overview: {
      title: '선택한 계획',
      info: '이 계획은 tax-lot 취득일, 연도별 신고 프로필, 현재 가격, 현재 FX를 사용합니다. 시장 전망은 사용하지 않습니다.',
      executionWindow: '추천 실행 기간',
      to: '부터',
      whyThisMatters: '중요한 이유',
      longTermTreatment: (pct: string) => `이 일정에서는 계획 매도 금액의 ${pct}%가 장기 보유 처리를 받습니다.`,
      plannedSales: '계획 매도',
      pricedLots: (count: string) => `가격이 있는 lot ${count}개`,
      estimatedTax: '추정 세금',
      longTermPct: (pct: string) => `${pct}% 장기`,
      afterTaxCash: '세후 현금',
      saleInstructions: (count: string) => `매도 지시 ${count}개`,
      inputCoverage: '입력 커버리지',
      inputCoverageInfo: '현재 보유 평가액 중 계획에 사용할 수 있는 가격 있는 tax lot과 연결된 비중입니다.',
      coverageHint: (issues: string, unpriced: string) => `이슈 ${issues}개 · 가격 없음 ${unpriced}개`,
      reviewInputRange: '입력 범위를 확인하세요.',
      coverageWarning: '계획 금액이 현재 보유 평가액보다 커서 커버리지가 100%를 초과합니다. 결과를 사용하기 전에 중복 tax lot이나 오래된 가격을 확인하세요.',
      lotsStillWaiting: '아직 대기 중인 lot',
      waitingLots: (lots: string, amount: string, next: string | null) => `${lots}개 lot, ${amount} 규모가 아직 1년을 넘기지 않았습니다.${next ? ` 다음: ${next}.` : ''}`,
      estimatedTermBenefit: '추정 기간 혜택',
      termBenefit: (amount: string) => `장기 보유 처리를 기다리면 현재 수익 중인 단기 lot에서 연방 세율 차이 약 ${amount}를 피할 수 있습니다.`,
      waitingUntil2028: '2028년까지 대기',
      saving: '절감',
      extraTax: '추가 세금',
      waitUntil2028: (label: string, amount: string, duration: string, earliest: string, wait: string) => `추정 ${label}: ${amount}, 약 ${duration} 더 대기. 한국 추가세는 ${earliest}에서 ${wait}로 바뀝니다.`,
    },
    comparison: {
      title: '계획 비교',
      info: '모든 행은 현재 가격이 있는 동일한 lot을 매도합니다. 달라지는 것은 시점과 보유기간 처리뿐입니다.',
      lowestEstimatedTax: '가장 낮은 추정 세금',
      scale: '세금 막대는 같은 기준을 씁니다. 짧을수록 낮습니다.',
      selected: '선택됨',
      lowestTax: '최저 세금',
      estimatedTax: '추정 세금',
      earliestBaseline: '가장 이른 매도 기준',
      less: (amount: string) => `${amount} 적음`,
      more: (amount: string) => `${amount} 많음`,
      execution: '실행',
      to: '부터',
      longTermSales: '장기 매도',
      averageWait: '평균 대기',
      krTopUp: '한국 추가세',
    },
    savedPlans: {
      title: '저장된 실행 계획',
      info: '저장은 변경 불가능한 계산 스냅샷을 만듭니다. 검토와 실행 상태는 원래 세금 추정치와 별도로 기록됩니다.',
      recent: (count: string) => `최근 ${count}개`,
      saveCurrentCalculation: '현재 계산 저장',
      saveDescription: '검토 전에 선택 전략, 수량, 날짜, 세금 가정, lot별 지시를 고정합니다.',
      planName: '계획 이름',
      placeholder: '예: 2026 staged baseline',
      saveAsDraft: '초안으로 저장',
      storageNote: 'git에 커밋되지 않는 ignored private JSON 파일에 로컬로 저장됩니다.',
      execution: '실행',
      planned: '계획됨',
      executed: (done: string, total: string) => `${done} / ${total} 실행`,
      empty: '저장된 계획이 아직 없습니다. 검토 준비가 되면 현재 계산을 저장하세요.',
    },
    annualTax: {
      title: '연도별 세금 합계',
      info: '연도별 결과는 예정된 이익과 손실을 상계하고, 단기 이익을 예상 근로소득 위에 쌓으며, 장기 구간, NIIT, 캘리포니아 세금, 설정된 국경 간 공제 모델만 적용합니다.',
      netTax: '순세금',
      sales: '매도',
      netGainLoss: '순손익',
      usGross: '미국 총세금',
      krGross: '한국 총세금',
      creditUsed: '사용 공제',
      afterTaxCash: '세후 현금',
      taxComponents: '세금 구성',
      taxYear: '세금 연도',
      profile: '프로필',
      credit: '공제',
      federalShortTerm: '연방 단기',
      federalLongTerm: '연방 장기',
      niit: 'NIIT',
      california: '캘리포니아',
      usFtcLimit: '미국 FTC 한도',
      usFtcUsed: '미국 FTC 사용',
      krCreditUsed: '한국 공제 사용',
    },
  },
} as const

export type TaxPlanningCopy = (typeof TAX_PLANNING_COPY)[Language]

export function getTaxPlanningCopy(language: Language): TaxPlanningCopy {
  return TAX_PLANNING_COPY[language]
}
